### ISSUE TITLE
Bun install, add, upgrade commands do not work

### ISSUE THREAD

**Issue by Xolo-Gamerz** [oven-sh/bun#1127]
### Version

0.1.10

### Platform

Linux DESKTOP-S5AACNE 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Install wsl , ubuntu 22.04.1, install bun and try out bun add , install , upgrade commands

### How often does it reproduce? Is there a required condition?

Reproduces everytime i try out the command

### What is the expected behavior?

Commands should work

### What do you see instead?

![image](https://user-images.githubusercontent.com/90712689/185918446-c9e17524-373c-4145-816d-34c006e6cd68.png)
![image](https://user-images.githubusercontent.com/90712689/185918505-633f7e76-c06f-4a94-bef5-195f1d0f2cba.png)
![image](https://user-images.githubusercontent.com/90712689/185918772-69c577ee-bd1a-4520-b5ae-d9d99e4d25b5.png)

**Comment by neutraali** [comment]
Don't know if directly related, but `bun install / add` are just (apparently) stuck resolving (version `0.1.10`)...

![bun](https://user-images.githubusercontent.com/16540190/185932640-092f0798-9226-49be-9be4-8d433cf15d83.png)

**Comment by Jarred-Sumner** [comment]
There are two separate issues here:
1. Bun seems to be exiting in cases which I don't know how to reproduce (this issue)
2. Install is hanging #490 

@Xolo-Gamerz Is there a package.json in the folder already?

**Comment by Xolo-Gamerz** [comment]
Yep there is a package.json file present already with pnpm but that's bcs I had already tried it with bun init and then bun install. Bun init worked but bun install produced the above mentioned problem.

**Comment by Xolo-Gamerz** [comment]
Any fix on this? @Jarred-Sumner

**Comment by Sjesc** [comment]
I have the same problem on WSL Ubuntu 22. All the commands that communicate with an external source are exiting without any output (create, install, add, remove, upgrade), the rest don't have this problem.

**Comment by adrianwix** [comment]
Same issue here on WSL 2 Ubuntu 20.08.
![image](https://user-images.githubusercontent.com/37629556/186608045-96c8a05d-b09c-4d31-89ee-89ae636e5a24.png)
![image](https://user-images.githubusercontent.com/37629556/186608078-885b047b-00bb-4ce2-8d50-905c7acd9a98.png)

Not even with Verbose file
![image](https://user-images.githubusercontent.com/37629556/186608260-8df71bb3-87de-4137-92f0-c83c2d82cce1.png)

Any clue on how to find out where the error is coming from? I guess you need to test it in WSL 2. Not sure if you have that environment at your disposal

**Comment by bevand10** [comment]
Ubuntu 20.04 LTS (real, not WSL :wink: )

Not only does `bun add` hang during the Resolving stage, `bun init` hangs too...

![Screenshot from 2022-08-25 14-36-15](https://user-images.githubusercontent.com/5892030/186679226-454fa151-8797-4fc4-8ca0-bfdd0a06d1d9.png)

Bun was installed for the 1st time this morning, so:
```
$ bun --version
0.1.10
```

**Comment by Xolo-Gamerz** [comment]
This problem continues to happen even for ubuntu 20.04.4, the previous version of 22.04.1

**Comment by Jarred-Sumner** [comment]
Okay I will get this fixed tonight




Edit: are you on WSL 2 with the latest Linux kernel (checked via windows update?)

**Comment by Xolo-Gamerz** [comment]
Yep I am on latest wsl2 Linux kernel just installed it this week.

**Comment by rktjmp** [comment]
Seems to be reliably reproducible in an ubuntu container if that helps. I also saw it happen on CentOS 9 Stream (5.14) - with and without SELinux which can sometimes cause drama. *Does work* "natively" on my host Arch install (5.19). Root / Non-root also didn't have an effect for what it's worth.

```
podman run --rm -it ubuntu:latest
apt update && apt install curl unzip
curl -fsSL https://bun.sh/install | bash
mkdir -p /root/proj && cd /root/proj
bun ... etc
```

**Comment by thezeronine** [comment]
same issue on WSL2 with 20.04 on Windows 11 (weird that neofetch says Win 10)
![image](https://user-images.githubusercontent.com/7404620/187043071-826a76a4-e3dc-4a46-ae9e-426379b70ded.png)

**Comment by NEARworld** [comment]
![image](https://user-images.githubusercontent.com/102969108/187166861-21ae44cc-1cb2-4464-b25f-fba390a12ba1.png)
WSL2
bun is there but sub commands don't work.

**Comment by Jarred-Sumner** [comment]
> Seems to be reliably reproducible in an ubuntu container if that helps. I also saw it happen on CentOS 9 Stream (5.14) - with and without SELinux which can sometimes cause drama. _Does work_ "natively" on my host Arch install (5.19). Root / Non-root also didn't have an effect for what it's worth.
> 
> ```
> podman run --rm -it ubuntu:latest
> apt update && apt install curl unzip
> curl -fsSL https://bun.sh/install | bash
> mkdir -p /root/proj && cd /root/proj
> bun ... etc
> ```

I can reproduce this!

I think I understand what's happening now.

One of two error conditions are happening and it is supposed to print out a very detailed, helpful error message. But, the code that sets up logging is (incorrectly) run _after_ the error is printed - which causes Bun to never actually log anything.

### For those in this thread trying to use Bun: 

**please install Bun v0.1.8 until this issue is marked as fixed**

To do that, run:
```bash
curl https://bun.sh/install | bash -s bun-v0.1.8
```

It does not fix the issue you're running into, but it at least gives you more information on what is going wrong.

**Comment by Xolo-Gamerz** [comment]
I did what Jarred said and found the solution to this problem. It was basically a problem with the kernel version. So here is what you do (for wsl users)
-Make sure you are on wsl2
-Open up a powershell or command prompt as an administrator
-Run the following
```bash
wsl --update
```
-Then after updating run,
```bash
wsl --shutdown
```
Then restart the terminal where you were previously using bun and then the commands should work.

**Comment by NEARworld** [comment]
@Xolo-Gamerz Did you do fix it on `bun v0.1.10` or what version?

**Comment by Xolo-Gamerz** [comment]
> 

Did it on bun v0.1.8 first and then on the latest version both seem to work

**Comment by NEARworld** [comment]
@Xolo-Gamerz Wow! I just solved it with your instruction! thanks!
I didn't even change the bun version to `0.1.8`!
My `bun v0.1.10` was installed in WSL2 already.

I will explain how I fixed it.

1. close all the software using `wsl` (In my case, I was using `vscode` on `WSL2` so I closed all the `vscode` windows)
1. Go to `Windows PowerShell`
2. type this command `wsl --update`
3. type this command `wsl --shutdown`
4. Open `vscode` again try the `bun sub commands`
5. It works!

Here's the evidence.
![image](https://user-images.githubusercontent.com/102969108/187178978-35c7228a-d347-480b-bc90-ad91118f4158.png)

Not sure What was really problem but I already tried `wsl --update` before but it didn't work even though I closed all the vs code windows so I think doing `wsl --shutdown` after updating `wsl` was the solution!
@Jarred-Sumner

**Comment by Jarred-Sumner** [comment]
This issue -- not reporting the error -- is fixed once the next canary build completes

**Comment by Davidaprilio** [comment]
> Ubuntu 20.04 LTS (real, not WSL 😉 )
> 
> Not only does `bun add` hang during the Resolving stage, `bun init` hangs too...
> 
> ![Screenshot from 2022-08-25 14-36-15](https://user-images.githubusercontent.com/5892030/186679226-454fa151-8797-4fc4-8ca0-bfdd0a06d1d9.png)
> 
> Bun was installed for the 1st time this morning, so:
> 
> ```
> $ bun --version
> 0.1.10
> ```

the same error still occurs here as it says I also use Ubuntu the same error still occurs here as it says I also use Ubuntu 20.24.4LTS real and bun version 1.1.420.24.4LTS real and bun version 1.1.4
