### ISSUE TITLE
error: No version matching "^x.x.x-next.0||^x.x.x" found for specifier "@x/x" (but package exists)

### ISSUE THREAD

**Issue by stewarthsoj** [oven-sh/bun#11424]
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```
mkdir proj
cd proj
bun init -y
bun add -D @sveltejs/vite-plugin-svelte@4.0.0-next.3
```

### What is the expected behavior?

The package should be installed. The latest version of `@sveltejs/vite-plugin-svelte-inspector` on NPM is `3.0.0-next.2`.

### What do you see instead?

```
warn: incorrect peer dependency "@sveltejs/vite-plugin-svelte@4.0.0-next.3"

error: No version matching "^3.0.0-next.0||^3.0.0" found for specifier "@sveltejs/vite-plugin-svelte-inspector" (but package exists)
```

### Additional information

The package can be installed via another package manager such as npm and pnpm.

**Comment by ghiscoding** [comment]
you wrote that the latest version is `...next.2` but you're trying to install `...next.3`, so it seems normal to get an error since `next.3` is not available. Please note that I'm not sure Bun yet, probably will in the near future

**Comment by dylan-conway** [comment]
Fixed in #11387. It will be included in `v1.1.11` on Wednesday, and it's already in canary (`bun upgrade --canary` to update).

**Comment by ZuBB** [comment]
> Fixed in #11387. It will be included in `v1.1.11` on Wednesday, and it's already in canary (`bun upgrade --canary` to update).

Still getting a very similar error:

```
vv@my-precious /tmp/my-app $ bun install                                                                                                  
bun install v1.1.13 (bd6a6051)                                       
error: No version matching "^4.6.0" found for specifier "eslint-plugin-react-hooks" (but package exists)
vv@my-precious /tmp/my-app $
```
I get it after I follow the official manual https://bun.sh/guides/ecosystem/vite

But after I ran `npm i` in the same directory and then `bun install` again all worked 😖

**Comment by dylan-conway** [comment]
@ZuBB what framework/variant did you choose when creating the vite project? and can you repro this bug consistently?

**Comment by ZuBB** [comment]
> @ZuBB what framework/variant did you choose when creating the vite project? and can you repro this bug consistently?

It was react + ts + swc

**Comment by dylan-conway** [comment]
> > @ZuBB what framework/variant did you choose when creating the vite project? and can you repro this bug consistently?
> 
> It was react + ts + swc.
> 
> Yes, I tried one more time just now. the same thing

Does it still happen if you clear the install cache beforehand (`bun pm cache rm`)?

**Comment by ZuBB** [comment]
> bun pm cache rm

Wow, that helps! Can we do something on your side to make things more obvious for the end user?

**Comment by ZuBB** [comment]
I have a guess: I had a big pause in bun usage. I did a bunch of tests around its v1.0. Did something major change since that?

**Comment by dylan-conway** [comment]
> I have a guess: I had a big pause in bun usage. I did a bunch of tests around its v1.0. Did something major change since that?

We bumped the cache version in #11606 in `bun-v1.1.13` which would invalidate any older entries, so it's surprising ran into this issue. Can you recall any other packages or projects you installed with 1.1.13 before hitting this error with the `bun create vite` project? I think this might be an entirely different bug with a similar result to this issue

**Comment by ZuBB** [comment]
> Can you recall any other packages or projects you installed with 1.1.13 before hitting this error with the bun create vite project?

No, I don't. As I said, I had a pause in bun usage 😕
