### ISSUE TITLE
bun v1.1.12 [WINDOWS?] stuck resolving when adding/installing package NOT in cache

### ISSUE THREAD

**Issue by cpakken** [oven-sh/bun#11526]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Bun install/add still hang on resolve when packages are not in cache. To simulate this remove cache.
`bun pm cache rm`
(This is because trying versions, 1.1.12 -> 1.1.8, only 1.1.8 doesn't hang on install/add packages but then after switching back to v1.1.12 it will resolve because it is in cache)
(I use scoop reset bun@version to switch versions 1.1.12 -> 1.1.8)

start new bun package with `bun init`
(will hang on bun init as well IF empty cache and need to ctrl-c to exit)

Remember to clear cache first to simulate no cache
`bun pm cache rm`

![image](https://github.com/oven-sh/bun/assets/61718569/29a58db8-ff4f-4b14-9f44-7231d2754a1f)

Install only works with v1.1.8 when cache is empty ( or does not contain the packages needed to install)
![image](https://github.com/oven-sh/bun/assets/61718569/bad8db4c-d126-4037-a277-6c2db33c16ec)

Now that it installed with v1.1.8, going back to v1.1.12 will work. 
Note in v1.1.12 removing node_modules and `bun i` will work. BUT if cache is removed via `bun pm cache rm`. Then bun will hang again in `bun i` 
![image](https://github.com/oven-sh/bun/assets/61718569/fc66fa8b-0e4d-4252-ae41-cc022a63c96f)

Same for adding any packages
![image](https://github.com/oven-sh/bun/assets/61718569/e489de71-58cf-445b-b19e-97d571fead89)

I don't think the previous bug https://github.com/oven-sh/bun/issues/11413 is solved

**Comment by cpakken** [comment]
This issue seemed to resolve once I restarted my computer. Wierd!

**Comment by cpakken** [comment]
This issue seems reoccurring after using bun for a bit...

**Comment by nicu-chiciuc** [comment]
I'm having the same issue on macOS 14.4.1 (23E224). 
`bun install` is stuck on Resolving [1/1] (the types for bun).

**Comment by nicu-chiciuc** [comment]
Actually, I was wrong, it seemed to work because before running `bun install --no-cache` I've ran `npm install`.
Removing `node_modules` and the locks and running `bun install --no-cache` again also gets stuck.

**Comment by dm1tryG** [comment]
Same stuck on EC2 AWS

**Comment by egorsmkv** [comment]
Got the same problem on Ubuntu where bun was installed from SNAPs

Resolved by uninstall bun from SNAP: `sudo snap remove bun-js` and install from the official website

**Comment by kwiat1990** [comment]
I’m having this issue right now and I have installed bun following guidelines on the official site for MacOS.

**Comment by cpakken** [comment]
This issue still persists at 1.1.42 and is somewhat inconsistent. On a clean restart, bun install, bun add seems to work without getting stuck. But something happens and bun add / install just hangs on resolves for 120 + seconds. The issue resolves if I restart windows again, but then an hour or two later this issue emmerges

**Comment by cpakken** [comment]
[From https://github.com/oven-sh/bun/issues/5831](https://github.com/oven-sh/bun/issues/5831#issuecomment-2509762569) seems like the issue will resolve if ipv6 is disabled.

bun install commands should work with ipv6 though.

**Comment by Alecyrus** [comment]
any update?

**Comment by RobinTail** [comment]
```shell
$ bun i --verbose
bun install v1.2.2 (c1708ea6)
Loaded 263 hoisted_dependencies
Loaded 383 resolutions
Loaded 383 dependencies
Loaded 8 extern_strings
Loaded 23016 string_bytes
Workspace package "..." has added 0 dependencies, removed 0 dependencies, and updated 2 dependencies
Enqueue package manifest for download: @arethetypeswrong/cli
Enqueue package manifest for download: @types/bun
Enqueue package manifest for download: semver
Enqueue package manifest for download: tsdown
Enqueue package manifest for download: typescript
Enqueue package manifest for download: @emotion/styled
Enqueue package manifest for download: @mui/material
Enqueue package manifest for download: react
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
[PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
  🔍 Resolving [1/8] [PackageManager] waiting for 8 tasks
[PackageManager] waiting for 8 tasks
...
```

**Comment by GoJermangoGo** [comment]
I just spent some hours chasing this. Disabling IPv6 worked temporarily, but my home network was the root cause. Simply yoinking the modem+router from the wall and restarting them fixed everything. Seems Chrome (and `curl`?) are smart enough to fall back to IPv4 automatically so the internet connection appears to work, but simpler utilities (`wget`, `bun install`, `gem install`) will just hang forever.

**Comment by DamChtlv** [comment]
Can confirm it's related to IPV6 and still occurs with v1.2.8  :/
Easy / fast fix i found for now: enable / toggle a VPN _(like WARP)_ and try commands again

**Comment by prakarangs** [comment]
Having the same problem. Bun seems to stuck in resolving after using it for sometimes. Restarting the machine solve the problem for me.

**Comment by phil-flip** [comment]
Resolved by disabling IPv6

**Comment by fomotrader** [comment]
Facing the same issue, I disable and enable IPv6 on mac

**Comment by Zekee69** [comment]
Same issues on windows 11
using command: bunx --bun shadcn@latest add tabs
stuck at 577 or 559, gets stuck at some package and never continues

**Comment by igoroctaviano** [comment]
Same issue here!

**Comment by mylinuxforwork** [comment]
Same issue here.

**Comment by oolongcha024** [comment]
Same issue here Windows 11 with v1.2.23. I tried `bun install --no-cache` and it works for me. 

Here are some logs when I just run `bun install`. 

```
❯ bun install --verbose
bun install v1.2.23 (cf136713)
Enqueue package manifest for download: @tsconfig/node22
   - "@types/node": "^22.18.6" - @types/node@22.18.8
Enqueue package manifest for download: @vitejs/plugin-vue
Enqueue package manifest for download: @vue/tsconfig
Enqueue package manifest for download: npm-run-all2
Enqueue package manifest for download: typescript
Enqueue package manifest for download: vite
Enqueue package manifest for download: vite-plugin-vue-devtools
Enqueue package manifest for download: vue-tsc
   - "vue": "^3.5.22" - vue@3.5.22
Enqueue package manifest for download: undici-types
   - "@vue/shared": "3.5.22" - @vue/shared@3.5.22
   - "@vue/runtime-dom": "3.5.22" - @vue/runtime-dom@3.5.22
   - "@vue/compiler-dom": "3.5.22" - @vue/compiler-dom@3.5.22
   - "@vue/compiler-sfc": "3.5.22" - @vue/compiler-sfc@3.5.22
   - "@vue/server-renderer": "3.5.22" - @vue/server-renderer@3.5.22
Enqueue package manifest for download: csstype
   - "@vue/reactivity": "3.5.22" - @vue/reactivity@3.5.22
   - "@vue/runtime-core": "3.5.22" - @vue/runtime-core@3.5.22
   - "@vue/compiler-core": "3.5.22" - @vue/compiler-core@3.5.22
Enqueue package manifest for download: @babel/parser
Enqueue package manifest for download: estree-walker
Enqueue package manifest for download: magic-string
Enqueue package manifest for download: postcss
Enqueue package manifest for download: source-map-js
   - "@vue/compiler-ssr": "3.5.22" - @vue/compiler-ssr@3.5.22
Enqueue package manifest for download: entities
  🔍 Resolving [1/16] [fetch] > HTTP/1.1 GET https://registry.npmjs.org/@tsconfig%2fnode22
[fetch] > If-None-Match: W/"10c44e06426e16274077100c3490c9cf"
[fetch] > Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
[fetch] > Connection: keep-alive
[fetch] > User-Agent: Bun/1.2.23
[fetch] > Host: registry.npmjs.org
[fetch] > Accept-Encoding: gzip, deflate, br, zstd

[fetch] > HTTP/1.1 GET https://registry.npmjs.org/@vitejs%2fplugin-vue
[fetch] > If-None-Match: W/"eee5f9211745cd09238eb41d22d0da3f"
[fetch] > Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
[fetch] > Connection: keep-alive
[fetch] > User-Agent: Bun/1.2.23
[fetch] > Host: registry.npmjs.org
[fetch] > Accept-Encoding: gzip, deflate, br, zstd

...[Omitted similar logs]...

[fetch] < 200 Connection established

[fetch] < 200 Connection established

...[Omitted similar logs]...

[fetch] < 304 Not Modified
[fetch] < Date: Thu, 02 Oct 2025 03:11:38 GMT
[fetch] < Connection: keep-alive
[fetch] < CF-Ray: 9881037c79691fbb-HKG
[fetch] < CF-Cache-Status: HIT
[fetch] < Access-Control-Allow-Origin: *
[fetch] < Age: 82
[fetch] < Cache-Control: public, max-age=300
[fetch] < ETag: "992114659dee36a749643069d6b09582"
[fetch] < Last-Modified: Wed, 01 Oct 2025 07:14:44 GMT
[fetch] < Vary: Accept-Encoding
[fetch] < Set-Cookie: _cfuvid=[REDACTED]; path=/; domain=.npmjs.org; HttpOnly; Secure; SameSite=None
[fetch] < Server: cloudflare

[fetch] < 304 Not Modified
[fetch] < Date: Thu, 02 Oct 2025 03:11:38 GMT
[fetch] < Connection: keep-alive
[fetch] < CF-Ray: 9881037c7f9e0ec8-HKG
[fetch] < CF-Cache-Status: HIT
[fetch] < Access-Control-Allow-Origin: *
[fetch] < Age: 99
[fetch] < Cache-Control: public, max-age=300
[fetch] < ETag: "2c833ce37ddf03db0f85ef208f666500"
[fetch] < Last-Modified: Tue, 09 Sep 2025 12:52:41 GMT
[fetch] < Vary: Accept-Encoding
[fetch] < Set-Cookie: _cfuvid=[REDACTED]; path=/; domain=.npmjs.org; HttpOnly; Secure; SameSite=None
[fetch] < Server: cloudflare

...[Omitted similar logs]...
```

Relevant Issues: 
- https://github.com/oven-sh/bun/issues/5831
- https://github.com/oven-sh/bun/issues/20886
