### ISSUE TITLE
connection error with bun, postgresql and Docker

### ISSUE THREAD

**Issue by maxime-aubry** [oven-sh/bun#11929]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

add this docker-compose.yml file :

``` YML
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules

  shadow-hunters-web-api:
    build:
      context: ./
      dockerfile: ./apps/shadow-hunters-web-api/Dockerfile
    ports:
      - 4000:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5436:5432
    volumes:
      #- ./db/data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "root", "-d", "shadow_hunters"]
      interval: 5s
      timeout: 10s
      retries: 5

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 15432:80
  
volumes:
  pgdata: {}
```

run this command :
`docker-componse up`

run this other command to run the project what use postgres :
`bun run start:dev auth`

### What is the expected behavior?

I would like to connect to the database please.

### What do you see instead?

Actually i get an error :

`[Nest] 2740  - 18/06/2024 00:31:54   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)`
    

### Additional information

Here is [the source code](https://github.com/maxime-aubry/shadow-hunters-web-api/tree/develop) if you want to test.

Docker Desktop : 4.31.1
Docker Compose version v2.27.0-desktop.2

Thanks for helping

**Comment by Jarred-Sumner** [comment]
@maxime-aubry this is running in Node.js, you may need to do `bun --bun start:dev auth` to force it to use Bun.

`onlookupall` is not a function we've implemented in Bun, nor is `GetAddrInfoReqWrap` something we've implemented. We have implemented `node:dns`, just not those specific Node C++ bindings where this error is being thrown

My guess here is the hostname being passed is incorrect somewhere. Likely involving an environment variable not being set when it should be. Or something in the Docker configuration isn't exposed that should be exposed.

I'm closing as not planned because it's running in Node and not in Bun, but if you run into issues when using bun's runtime here without it reproducing on Node please leave a comment and I'll re-open

**Comment by maxime-aubry** [comment]
Hello.

Thanks for your reply.

I updated my project, and i use your command line.
But i still get an error, and node still appears.
I don't understand.

``` Powershell
PS F:\Projets\shadow-hunters-web-api> bun --bun start:dev auth
$ nest start --watch auth

 Info  Webpack is building your sources...

Error: Process 17120 doesn't have open IPC channels
Error: Process 18868 doesn't have open IPC channels
webpack 5.90.1 compiled successfully in 827 ms
[Nest] 22848  - 18/06/2024 22:13:52     LOG [NestFactory] Starting Nest application...
[Nest] 22848  - 18/06/2024 22:13:52     LOG [InstanceLoader] TypeOrmModule dependencies initialized +12ms
[Nest] 22848  - 18/06/2024 22:13:52     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 22848  - 18/06/2024 22:13:52     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 22848  - 18/06/2024 22:13:52     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 22848  - 18/06/2024 22:13:52     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 22848  - 18/06/2024 22:13:54   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
[Nest] 22848  - 18/06/2024 22:13:58   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
ECONNREFUSED: Failed to connect
    at connect (native)
    at connect (node:net:303:20)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\connection.js:46:6)
    at _connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\client.js:117:6)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\client.js:162:6)
    at newClient (F:\Projets\shadow-hunters-web-api\node_modules\pg-pool\index.js:238:8)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg-pool\index.js:213:11)
    at F:\Projets\shadow-hunters-web-api\src\driver\postgres\PostgresDriver.ts:1522:17
    at new Promise (:2:22)
    at F:\Projets\shadow-hunters-web-api\src\driver\postgres\PostgresDriver.ts:1521:18
    at createPool (F:\Projets\shadow-hunters-web-api\src\driver\postgres\PostgresDriver.ts:1466:28)
    at F:\Projets\shadow-hunters-web-api\src\driver\postgres\PostgresDriver.ts:360:32
    at connect (F:\Projets\shadow-hunters-web-api\src\driver\postgres\PostgresDriver.ts:346:26)
    at F:\Projets\shadow-hunters-web-api\src\data-source\DataSource.ts:256:18
    at initialize (F:\Projets\shadow-hunters-web-api\src\data-source\DataSource.ts:249:18)
    at processTicksAndRejections (:13:78)
```

Here is [the source code](https://github.com/maxime-aubry/shadow-hunters-web-api/tree/develop).

**Comment by maxime-aubry** [comment]
I change the command line to start the project :
```powershell
bun --bun --watch ./apps/auth/src/main.ts
```

Displayed error has a little bit changed :

```powershell
PS F:\Projets\shadow-hunters-web-api> bun start:dev:auth
$ bun --bun --watch ./apps/auth/src/main.ts
[Nest] 10412  - 19/07/2024 23:48:56     LOG [NestFactory] Starting Nest application...
[Nest] 10412  - 19/07/2024 23:48:56     LOG [InstanceLoader] TypeOrmModule dependencies initialized +19ms
[Nest] 10412  - 19/07/2024 23:48:56     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 10412  - 19/07/2024 23:48:56     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 10412  - 19/07/2024 23:48:56     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 10412  - 19/07/2024 23:48:59   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
[Nest] 10412  - 19/07/2024 23:49:02   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
ECONNREFUSED: Failed to connect
    at connect (native)
    at connect (node:net:302:10)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\connection.js:44:17)
    at _connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\client.js:113:11)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg\lib\client.js:162:12)
    at newClient (F:\Projets\shadow-hunters-web-api\node_modules\pg-pool\index.js:237:12)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\pg-pool\index.js:212:10)
    at <anonymous> (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\driver\postgres\PostgresDriver.js:1174:18)
    at new Promise (:1:11)
    at <anonymous> (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\driver\postgres\PostgresDriver.js:1173:20)
    at createPool (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\driver\postgres\PostgresDriver.js:1138:22)
    at <anonymous> (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\driver\postgres\PostgresDriver.js:259:38)
    at connect (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\driver\postgres\PostgresDriver.js:251:21)
    at <anonymous> (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\data-source\DataSource.js:136:27)
    at initialize (F:\Projets\shadow-hunters-web-api\node_modules\typeorm\data-source\DataSource.js:132:24)
    at processTicksAndRejections (:12:39)
```

**Comment by maxime-aubry** [comment]
@Jarred-Sumner could you re-open this issue please ?

**Comment by IAmNelu** [comment]
@maxime-aubry did you solve the issue. I had similar issue using bun, trying to connect to supabase. When testing locally everything was working fin, as soon as I tried in the Docker I had this problem
