### ISSUE TITLE
fs.ReadStream does not emit data events

### ISSUE THREAD

**Issue by johnp789** [oven-sh/bun#12099]
### What version of Bun is running?

1.1.16

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

A Raspberry Pi Pico is connected to a Mac USB port.  The Pico shows up as a character special device at `/dev/cu.usbmodem1201` and sends a 29-byte line every 250ms or so, which I would like to read with Bun.  

With the script `read-test.js` below, the behavior of Bun is different from the behavior of Node.

```javascript
import * as fs from "node:fs"

const inp = fs.createReadStream("/dev/cu.usbmodem1201")
inp.on("data", function(chunk) {
  console.log("in:", chunk.length)
})
inp.on("open", function() {
  console.log("on open")
})
inp.on("close", function() {
  console.log("on close")
})
setTimeout(function() {
  console.log("Closing file now...")
  inp.close()
}, 3000)
```

### What is the expected behavior?

With Node.js v20.11.1, several data events are received before exiting.  The device writes 29-character lines about 250ms apart.
```shell
$ node read-test.js
on open
in: 27
in: 2
in: 27
in: 2
in: 29
in: 29
in: 29
in: 29
Closing file now...
on close
```

### What do you see instead?

Bun runs without reporting an error, but no data events are emitted.
```shell
$ bun read-test.js
on open
Closing file now...
on close
```

### Additional information

The Pi Pico streams data from a sensor.  My goal here is to read each line from the USB-attached Pi Pico and process the line immediately.  Eventually, the script needs to run on Windows, Mac, and Linux.

Changing the script to read from the Mac's `/dev/random`, Bun has some data events, but the behavior is still different from Node.js.  Bun evidently uses a larger read buffer.  Is there a way to set a read timeout for Bun, so that it does not wait for the read buffer to fill up before emitting a data event?

```javascript
import * as fs from "node:fs"

// const path = "/dev/cu.usbmodem1201"
const path = "/dev/random"
const inp = fs.createReadStream(path)
let chunkCount = 0
inp.on("data", function(chunk) {
  chunkCount += 1
  console.log(`in: ${chunk.length} ${chunkCount}`)
  if(chunkCount > 5) {
    console.log("Closing file now due to chunk count...")
    inp.close()
  }
})
inp.on("open", function() {
  console.log("on open")
})
inp.on("close", function() {
  console.log("on close")
})
setTimeout(function() {
  console.log("Closing file now...")
  inp.close()
}, 1000)
```

```shell
$ node read-test.js
on open
in: 65536 1
in: 65536 2
in: 65536 3
in: 65536 4
in: 65536 5
in: 65536 6
Closing file now due to chunk count...
on close
Closing file now...
$ bun read-test.js
on open
in: 262144 1
in: 262144 2
in: 262144 3
in: 262144 4
in: 262144 5
in: 262144 6
Closing file now due to chunk count...
in: 262144 7
Closing file now due to chunk count...
on close
Closing file now...
```

**Comment by museadam** [comment]
createReadStream seems to work because it gets to the "on open" log, i would like to see further debugging of the data from the createReadStream to see what data it is getting.


If you aren't using the node fs functions mkdir and readdir then you should use buns api file I/O (https://bun.sh/docs/api/file-io)
and what you could do...
Instead of: `const inp =fs.createReadStream(path)` you can use `Bun.file(path);`
and get the size with `const chunckSize = Bun.size;`

**Comment by johnp789** [comment]
I tried using `Bun.file(path)` instead, but the stream still does not return chunks, at least not in a reasonable time for this slow stream.  Using `/dev/random` instead, I see chunks of size 262144, but the reported `inp.size` is `Infinity`.
```javascript
// const inp = Bun.file("/dev/cu.usbmodem1201")
const inp = Bun.file("/dev/random")
const stream = await inp.stream()
console.log(`chunk size is ${inp.size}`) // chunk size is Infinity
let chunkCount = 0
for await (const chunk of stream) {
  console.log(chunk.length);             // 262144
  if (++chunkCount > 3) {
      break
  }
}
```

**Comment by johnp789** [comment]
Yes, this still reproduces on Bun 1.1.27.  The `read-test.js` script above still works OK with node 20.16.0 and fails to read anything with Bun 1.1.27.

**Comment by johnp789** [comment]
Here's a reproducer using a fifo.

```javascript
// fifo-writer.mjs
import * as fs from "node:fs"

const outp = fs.createWriteStream("my-fifo")
let i = 1
setInterval(() => {
  outp.write(`Message ${i++}\n`)
}, 10)
```

```javascript
// fifo-reader.mjs
import * as fs from "node:fs"

const inp = fs.createReadStream("my-fifo")
let chunkCount = 1
inp.on("data", function (chunk) {
  console.log(`${chunkCount++}: ${chunk.toString().trim()}`)
  if (chunkCount > 5) {
    console.log("Closing file now due to chunk count...")
    inp.close()
  }
})
inp.on("open", function () {
  console.log("on open")
})
inp.on("close", function () {
  console.log("on close")
})
```
Running the writer in the background, try the reader with node (twice) and with bun:
```shell
$ mkfifo my-fifo
$ bun fifo-writer.mjs &
[1] 50572
$ node fifo-reader.mjs
on open
1: Message 1
2: Message 2
3: Message 3
4: Message 4
5: Message 5
Closing file now due to chunk count...
on close
$ node fifo-reader.mjs
on open
1: Message 198
2: Message 199
3: Message 200
4: Message 201
5: Message 202
Closing file now due to chunk count...
on close
$ bun fifo-reader.mjs  # hangs, interrupt with Ctrl-C
on open
^C
```

**Comment by johnp789** [comment]
There have been several releases since I last checked, so I tried it again, and the fifo reproducer still fails (hangs) with bun 1.1.45.

**Comment by RiskyMH** [comment]
I believe this is fixed in canary now (due to `node:fs` compat improvements). Please let me know if it is solving your issues :)

**Comment by johnp789** [comment]
I still see some difference between Bun v1.2.0-canary.3+4641b6184 (Linux x64) and Node v22.13.1. 

```javascript
// fifo-writer.mjs (some changes since last time)
import * as fs from "node:fs"

const outp = fs.createWriteStream("my-fifo")
outp.on('error', (err) => {
  outp.end()
  process.exit(0)
})

let i = 1
setInterval(() => {
  outp.write(`Message ${i++}\n`)
}, 1000)
```

```shell
$ mkfifo my-fifo
$ bun fifo-writer.mjs &
[1] 11855
$ node fifo-reader.mjs 
on open
1: Message 1
Message 2
Message 3
Message 4
2: Message 5
3: Message 6
4: Message 7
5: Message 8
Closing file now due to chunk count...
on close
$ 

[1]+  Done                    bun fifo-writer.mjs
$ bun fifo-writer.mjs &
[1] 11938
$ bun fifo-reader.mjs 
on open
ESPIPE: invalid seek, read
      fd: 12,
 syscall: "read",
   errno: -29,
    code: "ESPIPE"


Bun v1.2.0-canary.3+4641b6184 (Linux x64)
$ 

[1]+  Done                    bun fifo-writer.mjs
```

**Comment by Jarred-Sumner** [comment]
The bug is that we can't be using the `pread` syscall when the file type is not seekable

**Comment by johnp789** [comment]
Since I hadn't checked in a while, I gave this a try again, and canary still reports `ESPIPE`.
```shell
$ bun fifo-reader.mjs
on open
ESPIPE: invalid seek, read
      fd: 4,
 syscall: "read",
   errno: -29,
    code: "ESPIPE"


Bun v1.2.11-canary.5+ef17164c6 (macOS arm64)
```

**Comment by Jarred-Sumner** [comment]
Fixed in #22591 

Previous:
```js
❯ bun fifo-reader.mjs
on open
ESPIPE: invalid seek, read
      fd: 4,
 syscall: "read",
   errno: -29,
    code: "ESPIPE"

```
#22591:
```js
❯ bun-latest fifo-reader.mjs
on open
1: Message 1
2: Message 2
3: Message 3
4: Message 4
5: Message 5
Closing file now due to chunk count...
on close
```
