### ISSUE TITLE
SegmentationFault on bun install

### ISSUE THREAD

**Issue by rsc1975** [oven-sh/bun#1234]
### Version

0.1.11 (canary 2022-09-12)

### Platform

`Linux ThinkPad-Rob 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux `

### What steps will reproduce the bug?

In an empty dir, with the following package.json:

```json
{
  "version": "0.0.1",
  "name": "issue-bun-install",
  "devDependencies": {
    "http-server": "latest"
  },
  "dependencies": {}
}
```

run:

```
bun install
```

### What is the expected behavior?

No errors

### What do you see instead?

```
$ bun install

SegmentationFault at 0x8000000000000000


----- bun meta -----
Bun v0.1.11 (2b02f7eb) Linux x64 #1 SMP Wed Jul 27 02:20:31 UTC 2022
InstallCommand: 
Elapsed: 6ms | User: 0ms | Sys: 8ms
RSS: 69.21MB | Peak: 21.00MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

### Additional information

The error happens with whatever dependency or even without any deps.

**Comment by Jarred-Sumner** [comment]
This should be fixed in latest canary

If it isn't, please comment

**Comment by rsc1975** [comment]
I've just upgraded, but the problem persists:

```$ bun install

SegmentationFault at 0x8000000000000000


----- bun meta -----
Bun v0.1.11 (0935ab14) Linux x64 #1 SMP Wed Jul 27 02:20:31 UTC 2022
InstallCommand:
Elapsed: 4ms | User: 0ms | Sys: 4ms
RSS: 69.21MB | Peak: 19.13MB | Commit: 69.21MB | Faults: 0
----- bun meta ----- 
```

**Comment by rsc1975** [comment]
An update, the problem persists in WSL2 with Win11 and Ubuntu & Debian, however in the same host with a Hyper-V VM machine with Kali linux works fine. I've removed the `$HOME/.bun` dir and installed all from scratch.

Kali uname: `Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux`
Ubuntu WSL2 uname: `Linux ThinkPad-Rob 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Jarred-Sumner** [comment]
Hm. Can you try deleting ~/.bun/install?

**Comment by rsc1975** [comment]
Same result, I also removed (in a different test) the entire `$HOME/.bun` and install everything again, with the same result.

Now the error happens but there is no `.bun/install` dir: 
```
$ ls ~/.bun
bin
```

[update]

I've just reproduced it in a Google Cloud  instance: `Linux instance-1 5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux` 

The machine was created right now, completely clean:

Commands to reproduce:

```
sudo apt update
sudo apt install unzip
curl https://bun.sh/install | bash
# Update PATH with bun executable
bun upgrade --canary
mkdir _test
cd _test
cp /whatever/package.json .
bun install
```

**Comment by Jarred-Sumner** [comment]
@rsc1975 can you try once again? Pretty good chance this is fixed now

**Comment by rsc1975** [comment]
I've just tested in Ubuntu 22.04 and Kali linux, both of them in Win11 WSL2 and It works fine now. I've also tested in a clean Google cloud Instance with Ubuntu 22.04 and all is fine now, so I close the issue.
