### ISSUE TITLE
Stream closed with error code NGHTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by oliverfunk** [oven-sh/bun#12544]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

temp.js:

```ts
import { Client, fql } from "fauna";

const faunaClient = new Client({
  secret: "",
});
const qr = await faunaClient.query(fql`newId()`);
console.log(qr);
```

You don't even need a key to proc this issue.

You'll need to install the fauna package: `bun i fauna`

### What is the expected behavior?

That it works, returning a result with an id.

### What do you see instead?

```bash
❯ bun run temp.ts
597 |     do {
598 |       try {
599 |         return await __privateMethod(this, _doRequest, doRequest_fn).call(this, req);
600 |       } catch (error) {
601 |         if (error?.code !== "ERR_HTTP2_GOAWAY_SESSION") {
602 |           throw new NetworkError(
                      ^
NetworkError: The network connection encountered a problem.
      at /.../node_modules/fauna/dist/node/index.js:602:17
      at processTicksAndRejections (native:1:1)

2 | var streamErrorFromCode = function(code) {
                                      ^
error: Stream closed with error code 1
 errno: 1
  code: "ERR_HTTP2_STREAM_ERROR"

      at node:http2:2:35
      at streamError (node:http2:576:16)
      at #onRead (node:http2:708:10)
      at emit (node:events:180:48)
      at addChunk (node:stream:2029:22)
      at readableAddChunk (node:stream:1983:30)
      at data (node:net:76:9)

Bun v1.1.20 (macOS arm64)
```

### Additional information

This could be related to #6204 or #887

**Comment by oliverfunk** [comment]
This was fixed in `1.1.26`

Thank you!

**Comment by djkato** [comment]
It's still an issue for me.

`djkato> cat test.ts`
```ts
import { Client, fql } from "fauna"

const faunaClient = new Client({
    secret: ""
})
const qr = await faunaClient.query(fql`newId()`)
console.log(qr)
```

`djkato> bun test.ts`
```ts
597 |     do {
598 |       try {
599 |         return await __privateMethod(this, _doRequest, doRequest_fn).call(this, req);
600 |       } catch (error) {
601 |         if (error?.code !== "ERR_HTTP2_GOAWAY_SESSION") {
602 |           throw new NetworkError(
                      ^
NetworkError: The network connection encountered a problem.
      at /home/djkato/Code/portfolio-new/cms/node_modules/fauna/dist/node/index.js:602:17
      at processTicksAndRejections (native:1:1)

2 | function streamErrorFromCode(code) {
                                ^
error: Stream closed with error code 1
 errno: 1
  code: "ERR_HTTP2_STREAM_ERROR"

      at streamErrorFromCode (node:http2:2:29)
      at streamError (node:http2:588:16)
      at #onRead (node:http2:720:10)
      at emit (node:events:201:48)
      at addChunk (node:stream:2044:22)
      at readableAddChunk (node:stream:1998:30)
      at data (node:net:120:9)

Bun v1.1.29 (Linux x64)
```

**Comment by dragonmaster784** [comment]
I have this issue with FCM and Bun 1.1.42. 
Strangely downgrading to Firebase Admin 11.11.0 works fine, but this obviously doesn't resolve the underlying issue on later versions.

**Comment by oliverfunk** [comment]
This actually wasn't fixed, I was wrong and shouldn't have closed it.

I'm sure there is another way to proc the issue but I don't know of another library that uses HTTP2 stream and I don't know to write one myself.

**Comment by taylorcode** [comment]
This also affects https://www.npmjs.com/package/@connectrpc/connect-node, which appears to use `node:http2` internally.

```
import {createClient} from '@connectrpc/connect';
import {createConnectTransport} from '@connectrpc/connect-node';

import {MyRpcService} from 'proto/gen/my_rpc_service';

const transport = createConnectTransport({
  httpVersion: '2',
  baseUrl: 'example.com/api',
});

const client = createClient(
  MyRpcService,
  transport,
);

// throws error
const stream = client.someRpcStream();
for await (const {msg} of stream) {
  ...
}
```


```
34 |      * Outgoing details are only relevant for the server side - a service may
35 |      * raise an error with details, and it is up to the protocol implementation
36 |      * to encode and send the details along with error.
37 |      */
38 |     constructor(message, code = Code.Unknown, metadata, outgoingDetails, cause) {
39 |         super(createMessage(message, code));
             ^
ConnectError: [internal] Stream closed with error code NGHTTP2_PROTOCOL_ERROR
 rawMessage: "Stream closed with error code NGHTTP2_PROTOCOL_ERROR",
       code: 13,
   metadata: Headers {},
    details: [],

      at new ConnectError (/node_modules/@connectrpc+connect@2.0.0_@bufbuild+protobuf@2.2.2/node_modules/@connectrpc/connect/dist/esm/connect-error.js:39:9)
      at from (/node_modules/@connectrpc+connect@2.0.0_@bufbuild+protobuf@2.2.2/node_modules/@connectrpc/connect/dist/esm/connect-error.js:72:20)
      at connectErrorFromNodeReason (/node_modules/@connectrpc+connect-node@2.0.0_@bufbuild+protobuf@2.2.2_@connectrpc+connect@2.0.0/node_modules/@connectrpc/connect-node/dist/esm/node-error.js:52:29)
      at reject (/node_modules/@connectrpc+connect-node@2.0.0_@bufbuild+protobuf@2.2.2_@connectrpc+connect@2.0.0/node_modules/@connectrpc/connect-node/dist/esm/node-universal-client.js:293:63)
      at h2StreamError (/node_modules/@connectrpc+connect-node@2.0.0_@bufbuild+protobuf@2.2.2_@connectrpc+connect@2.0.0/node_modules/@connectrpc/connect-node/dist/esm/node-universal-client.js:182:22)
      at emitError (node:events:37:23)
      at emitErrorNT (internal:streams/destroy:88:12)
      at emitErrorCloseNT (internal:streams/destroy:69:14)

error: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
 code: "ERR_HTTP2_STREAM_ERROR"

      at node:http2:1564:45

Bun v1.2.1 (Linux x64)
```

**Comment by anatolebeuzon** [comment]
Can confirm this is still an issue with `bun 1.2.20` (currently the latest).
Easy to reproduce with the `connectrpc` client.

**Comment by adamegyed** [comment]
I'm also running into this issue when trying to use grpc via `connectrpc`, it works on bun `1.2.12` through `1.2.15`, but from `1.2.16` -> `1.2.22` I'm getting a `[internal] Stream closed with error code NGHTTP2_FRAME_SIZE_ERROR` error when trying to invoke a unary gRPC call.

**Comment by jakehobbs** [comment]
Also encountering this issue still in v1.3.5 using `connectrpc`.

**Comment by yuyakinjo** [comment]
Maybe it was fixed in 1.3.6?

https://github.com/oven-sh/bun/issues/25589
