### ISSUE TITLE
panic(main thread): incorrect alignment (Using zeromq)

### ISSUE THREAD

**Issue by Araxeus** [oven-sh/bun#12711]
### How can we reproduce the crash?

import [zeromq](https://www.npmjs.com/package/zeromq) and create any socket
```ts
import zmq from 'zeromq';
const sock = new zmq.Publisher();
```

### Relevant log output

```shell
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2 avx512
Args: "C:\Users\Araxeus\.bun\bin\bun.exe" "zeromq.ts"
Features: jsc dotenv tsconfig(4)
Builtins: "bun:main" "node:fs" "node:os" "node:path" "node:string_decoder" "node:util/types"
Elapsed: 54ms | User: 46ms | Sys: 15ms
RSS: 110.10MB | Peak: 110.10MB | Commit: 0.15GB | Faults: 27101

panic(main thread): incorrect alignment
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [AutoCommand]

**panic**: incorrect alignment

- [`napi.zig:1345`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/napi/napi.zig#L1345>): `napi_get_uv_event_loop`
- ??? at `0xc79f` in node.napi.glibc.node
- ??? at `0xccdc` in node.napi.glibc.node
- [`BunProcess.cpp:393`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/bindings/BunProcess.cpp#L393>): `Bun::Process_functionDlopen`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/dc775f75f03e0ff32458fcd50d868a0f4cee5e86

**Comment by Araxeus** [comment]
@Jarred-Sumner I have just tested the windows build and it did not fix the issue

```
Bun Canary v1.1.21-canary.1 (dc775f75) Windows x64
CPU: sse42 avx avx2 avx512
Args: "C:\Git\test\tidal\bun.exe" "test.ts"
Features: jsc dotenv tsconfig(4)
Builtins: "bun:main" "node:fs" "node:os" "node:path" "node:string_decoder" "node:util/types"
Elapsed: 81ms | User: 15ms | Sys: 46ms
RSS: 112.36MB | Peak: 112.36MB | Commit: 0.15GB | Faults: 27679

panic(main thread): Segmentation fault at address 0xA8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```
