### ISSUE TITLE
Segmentation fault when running zip.js tests

### ISSUE THREAD

**Issue by gildas-lormeau** [oven-sh/bun#14042]
### How can we reproduce the crash?

Run the following commands to reproduce the issue:
1. `git clone --depth 1 https://github.com/gildas-lormeau/zip.js`
2. `cd zip.js`
3. `npm install`
4. `npm run test-bun`

### Relevant log output

```shell
Bun v1.1.28 (cf4e9cb6) macOS Silicon
macOS v15.0
Args: "bun" "test" "bun-runner.test.js"
Features: jsc transpiler_cache(2) tsconfig workers_spawned(13) workers_terminated(13) 
Builtins: "bun:main" 
Elapsed: 404ms | User: 562ms | Sys: 102ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 1.04GB | Faults: 1669

panic(main thread): Segmentation fault at address 0x11D20
```

### Stack Trace (bun.report)

Bun v1.1.28 ([`cf4e9cb`](<https://github.com/oven-sh/bun/tree/cf4e9cb69ee862037b09f2cd6668be76d2aca78d>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x00011D20

- *1 unknown/js code*
- `WebCore::jsWorkerPrototypeFunction_terminate`
- `WebCore::jsWorkerPrototypeFunction_terminate`
- *1 unknown/js code*
- `llint_entry`
- *1 unknown/js code*
- `llint_entry`
- *1 unknown/js code*
- `llint_entry`

**Comment by nektro** [comment]
Fixed by https://github.com/oven-sh/bun/pull/14079. will be available in the next canary/release.
there's still some failing crypto functions in the suite but those are largely being tracked in aggregate by https://github.com/oven-sh/bun/issues/13681

**Comment by gildas-lormeau** [comment]
@nektro I just did a test with the version 1.2 of bun and I can still reproduce the crash, see the logs below. 

```
...
✓ Filesystem export [41.47ms]
============================================================
Bun v1.2.0 (b0c5a765) macOS Silicon
macOS v15.2
Args: "bun" "test" "./bun-runner.js"
Features: jsc tsconfig workers_spawned(13) workers_terminated(13) 
Builtins: "bun:main" 
Elapsed: 435ms | User: 583ms | Sys: 95ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.99GB | Faults: 1730

panic(main thread): Segmentation fault at address 0xFF00000000013D16
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

**Comment by nektro** [comment]
new trace:

```
ASSERTION FAILED: m_normalWorld->hasOneRef()
../../src/bun.js/bindings/BunClientData.cpp(75) : virtual WebCore::JSVMClientData::~JSVMClientData()
1   0x100069b90 WebCore::JSVMClientData::~JSVMClientData()
2   0x10006a070 WebCore::JSVMClientData::~JSVMClientData()
3   0x10006a0bc WebCore::JSVMClientData::~JSVMClientData()
4   0x10631549c JSC::VM::~VM()
5   0x100053bd8 WTF::ThreadSafeRefCountedWithSuppressingSaferCPPChecking<JSC::VM, (WTF::DestructionThread)0>::derefSuppressingSaferCPPChecking() const
6   0x100a1fb78 WebWorker__dispatchExit
7   0x103c52460 src.bun.js.web_worker.WebWorker.exitAndDeinit
8   0x104419e2c src.bun.js.web_worker.WebWorker.spin
9   0x1040a7194 src.bun.js.javascript.OpaqueWrap__anon_221733__struct_231597.callback
10  0x1005ba030 JSC__VM__holdAPILock
11  0x100fd894c src.bun.js.bindings.bindings.VM.holdAPILock
12  0x10369a574 src.bun.js.web_worker.WebWorker.start
13  0x102fc8a24 src.bun.js.web_worker.WebWorker.startWithErrorHandling
14  0x1028f690c Thread.callFn__anon_174648
15  0x1020a6a48 Thread.PosixThreadImpl.spawn__anon_149667.Instance.entryFn
16  0x1973572e4 _pthread_start
17  0x1973520fc thread_start
```

**Comment by gildas-lormeau** [comment]
I cannot reproduce this bug anymore in the version v1.2.3, it looks like it's fixed.

**Comment by gildas-lormeau** [comment]
I spoke too fast. It's still reproducible, see below. To reproduce it, I replaced `{ title: "Crypto (raw password)", script: "./test-crypto-raw-password.js", env: ["deno", "node", "browser"] },` with `{ title: "Crypto (raw password)", script: "./test-crypto-raw-password.js"] },` in https://github.com/gildas-lormeau/zip.js/blob/dff9976220aa177cfeee44859b274e4a673f1eef/tests/tests-data.js#L9. Then, the bug can be reproduced even by reverting the change.

```
============================================================
Bun v1.2.3 (8c4d3ff8) macOS Silicon
macOS v15.3.1
Args: "bun" "test" "./bun-runner.js"
Features: jsc transpiler_cache(2) tsconfig workers_spawned(14) workers_terminated(14) 
Builtins: "bun:main" 
Elapsed: 349ms | User: 585ms | Sys: 55ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 1.04GB | Faults: 74

panic(main thread): Segmentation fault at address 0x4345775351439009
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.3/Mt18c4d3ffmDgggQ_2y4zjB2y4zjB_u5p82C_2nh82C_+l/72C_A2m171ojCygouoxC

sh: line 1: 36932 Trace/BPT trap: 5       bun test ./bun-runner.js
```

**Comment by Jarred-Sumner** [comment]
Tracking this in https://github.com/oven-sh/bun/issues/15964
