### ISSUE TITLE
ConnectionRefused when `fetch()` is localhost

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1425]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64 arm

### What steps can reproduce the bug?

```js
export default {
  port: 4281,
  fetch(request) {
    return new Response("Ok");
  }
}

console.log(await fetch("http://localhost:4281/hello"))
```

### What do you see instead?

The above code fails with the error:
```bash
ConnectionRefused: fetch() failed
 path: "http://localhost:4281/hello"
```

**Comment by Jarred-Sumner** [comment]
I used to hardcode localhost to 127.0.0.1 as a workaround, but it's not great since technically the OS could have rewritten localhost to anything else

@unetworking do you have any ideas?

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v0.7.1

**Comment by rubenfiszel** [comment]
Still have this issue on 0.7.3 for localhost:8000

**Comment by Voldemat** [comment]
On 1.0.0 same error

**Comment by Carter-Apas** [comment]
I have the same error on 1.0.0

**Comment by nourmanhajar** [comment]
Could this be related with my Next.js dev with `bun run --bun next dev`? It says there's something regarding sockets, which could be used by Next for HMR, followed by a ConnectionRefused.

```
dyld[35100]: missing symbol called
ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "http://localhost:51789/"

ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:51789/"
```

**Comment by masnormen** [comment]
Could this be related with my Next.js dev with `bun run --bun next dev`? It says there's something regarding sockets, which could be used by Next for HMR, followed by a ConnectionRefused.

```
dyld[35100]: missing symbol called
ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "http://localhost:51789/"

ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:51789/"
```

**Comment by BobDenar1212** [comment]
I have the same issue with the following:
`wsl2 Ubuntu-22.04 LTS` `bun-1.0.0`
Create nextjs app with :
`bunx create-next-app test --ts --tailwind --eslint --app --src-dir --use-bun --import-alias "@/*"`
Run nextjs app with:
`bun next dev`

Gives the output: 
```
$ bun next dev
- ready started server on localhost:3000, url: http://localhost:3000
- event compiled client and server successfully in 209 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 38 ms (20 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 2.2s (426 modules)
- wait compiling...
- event compiled successfully in 174 ms (235 modules)
ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "http://localhost:43275/"

- wait compiling /_error (client and server)...
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:43275/favicon.ico"
```

EDIT 2023-10-09
I gave a try to latest bun version 1.0.4, and it is working fine

**Comment by markstos** [comment]
Using 127.0.0.1 works as a workaround.

**Comment by paperclover** [comment]
Edit: this is incorrect, the server will begin on the tick after it has started

the code snippet in the issue is technically wrong.

```ts
export default {
  port: 4281,
  fetch(request) {
    return new Response("Ok");
  }
}

console.log(await fetch("http://localhost:4281/hello"))
```

when you use export default to start a server, it will only start after the module is finished evaluating, so you cannot top-level-await a fetch here.

```ts
Bun.serve({
  port: 4281,
  fetch(request) {
    return new Response("Ok");
  },
});

console.log(await fetch("http://localhost:4281"));
```
This works for me on Linux and MacOS. Can someone test this on WSL?

**Comment by markstos** [comment]
I wonder if the issue is that Bun is defaulting to an IPv6 connection for localhost, but there's no entry for `localhost` for IPv6 in `/etc/hosts`.

You could try adding this to `/etc/hosts` if there's not something like it there:

```
::1             localhost
```

**Comment by kszpakowski** [comment]
@markstos I already have /etc/hosts entry for IPv6 localhost and unfortunately it still does not work.

**Comment by nCrafts** [comment]
Having the same issue and can’t really use Bun on any of my projects because of this. Is there something I can do to help debug this?

**Comment by masnormen** [comment]
I think this has been solved with 1.0.4, at least for me. Give it a try

**Comment by nCrafts** [comment]
Unfortunately not for me. It says, `ConnectionRefused: Unable to connect. Is the computer able to access the url?`

**Comment by markstos** [comment]
@nCrafts You can checkout the Bun project and review the related test coverage and then add a new failing test which triggers this failure:

https://github.com/oven-sh/bun/blob/main/test/js/web/fetch/fetch.test.ts

There are already some tests for `fetch()` with localhost, including some with IPv6, so you'll to figure what specifically is triggering this failure.

**Comment by danny-avila** [comment]
In my case, it seems to happen intermittently when the express res object closes `res.on('close', ...)`

**Comment by Schrammel** [comment]
Related issue on `1.0.11`

- on browser it works all time
- on bun it works **sometimes**

```ts

  console.log("fetching projects");
  const request = await fetch("https://git.syonet.com/api/v4/projects", {
    headers: {
      "Private-Token": "< my private token >",
    },
  });
  const projects = await request.json();
  console.table(projects);

```

output:

```bash
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "https://git.syonet.com/api/v4/projects"
```

**Comment by mathiasrw** [comment]
Same problem on mac m1 cpu. 

Took me ages to identify that this line works in Node but not in Bun. 

<img width="715" alt="image" src="https://github.com/oven-sh/bun/assets/1063454/3152bb8c-4d2a-421e-bbe6-06f85ab2f532">
<img width="580" alt="image" src="https://github.com/oven-sh/bun/assets/1063454/231487bd-5cf4-4b72-b99e-a53ec92dc79c">

**Comment by prantlf** [comment]
I can confirm the problem with `bun` 0.1.18. But executing the same `.js` script containing `await fetch('http://localhost'...` with `node` works.

**Comment by alextbok** [comment]
I'm seeing this same issue in `v1.0.23`. Apple M2 (Sonoma macOS).
```
bun --version
1.0.23
```

**Comment by VigilioYonatan** [comment]
any update?

**Comment by jameshfisher** [comment]
Still broken on 1.0.27.

Example of `node` connecting just fine:

```
$ node
Welcome to Node.js v20.10.0.
Type ".help" for more information.
> const response = await fetch("http://localhost:11434/api/chat")
undefined
> await response.text()
'404 page not found'
>
```

`bun repl` equivalent fails with `ConnectionRefused: Unable to connect`:

```
$ bun repl
Welcome to Bun v1.0.27
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> const response = await fetch("http://localhost:11434/api/chat")
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:11434/api/chat"

>
```

```
$ bun --version
1.0.27
```

**Comment by jameshfisher** [comment]
Can confirm replacing `localhost` with `127.0.0.1` works. Although of course this is not a general workaround

**Comment by Iuriiiii** [comment]
Make requests to `http://[::1]:3000/` worked for me.

Notes:
I'm using Windows, Bun is executing on WSL.

**Comment by zartinn** [comment]
Can confirm that I have the same error when trying to accessing a local running nest application with hostname `0.0.0.0`
I have two possibilities here to solve this:

Either remove the hostname in the nest appliction OR use `127.0.0.1` instead of `localhost` when making the fetch from bun

my hosts file has also nothing suspicious in it and it should be able to resolve localhost correctly on my machine

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by VigilioYonatan** [comment]
I found a solution temporarily. 
Install  ngrok https://dashboard.ngrok.com/get-started/setup/windows , login in ngrok and CMD EXECUTE  "ngork.exe http 3000" you will have a host https temporarily

**Comment by kirill-dev-pro** [comment]
same error with arbitrary ip addresses in bun 1.0.29

**Comment by mathiasrw** [comment]
@kirill-dev-pro Example please?

**Comment by prantlf** [comment]
This reminds me about `ECONNREFUSED` errors, which started occurring when Node.js 18 was released. They were caused by a [change in the Node.js implementation](https://github.com/nodejs/node/pull/39987), preferring IPV6 to IPV4 in the address resolution. (Actually, it had happened in Node.js 17 already, but most of the community had waited for LTS versions as usual.) `npm install` started failing. Packages like `puppeteer`, which download a part from other servers than npmjs.org, couldn't be installed. There're many bug reports related to it like [this one](https://github.com/nodejs/node/issues/40537).

An easy way of reproducing the problem was making a server listen at `127.0.0.1:80` or `0.0.0.0:80`, which is very often, and connecting to `[::1]:80`, which failed. The IPV6 address was the new result of the resolution of `http://localhost`.

It took some time to fix the IPV6 configuration on servers and clients. I had to survive with the environment variable `NODE_OPTIONS=--dns-result-order=ipv4first` for quite some time. But a year has passed, `puppeteer` and `storybook` can be installed on both IPV4 and IPV6 networks today and people forgot about the dark period.

You can feel a deajvu by making a mistake deliberately:

```js
export default {
  port: 4281,
  hostname: '127.0.0.1', // 0.0.0.0 is bad too
  fetch(request) {
    return new Response("Ok");
  }
}

console.log(await fetch("http://[::1]:4281/hello"))
```

If you don't specify any value for `hostname`, Bun will do something magical and connections using both IPV4 and IPV6 will succeed:

```js
const server = Bun.serve({
  port: 4281,
  fetch(request) {
    return new Response("Welcome to Bun!");
  }
})

console.log(await fetch("http://127.0.0.1:4281/hello"))
console.log(await fetch("http://[::1]:4281/hello"))
```

As sool as you specify `hostname`, the server will listen to only one IP address type, according to the local configuration of `localhost`. Shouldn't Bun listen [to both IPV4 and IPV6 addresses](https://stackoverflow.com/questions/1618240/how-to-support-both-ipv4-and-ipv6-connections) on dual-stack systems?

**Comment by oSethoum** [comment]
Still having this issue on bun 1.0.30

**Comment by didier** [comment]
Still happening on `1.0.33`.

**Comment by ArthurTimofey** [comment]
Still happening `1.1.0` M1 Pro :(

**Comment by ArthurTimofey** [comment]
Still happening `1.1.0` M1 Pro :(

**Comment by zpix1** [comment]
Same on 1.1.1:

```
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:11434/api/generate"
```

Fixed by replacing localhost with 127.0.0.1

**Comment by iHaiduk** [comment]
Same on 1.1.x:
```
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://logs.eu-central-1.amazonaws.com/"
 ```

**Comment by lukewlms** [comment]
Oh wow.  Connecting to `localhost` is very common, I spent close to an hour trying to debug this and confused about why I could GET a public URL but not localhost.  Seems like this would be a high priority to fix.  `curl` and the browser can connect to localhost, bun should be able to also.  (I'm on latest, v1.1.3)

**Comment by omarpando** [comment]
Still happening.

**Comment by 7heMech** [comment]
Happens on 127.0.0.1 as well

**Comment by ilya-tkachov** [comment]
Used the latest version `1.1.8` on M3 Pro and got this issue but only when trying to use a proxy in nextjs between two apps. Had to downgrade to `1.0.35` and it worked like a charm.

**Comment by 7heMech** [comment]
> Used the latest version `1.1.8` on M3 Pro and got this issue but only when trying to use a proxy in nextjs between two apps. Had to downgrade to `1.0.35` and it worked like a charm.

@Jarred-Sumner maybe you can check this out?

**Comment by schulzf** [comment]
is there a temporary workaround for this?

We've been experiencing this issue on production (under v1.1.8), the server randomly fails to resolve url and throws `Unable to connect. Is the computer able to access the url?`

**Comment by Jarred-Sumner** [comment]
@schulzf if you can use `127.0.0.1` or `0.0.0.0` as the hostname that should workaround this. Or otherwise, if you can disable IPv6. The problem is that `localhost` often resolves to both IPv6 and IPv4, but the server may only be listening on IPv4.

**Comment by schulzf** [comment]
@Jarred-Sumner in our case is a not localhost but a live url (and it doesn't support ipv6).
By disabling ipv6 the server would become ipv4 only for inbound as well, which wouldn't be the best...

Is there a way to disable ipv6 in bun? (we're running under Cloud Run, we can't access the underlying system configuration)

**Comment by mathiasrw** [comment]
I can confirm that this is now working as expected with bun v1.1.9

Nice work @teamBun

<img width="670" alt="image" src="https://github.com/oven-sh/bun/assets/1063454/3aa4c6c1-3e63-4c74-9380-de127d754ea4">

#bunUp

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.9

**Comment by rogercbe** [comment]
I am still having the same problem on **Bun v.1.1.12** using localstack and trying to upload an image to s3 
```
AWS_ENDPOINT=http://localhost:4566
```

Error:
```
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://my-buckett.localhost:4566/3354167639216915979?uploads="
 ```

**Comment by stewones** [comment]
not sure what I'm doing wrong but I can't seem to make bun fetch, neither using 0.0.0.0 or 127.0.0.1. tried everything spoken in this thread so far 🙄

**Comment by stewones** [comment]
holy moly, I figured out my problem. the issue is that I needed to fetch between containers, so nothing worked until I tried `host.docker.internal`, which did the trick. so yeah, I can confirm fetch on Bun 1.1.15 works 🎉

**Comment by garraflavatra** [comment]
Has this been tested with local TLS (Caddy server) as well? I am able to visit this URL using cURL but not with Bun.

```js
> await fetch('https://test.localhost/api/v2/portal/funnels/1/')
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "https://test.localhost/api/v2/portal/funnels/1/"
```

**Comment by garraflavatra** [comment]
TLS turns out not to be the issue... instead, localhost subdomains (`test.localhost`) are not handled correctly.

**Comment by msamia** [comment]
Hello, if for some reason when you try to access a registry file the connection fails, it gives an error of connection refused and not installed. Connection errors will not be recovered. The only way out in this case is to persist. This error is more likely to be detected if the json file that tries to access and fails is different in each attempt, especially if many components are installed at once.

**Comment by MichaelYuhe** [comment]
Still happening at v1.1.21

**Comment by mathiasrw** [comment]
@MichaelYuhe Please fill out a new issue referencing this one and providing information on how to replicate and the versions of bun and OS.

**Comment by lsyuanyuan** [comment]
I cannot determine whether the issue is with the server or with Bun, as I have encountered the same problem when using other URLs. I am using a URL similar to http://oa.xxxx.com, and I am in a production environment.
﻿
Error message: ConnectionRefused: Unable to connect. Is the computer able to access the URL?
Path: "http://oa.xxxx.com/"
﻿
My service information:
﻿
Linux localhost.localdomain 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
﻿
bun -v 1.1.21

**Comment by lsyuanyuan** [comment]
> > I cannot determine whether the issue is with the server or with Bun, as I have encountered the same problem when using other URLs. I am using a URL similar to http://oa.xxxx.com,和I am in a production environment.
> > ﻿
> > Error message: ConnectionRefused: Unable to connect. Is the computer able to access the URL?
> > Path: "http://oa.xxxx.com/"
> > ﻿
> > My service information:
> > ﻿
> > Linux localhost.localdomain 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed 12月22日 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > ﻿
> > bun -v 1.1.21
> 
> If you don't provide the exact url or another url at which this happens we can't help.

I'm sorry, I should have considered that it might be a server issue, because normally there wouldn't be any mistakes. Thank you!

**Comment by Jarred-Sumner** [comment]
If you're continuing to run into an issue like this, please open a new issue one with a complete reproduction
