### ISSUE TITLE
Memory leak when using Prisma

### ISSUE THREAD

**Issue by boomNDS** [oven-sh/bun#14664]
### How can we reproduce the crash?

I’m using Elysia.js to run an API server that handles approximately 30 requests per second. Over time, I observed an increase in CPU usage, which eventually affects the server’s performance. This issue seems to worsen after making several requests, leading to degraded system performance. Restarting the server temporarily resolves the issue, but this is not a viable long-term solution.

```Dockerfile
FROM oven/bun:1.1.29 AS build
WORKDIR /app
ENV HUSKY=0
COPY package.json bun.lockb ./
COPY ./prisma ./prisma
COPY ./src ./src

# Install dependencies
RUN bun install

# Generate Prisma client with the correct schema location
RUN bunx prisma generate --schema prisma/schema.prisma

# Compile the server to a binary
RUN bun build \
  --compile \
  --minify-whitespace \
  --minify-syntax \
  --target bun \
  --outfile server \
  ./src/index.ts


FROM oven/bun:1.1.29-slim AS runner

WORKDIR /app

# Copy the compiled binary and the Prisma schema from the build stage
COPY --from=build /app/server /app/server
COPY --from=build /app/node_modules/.prisma/client /app/node_modules/.prisma/client
COPY --from=build /app/prisma ./prisma

RUN apt-get update && apt-get install -y openssl

COPY start.sh /app/start.sh

ENV NODE_ENV=production

RUN chmod +x /app/start.sh

CMD ["/app/start.sh"]
```

## Shell Script (start.sh)
Here is the start.sh script used to start the server:
```
#!/bin/sh

# Run Prisma migrations
echo "Running Prisma migrations..."
bunx prisma migrate deploy --schema prisma/schema.prisma

# Check if the migrations succeeded
if [ $? -eq 0 ]; then
    echo "Migrations completed successfully!"
    
    # Start the server
    echo "Starting the server..."
    ./server
else
    echo "Migrations failed. Server will not start."
    exit 1
fi
```

### Stack Trace (bun.report)

```
{
  objectTypeCounts: {
    string: 37367,
    Object: 36919,
    Function: 31116,
    JSLexicalEnvironment: 20342,
    Structure: 12721,
    FunctionExecutable: 11238,
    UnlinkedFunctionExecutable: 9653,
    Promise: 9313,
    Generator: 4865,
    Array: 3660,
    SymbolTable: 2620,
    GetterSetter: 2335,
    FunctionCodeBlock: 2329,
    UnlinkedFunctionCodeBlock: 1942,
    StructureRareData: 1633,
    Date: 1546,
    InternalPromise: 1327,
    "Immutable Butterfly": 1215,
    Headers: 1032,
    Response: 1030,
    Error: 1017,
    NativeExecutable: 949,
    AsyncFunction: 730,
    ProxyObject: 532,
    Request: 516,
    Map: 466,
    StructureChain: 451,
    JSModuleEnvironment: 444,
    JSSourceCode: 444,
    ModuleRecord: 444,
    ModuleProgramCodeBlock: 410,
    ModuleProgramExecutable: 410,
    UnlinkedModuleProgramCodeBlock: 406,
    PropertyTable: 405,
    FunctionRareData: 376,
    RegExp: 358,
    Exception: 357,
    BigInt: 266,
    Module: 224,
    UnlinkedProgramCodeBlock: 200,
    symbol: 189,
    ProgramCodeBlock: 175,
    ProgramExecutable: 175,
    DOMAttributeGetterSetter: 82,
    CustomGetterSetter: 75,
    DOMException: 75,
    GeneratorFunction: 70,
    SparseArrayValueMap: 69,
    JSPropertyNameEnumerator: 66,
    Uint8Array: 57,
    ModuleNamespaceObject: 35,
    Set: 17,
    Arguments: 13,
    ArrayBuffer: 7,
    WeakMap: 6,
    BufferList: 4,
    TextEncoder: 4,
    FileInternalReadableStreamSource: 3,
    ReadableStream: 3,
    StringDecoder: 3,
    URL: 3,
    Uint16Array: 3,
    AbortController: 2,
    AbortSignal: 2,
    AsyncGeneratorFunction: 2,
    Blob: 2,
    Callee: 2,
    Crypto: 2,
    DataView: 2,
    DebugHTTPServer: 2,
    EventTarget: 2,
    Int32Array: 2,
    JSAsyncGeneratorFunction: 2,
    NodeJSFS: 2,
    Performance: 2,
    SubtleCrypto: 2,
    TCPSocket: 2,
    TextDecoder: 2,
    URLSearchParams: 2,
    Uint32Array: 2,
    WeakRef: 2,
    WeakSet: 2,
    "Array Iterator": 1,
    AsyncFromSyncIterator: 1,
    AsyncGenerator: 1,
    AsyncIterator: 1,
    BigInt64ArrayPrototype: 1,
    BigUint64ArrayPrototype: 1,
    Boolean: 1,
    Buffer: 1,
    Bun: 1,
    CryptoHasher: 1,
    Dirent: 1,
    ErrorCodeCache: 1,
    EvalCodeBlock: 1,
    EvalExecutable: 1,
    EventEmitter: 1,
    File: 1,
    FinalizationRegistry: 1,
    Float16ArrayPrototype: 1,
    Float32ArrayPrototype: 1,
    Float32Array: 1,
    Float64ArrayPrototype: 1,
    Float64Array: 1,
    "FormData Iterator": 1,
    FormData: 1,
    GlobalObject: 1,
    Int16ArrayPrototype: 1,
    Int16Array: 1,
    Int32ArrayPrototype: 1,
    Int8ArrayPrototype: 1,
    InternalFieldTuple: 1,
    InternalModuleRegistry: 1,
    InternalPromisePrototype: 1,
    "Intl.DateTimeFormat": 1,
    "Intl.DurationFormat": 1,
    "Intl.ListFormat": 1,
    Intl: 1,
    Iterator: 1,
    JSGlobalLexicalEnvironment: 1,
    JSGlobalProxy: 1,
    JSON: 1,
    "Map Iterator": 1,
    Math: 1,
    ModuleLoader: 1,
    ModulePrototype: 1,
    NextTickQueue: 1,
    Number: 1,
    ProcessBindingConstants: 1,
    Process: 1,
    Prototype: 1,
    Proxy: 1,
    Reflect: 1,
    "RegExp String Iterator": 1,
    "Set Iterator": 1,
    ShadowRealm: 1,
    Stats: 1,
    "String Iterator": 1,
    String: 1,
    Symbol: 1,
    TextEncoderStreamEncoder: 1,
    Uint16ArrayPrototype: 1,
    Uint32ArrayPrototype: 1,
    Uint8ArrayPrototype: 1,
    Uint8ClampedArrayPrototype: 1,
    UnlinkedEvalCodeBlock: 1,
    WebAssembly: 1,
    console: 1,
    require: 1,
    resolve: 1,
  },
  protectedObjectTypeCounts: {
    UnlinkedModuleProgramCodeBlock: 406,
    UnlinkedProgramCodeBlock: 200,
    Function: 33,
    UnlinkedFunctionExecutable: 4,
    AsyncFunction: 1,
    DebugHTTPServer: 1,
    GlobalObject: 1,
  },
  heapSize: 24838266,
  heapCapacity: 31881642,
  extraMemorySize: 10792874,
  objectCount: 220692,
  protectedObjectCount: 646,
  globalObjectCount: 1,
  protectedGlobalObjectCount: 1,
}
```

**Comment by boomNDS** [comment]
I removed the other router and disabled the app services. Then I inserted the data into the database and added a message, but RAM usage is still high for me too. Do you have any idea why CPU usage hits 90% during high-demand periods?

**Comment by JayFreemandev** [comment]
same situation. it's bad bad bad one.

**Comment by boomNDS** [comment]
this my [minimap reproduction ](https://replit.com/@boomsixboom/Elysia-call-3th-party-api) use bun 1.1.29 and elysia 1.1.23


loadtest with [oha](https://github.com/hatoo/oha)
```bash
oha http://localhost:5002/api/some\
-H "Authorization: Bearer <token>" \
-H "Content-Type: application/json" \
-m POST \
-d '{"data": "0000"}' \
-n 10000 \
-q 20 \
--disable-keepalive \
--latency-correction
```

**Comment by withadne** [comment]
In my case, the problem occurred with Prisma. When PrismaClient is continuously used, memory usage keeps increasing and is never released until it remains unused for more than 3 minutes (until there are no API requests for over 3 minutes). This memory leak issue did not occur with Node.js or other ORMs.

**Comment by Jonatthu** [comment]
@withadne This could be it! Prisma is also something I am using

**Comment by boomNDS** [comment]
@withadne  Interesting! I also use Prisma, and my API gets about 15 requests all the time.

**Comment by ricardojmendez** [comment]
I'm running into a similar situation with Elysia and Prisma - total memory use grows constantly if I leave the processes running, until I close iTerm.

My case is a bit more involved: two bun processes, one of them sending HTTP requests to the other, which is the one that involved Elysia and Prisma.  It's fielding easily between 30-50 requests per second and, after running for a couple of days, I can see it consuming ~120GBs of RAM.

Happy to provide the projects, even if they aren't a microrepro yet.

**Comment by boomNDS** [comment]
After reducing Prisma connections per request, performance seems improved. However, yesterday, CPU usage remained above 100% for an extended period until the app was restarted due to unresponsive queries.

**Comment by ricardojmendez** [comment]
This is not a minimal repro, but it consistently shows the issue after a while of running, and considering that it seems to manifest because of a ton of requests it is a good way to reproduce it.

You'll need these two projects:

1. https://github.com/ricardojmendez/morat-reference
2. https://github.com/ricardojmendez/morat-atproto

The first one is the one doing all the request handling with Elysia and storing the data on Postgres through Prisma, the second does ingestion of BlueSky events.

Run them side by side on separate terminals for a while - a couple of hours should make it obvious. You will see the terminal's memory use continually increase.

![Image](https://github.com/user-attachments/assets/3f4f4aea-efb4-4825-905b-dabe4579e653)

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15309

This will be part of the Bun v1.1.36 release, which is tomorrow.

**Comment by ricardojmendez** [comment]
@Jarred-Sumner I am still seeing this behavior on 1.1.37 on the example pair I provided above.

![Image](https://github.com/user-attachments/assets/97adff83-2801-42be-b17a-8698cc293c6b)

Do you want me to reopen this issue or create a new one with it?

**Comment by Jarred-Sumner** [comment]
@ricardojmendez am very confident the original issue here is fixed, as we have a test for it

Can you open a new issue with a reproduction for us to take a look at?

**Comment by boomNDS** [comment]
> Fixed in [#15309](https://github.com/oven-sh/bun/pull/15309)
> 
> This will be part of the Bun v1.1.36 release, which is tomorrow.

Thank you for addressing the issue, I'll test it again
