### ISSUE TITLE
--hot mode caused double echo in console

### ISSUE THREAD

**Issue by branaway** [oven-sh/bun#15027]
### What version of Bun is running?

1.1

### What platform is your computer?

Mac

### What steps can reproduce the bug?

```js
import readline from "readline/promises";

const stdio = readline.createInterface({ input: process.stdin, output: process.stdout });
while (true) {
   const userInput = await stdio.question("> ");
}
```

Running in --hot mode and having reloaded once, the user input in the console would double echoed.  Happened only after a hot reload has occurred. 

### What is the expected behavior?

it should echo once 

### What do you see instead?

instead of `> this is my input`
got: `> tthhiiss  iiss  mmyy  iinnppuutt`

**Comment by RiskyMH** [comment]
Fixed in [`v1.1.37`](https://bun.sh/blog/bun-v1.1.37#fixed-errors-printing-twice-in-watch-or-hot-mode)!

**Comment by branaway** [comment]
Still not working. 

`import * as readline from 'readline';

(async function main() {
    const stdio = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    let userInput = '';

    console.log("Welcome to the Echo!");

    while (true) {
        userInput = await new Promise<string>((resolve) =>
            stdio.question(`:: > `, resolve)
        );

        if (userInput.toLowerCase() === 'exit') {
            console.log('Goodbye!');
            stdio.close();
            break;
        }

        console.log(`You typed: "${userInput}"`);
    }
})();
`

run it with `bun --hot demo.ts`

after a reloading caused by a file save, I started to see something like:

`Welcome to the Echo!
:: > hhhheeeelllllllloooo



You typed: "hello"
:: > You typed: "hello"
:: > You typed: "hello"
:: > You typed: "hello"
:: > 
`

**Comment by RiskyMH** [comment]
Ah ok it was reproducible on windows and was fixed then so i assumed, i will reopen now though.
