### ISSUE TITLE
Bun fails to terminate running query with `postgres`

### ISSUE THREAD

**Issue by alexblack** [oven-sh/bun#15443]
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Create a file db.ts with contents:

```
import postgres from 'postgres'

const url = 'postgres-connection-string';

const sql = postgres(url, { ssl: { sslMode: 'required', rejectUnauthorized: false } });

const res = await sql`SELECT * FROM some-table LIMIT 1`;
console.log(JSON.stringify(res, null, 2));

console.log('done');
await sql.end();
```

From the command line execute

`bun db.ts`

### What is the expected behavior?

The program should run, display the results and then terminate.

### What do you see instead?

It displays the results, then `done`, then hangs, failing to terminate.

If I press CTRL-C then it terminates.

### Additional information

My package.json

```
{
  "name": "test",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "postgres": "^3.4.5"
  }
}
```

**Comment by alexblack** [comment]
Interesting - I changed my SQL query a bit, to return fewer columns, and now `bun db.ts` does terminate, so perhaps the issue is more subtle than I realized?

**Comment by RiskyMH** [comment]
Duplicate of #15438

**Comment by Jarred-Sumner** [comment]
@alexblack thanks for the reproduction, am able to reproduce it

we will fix it

**Comment by alexblack** [comment]
> [@alexblack](https://github.com/alexblack) thanks for the reproduction, am able to reproduce it
> 
> we will fix it

Awesome.

**Comment by alexblack** [comment]
Intermittently I also see it hang forever on queries, not sure if that is bun related or not.

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15452

**Comment by alexblack** [comment]
I might be misunderstanding, but I upgraded to bun 1.1.38 and the issue still reproduces for me with those steps above

**Comment by Jarred-Sumner** [comment]
@alexblack there was a crash that could occur when TCP fin was received after an unsuccessful TCP -> TLS upgrade and that crash is fixed. I was able to locally verify that Postgres.js no longer crashed and instead threw an exception (as expected) in the specific scenario I was able to reproduce

That being said, we're now seeing a reports of a different but similar bug where Postgres gets into an infinite retry loop when the TLS certificate it receives is invalid. @cirospaciari is actively working on fixing that.

**Comment by alexblack** [comment]
thanks @Jarred-Sumner.  Just to be clear - when I execute the steps (above) it connects no problem and runs the query and displays the output, but the process doesn't terminate.

Are you saying that somewhere in there there is an invalid certificate causing an infinite loop that doesn't prevent my query running, but does prevent the process from terminating
