### ISSUE TITLE
Bun stalls when reading from console. Is it a performance bug?

### ISSUE THREAD

**Issue by kkdd** [oven-sh/bun#15520]
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Darwin 23.6.0 x86_64 i386

### What steps can reproduce the bug?

Bun stalls when reading from ```console```, appearing in the following benchmark in the case of n= 200000, by using ```hyperfine```.

```py
$ for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | bun run stream.js'; done

Benchmark 1: ./cycle_graph.sh 200000 | bun run stream.js
  Time (mean ± σ):     13.774 s ±  0.265 s    [User: 14.409 s, System: 1.124 s]
  Range (min … max):   13.484 s … 14.262 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | bun run stream.js
  Time (mean ± σ):      2.609 s ±  0.081 s    [User: 2.573 s, System: 0.636 s]
  Range (min … max):    2.505 s …  2.753 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | bun run stream.js
  Time (mean ± σ):      1.221 s ±  0.045 s    [User: 1.287 s, System: 0.303 s]
  Range (min … max):    1.192 s …  1.347 s    10 runs
```

```sh
$ cat cycle_graph.sh
#!/bin/sh

n=$1  # positive integer
case "$n" in '' | *[!0-9]* ) n=10; esac  # default value

i=0; edge_length=1
while [ $i -lt "$n" ]; do
  i_next=$((i+1))
  echo "$i,$((i_next%n)),$edge_length"
  i=$i_next
done
```

```ts
$ cat stream.js
const graph = {
  n: 0, // the order of graph, the number of vertices
  edges: []  // see addEdgeToGraph() below
}
await loadFromStdin(addEdgeToGraph);
console.log(`graph.n: ${graph.n}`);

function addEdgeToGraph(line) {
  const [from, to, length] = line.split(',').map(e => parseInt(e));
  const n = (from > to ? from : to) + 1;
  if (n > graph.n) {graph.n = n; graph.edges.length = n;}
  if (!graph.edges[to]) graph.edges[to] = [];
  if (!graph.edges[from]) graph.edges[from] = [];
  graph.edges[from].push([to, length]);
}

async function loadFromStdin(funcOfLine) {
  const userAgent = navigator.userAgent;
  switch(true) {
    case userAgent.startsWith('Bun'):
      for await (const line of console) {
        funcOfLine(line);
      }
      break;
    case userAgent.startsWith('Deno'):
      const streams = await import("jsr:@std/streams")
      const lineStream = Deno.stdin.readable.pipeThrough(new TextDecoderStream()).pipeThrough(new streams.TextLineStream());
      for await (const line of lineStream) {
        funcOfLine(line);
      }
      break;
    case userAgent.startsWith('Node'):
      const fs = await import("node:fs");
      const readline = await import("node:readline");
      const stream = fs.createReadStream('/dev/stdin', {encoding: 'utf8'});
      const rl = readline.createInterface({input: stream});
      for await (const line of rl) {
        funcOfLine(line);
      }
      break;
  }
}
```

### What is the expected behavior?

I expect that Time ~ 5 s in the case of n= 200000, behaving with a linear dependence.

**Comment by kkdd** [comment]
Is this issue planned to be solved?

**Comment by RiskyMH** [comment]
Yay I think this is fixed!

```ts
# for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | bun run stream.js'; done
Benchmark 1: ./cycle_graph.sh 200000 | bun run stream.js
  Time (mean ± σ):      10.9 ms ±   0.7 ms    [User: 5.4 ms, System: 7.4 ms]
  Range (min … max):     9.2 ms …  13.1 ms    258 runs

Benchmark 1: ./cycle_graph.sh 100000 | bun run stream.js
  Time (mean ± σ):      11.0 ms ±   0.7 ms    [User: 6.0 ms, System: 7.1 ms]
  Range (min … max):     9.0 ms …  12.9 ms    274 runs

Benchmark 1: ./cycle_graph.sh 50000 | bun run stream.js
  Time (mean ± σ):      11.1 ms ±   0.6 ms    [User: 5.1 ms, System: 7.9 ms]
  Range (min … max):     8.9 ms …  12.6 ms    261 runs


# for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | node  stream.js'; done
Benchmark 1: ./cycle_graph.sh 200000 | node  stream.js
  Time (mean ± σ):      16.8 ms ±   1.2 ms    [User: 10.9 ms, System: 6.8 ms]
  Range (min … max):    15.0 ms …  20.8 ms    181 runs

Benchmark 1: ./cycle_graph.sh 100000 | node  stream.js
  Time (mean ± σ):      16.9 ms ±   1.4 ms    [User: 10.9 ms, System: 6.7 ms]
  Range (min … max):    15.1 ms …  22.8 ms    156 runs

Benchmark 1: ./cycle_graph.sh 50000 | node  stream.js
  Time (mean ± σ):      16.6 ms ±   1.2 ms    [User: 10.3 ms, System: 7.2 ms]
  Range (min … max):    15.0 ms …  22.0 ms    185 runs
```

**Comment by kkdd** [comment]
Thank you.
But, the performance of ```./cycle_graph.sh 200000 | bun stream.js``` still doesn't seem to be linear on the platform of Darwin 24.3.0 arm64, as follows:

```console
$ for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | bun stream.js'; done
Benchmark 1: ./cycle_graph.sh 200000 | bun stream.js
  Time (mean ± σ):      2.465 s ±  0.021 s    [User: 2.684 s, System: 0.363 s]
  Range (min … max):    2.429 s …  2.492 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | bun stream.js
  Time (mean ± σ):     609.0 ms ±   6.7 ms    [User: 631.2 ms, System: 223.4 ms]
  Range (min … max):   598.7 ms … 618.0 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | bun stream.js
  Time (mean ± σ):     307.9 ms ±   4.4 ms    [User: 341.7 ms, System: 114.8 ms]
  Range (min … max):   302.9 ms … 315.9 ms    10 runs
 
$ for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | deno stream.js'; done
Benchmark 1: ./cycle_graph.sh 200000 | deno stream.js
  Time (mean ± σ):      1.299 s ±  0.013 s    [User: 2.149 s, System: 0.698 s]
  Range (min … max):    1.278 s …  1.323 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | deno stream.js
  Time (mean ± σ):     644.4 ms ±   8.5 ms    [User: 1126.7 ms, System: 339.6 ms]
  Range (min … max):   630.0 ms … 656.8 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | deno stream.js
  Time (mean ± σ):     319.4 ms ±   1.9 ms    [User: 600.0 ms, System: 165.5 ms]
  Range (min … max):   315.5 ms … 322.4 ms    10 runs
 
$ for n in 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | node stream.js'; done
Benchmark 1: ./cycle_graph.sh 200000 | node stream.js
  Time (mean ± σ):      1.341 s ±  0.017 s    [User: 2.067 s, System: 0.957 s]
  Range (min … max):    1.309 s …  1.368 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | node stream.js
  Time (mean ± σ):     666.7 ms ±  10.7 ms    [User: 1137.8 ms, System: 457.8 ms]
  Range (min … max):   652.8 ms … 686.7 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | node stream.js
  Time (mean ± σ):     332.2 ms ±   2.3 ms    [User: 603.3 ms, System: 215.6 ms]
  Range (min … max):   328.7 ms … 335.5 ms    10 runs
 
$ bun -v
1.2.2
$ node -v
v23.7.0
$ deno -v
deno 2.1.9
```

**Comment by kkdd** [comment]
The following is obtained by using ```x86_64 GNU/Linux``` additionally.

```console
$ for n in 400000 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | bun stream.js'; done
Benchmark 1: ./cycle_graph.sh 400000 | bun stream.js
  Time (mean ± σ):     16.518 s ±  0.084 s    [User: 16.287 s, System: 0.717 s]
  Range (min … max):   16.362 s … 16.617 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 200000 | bun stream.js
  Time (mean ± σ):      3.679 s ±  0.022 s    [User: 3.537 s, System: 0.412 s]
  Range (min … max):    3.642 s …  3.702 s    10 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | bun stream.js
  Time (mean ± σ):     351.3 ms ±  29.2 ms    [User: 302.7 ms, System: 195.4 ms]
  Range (min … max):   307.1 ms … 385.6 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | bun stream.js
  Time (mean ± σ):     187.3 ms ±   7.3 ms    [User: 165.7 ms, System: 117.2 ms]
  Range (min … max):   176.2 ms … 204.4 ms    16 runs
  
$ for n in 400000 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | deno stream.js'; done
Benchmark 1: ./cycle_graph.sh 400000 | deno stream.js
  Time (mean ± σ):     519.9 ms ±   9.8 ms    [User: 1098.3 ms, System: 216.7 ms]
  Range (min … max):   512.2 ms … 544.2 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 200000 | deno stream.js
  Time (mean ± σ):     268.9 ms ±  15.3 ms    [User: 541.7 ms, System: 112.7 ms]
  Range (min … max):   262.6 ms … 314.9 ms    11 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | deno stream.js
  Time (mean ± σ):     141.8 ms ±   2.1 ms    [User: 302.1 ms, System: 59.0 ms]
  Range (min … max):   138.6 ms … 146.6 ms    21 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | deno stream.js
  Time (mean ± σ):      80.0 ms ±   1.1 ms    [User: 162.4 ms, System: 35.2 ms]
  Range (min … max):    78.3 ms …  83.8 ms    36 runs
  
$ for n in 400000 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' | node stream.js'; done
Benchmark 1: ./cycle_graph.sh 400000 | node stream.js
  Time (mean ± σ):     497.2 ms ±   7.6 ms    [User: 955.2 ms, System: 256.2 ms]
  Range (min … max):   492.7 ms … 518.2 ms    10 runs

Benchmark 1: ./cycle_graph.sh 200000 | node stream.js
  Time (mean ± σ):     255.0 ms ±   3.5 ms    [User: 479.0 ms, System: 125.4 ms]
  Range (min … max):   252.0 ms … 261.2 ms    11 runs
 
Benchmark 1: ./cycle_graph.sh 100000 | node stream.js
  Time (mean ± σ):     133.9 ms ±   1.3 ms    [User: 257.1 ms, System: 54.6 ms]
  Range (min … max):   132.1 ms … 137.8 ms    22 runs
 
Benchmark 1: ./cycle_graph.sh 50000 | node stream.js
  Time (mean ± σ):      74.5 ms ±   2.6 ms    [User: 137.9 ms, System: 26.9 ms]
  Range (min … max):    72.8 ms …  88.8 ms    40 runs

$ for n in 400000 200000 100000 50000; do hyperfine --warmup 1 './cycle_graph.sh '$n' >/dev/null'; done
Benchmark 1: ./cycle_graph.sh 400000 >/dev/null
  Time (mean ± σ):     447.6 ms ±   2.0 ms    [User: 432.8 ms, System: 13.1 ms]
  Range (min … max):   444.5 ms … 451.2 ms    10 runs
 
Benchmark 1: ./cycle_graph.sh 200000 >/dev/null
  Time (mean ± σ):     225.2 ms ±   2.7 ms    [User: 210.4 ms, System: 13.6 ms]
  Range (min … max):   223.3 ms … 233.7 ms    13 runs
 
Benchmark 1: ./cycle_graph.sh 100000 >/dev/null
  Time (mean ± σ):     113.3 ms ±   1.0 ms    [User: 106.1 ms, System: 4.2 ms]
  Range (min … max):   112.0 ms … 115.8 ms    26 runs
 
Benchmark 1: ./cycle_graph.sh 50000 >/dev/null
  Time (mean ± σ):      57.7 ms ±   1.0 ms    [User: 52.0 ms, System: 2.2 ms]
  Range (min … max):    56.3 ms …  62.5 ms    50 runs

$ bun -v
1.2.2 
$ node -v
v23.7.0 
$ deno -v
deno 2.1.9
```

**Comment by kkdd** [comment]
Improve ```cycle_graph.sh``` to avoid its slowness, as follows:

```console
$ cat cycle_graph.sh
#!/bin/sh

n=$1  # positive integer
case "$n" in '' | *[!0-9]* ) n=10; esac  # default value

seq $n | awk -v n=$n -v e=$edge_length '{printf("%d,%d,%d\n",$1-1,$1%n,e)}'
```

**Comment by kkdd** [comment]
Is there any progress?
Or should this be set in the milestone?

**Comment by kkdd** [comment]
I realized that this problem is the anti-pattern of Bun when increasing `array.length > 200000`. It can be avoided by iterating `array.push(undefined)`.
