### ISSUE TITLE
ERR_POSTGRES_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Nabwin** [oven-sh/bun#16691]
### What version of Bun is running?

1.2.0

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```ts

import { SQL } from "bun";

export const db = new SQL({
  url: "postgres://postgres:nabin@localhost:5433/refresher",

  max: 20, // Maximum connections in pool
  idleTimeout: 30, // Close idle connections after 30s

  onconnect: (client) => {
    console.log("Connected to database");
  },
  onclose: (client) => {
    console.log("Connection closed");
  },
});

```

```ts
import { sql } from "bun";
import { db } from "./db";

db.connect()
  .then(() => {
    console.log("Connected to database");
  })
  .catch((err) => {
    console.log("Error connecting to database", err);
  });

const users = await sql`
  SELECT * FROM users
  LIMIT ${10}
`;

console.log("active Users:", users);

```
```
➜  bun-1.2 bun run index.ts
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Connection closed
Error connecting to database PostgresError: Connection closed
 code: "ERR_POSTGRES_CONNECTION_CLOSED"


PostgresError: Connection closed
 code: "ERR_POSTGRES_CONNECTION_CLOSED"
```
i have my postgres container running in port 5433 

## While using the pg package it work success fully

database.ts
```ts

import { Client } from "pg";

const connectionString =
  "postgres://postgres:postgres@localhost:5433/refresher";

const client = new Client({
  connectionString: connectionString,
});

client
  .connect()
  .then(() => console.log("Connected to database"))
  .catch((err: unknown) => console.error("Error connecting to database", err));

export { client };

```

index.ts

```ts
import { sql } from "bun";
import { db } from "./db";
import { client } from "./database";

// db.connect()
//   .then(() => {
//     console.log("Connected to database");
//   })
//   .catch((err) => {
//     console.log("Error connecting to database", err);
//   });

// const users = await sql`
//   SELECT * FROM users
//   LIMIT ${10}
// `;

client.query("SELECT * FROM users LIMIT 10", (err, res) => {
  if (err) {
    console.error("Error executing query", err);
    return;
  }

  console.log("active Users:", res.rows);
});
// console.log("active Users:", users);

```
Result of pg packages
```ts

active Users: [
  {
    id: 1,
    name: "Nabin",
  }, {
    id: 2,
    name: "Ram",
  }
]
```

### What do you see instead?

![Image](https://github.com/user-attachments/assets/c1ad5200-5dd9-42e2-ae61-23d37a716806)

**Comment by raventos** [comment]
I am experiencing the same issue; it connects successfully but it stops after a couple of minutes with the same error, and it won't work until restarting.

**Comment by cirospaciari** [comment]
Fixed in https://github.com/oven-sh/bun/pull/16854

**Comment by raventos** [comment]
I know this is closed but I am still getting this error (although much less frequently since Ciros' changes).

**Comment by raventos** [comment]
I installed the canary version this morning and it was fine most of the day, but now after a couple of hours of inactivity, I got the same error again: PostgresError: Connection closed; code: "ERR_POSTGRES_CONNECTION_CLOSED". I noticed this time it managed to restart itself after a while but there was some downtime so in the end I had to revert back to the pg driver.

**Comment by cirospaciari** [comment]
> I installed the canary version this morning and it was fine most of the day, but now after a couple of hours of inactivity, I got the same error again: PostgresError: Connection closed; code: "ERR_POSTGRES_CONNECTION_CLOSED". I noticed this time it managed to restart itself after a while but there was some downtime so in the end I had to revert back to the pg driver.

Will run a longer test today, and see what I can do to make sure we always have uptime, sorry that you having this problems, thanks for the reports

**Comment by ashfaqnisar** [comment]
Can we reopen this issue as it still exists.

**Comment by RWOverdijk** [comment]
Same here, using a db service (tembo in my case). It worked before I updated to 1.2.5.

**Comment by Scooter1337** [comment]
Encountering this right now in 1.2.8. Any temporary solutions? Downgrading to 1.2.4?

**Comment by rizrmd** [comment]
This still happen with latest 1.2.10

**Comment by Scooter1337** [comment]
@cirospaciari this bug makes Bun SQL for postgres currently unusable. I get this error after every ~10 minutes of inactivity, and the first 3-4 requests then return 500, after which it starts working again.

**Comment by delasource** [comment]
Started a new project, with bun, elysia and drizzle. Very simple rest-like api. After some time (6h to 12h) the api does no longer answer correctly. adding logging i see the "ERR_POSTGRES_CONNECTION_CLOSED" error. The db server is a docker container on the same server.

**Comment by pleclech** [comment]
Same using v1.2.18-canary.40 (4cf31f6a) with a postgres 17 database, it makes the postgres sql bun useless for now :(
the error appear immediately not seeing any log saying it's connecting. Using psql on the same machine work fine.

**Comment by SpeedySH** [comment]
same here

**Comment by vastamaki** [comment]
Just encountered this error on Bun v1.2.18 using local postgres container with minimal connection settings in my application. Has anyone found any workarounds?

**Comment by luanhenzo** [comment]
Same here.

**Comment by BlackHole1** [comment]
The issue persists in v1.3.4-canary.62 (2ab6efee). However, it might be different from before.

During unit testing, there is about a 50% chance of triggering the ERR_POSTGRES_CONNECTION_CLOSED error. Sometimes it succeeds, sometimes it fails 3, sometimes it fails 9; the number of failures is uncertain, staying between 3 and 9.

<img width="2646" height="3360" alt="Image" src="https://github.com/user-attachments/assets/9bc72b04-bc9b-4d4b-9ef1-14d3d0901b9f" />

Error Message:
```
src/prices/schema.test.ts:
160 |   let delimiter = type === "BOX" ? ";" : ",";
161 |   return `{${values.map(arrayValueSerializer.bind(this, type, isPostgresNumericType(type), isPostgresJsonType(type))).join(delimiter)}}`;
162 | }
163 | function wrapPostgresError(error) {
164 |   if (Error.isError(error))
165 |   return new PostgresError(error.message, error);
               ^
PostgresError: Connection closed
 code: "ERR_POSTGRES_CONNECTION_CLOSED"

      at wrapPostgresError (internal:sql/postgres:165:10)
      at #onClose (internal:sql/postgres:341:30)
✗ createPriceSchema.body > name field > should accept valid name: shortest (2 chars) [13.08ms]
160 |   let delimiter = type === "BOX" ? ";" : ",";
161 |   return `{${values.map(arrayValueSerializer.bind(this, type, isPostgresNumericType(type), isPostgresJsonType(type))).join(delimiter)}}`;
162 | }
163 | function wrapPostgresError(error) {
164 |   if (Error.isError(error))
165 |   return new PostgresError(error.message, error);
               ^
PostgresError: Connection closed
 code: "ERR_POSTGRES_CONNECTION_CLOSED"

      at wrapPostgresError (internal:sql/postgres:165:10)
      at #onClose (internal:sql/postgres:341:30)
✗ createPriceSchema.body > name field > should accept valid name: numbers and underscores [9.76ms]
160 |   let delimiter = type === "BOX" ? ";" : ",";
161 |   return `{${values.map(arrayValueSerializer.bind(this, type, isPostgresNumericType(type), isPostgresJsonType(type))).join(delimiter)}}`;
162 | }
163 | function wrapPostgresError(error) {
164 |   if (Error.isError(error))
165 |   return new PostgresError(error.message, error);
               ^
PostgresError: Connection closed
 code: "ERR_POSTGRES_CONNECTION_CLOSED"
```

However, in `src/prices/schema.test.ts` and `src/prices/schema.ts`, there is no SQL-related code at all; they only contain Zod schemas.

Strangely:

1. Why does the error ERR_POSTGRES_CONNECTION_CLOSED appear in completely unrelated files,
2. Why is `Connected to PostgreSQL` not printed before src/prices/schema.test.ts

**Comment by PierBover** [comment]
Thanks @alii

I guess this will only be fixed in the Rust version?
