### ISSUE TITLE
Bun css transpiler formats the output wrongly when using @apply utility from tailwindcss

### ISSUE THREAD

**Issue by AlbertSabate** [oven-sh/bun#16712]
### What version of Bun is running?

1.2.0

### What platform is your computer?

Darwin 24.2.0 x86_64 i386

### What steps can reproduce the bug?

Import a css where you are using @apply utility from tailwind will reformat the classname wrongly: .something/80 or button[type="submit"] other-class.

Tailwind v4 example:
https://tailwindcss.com/docs/background-color#changing-the-opacity
https://tailwindcss.com/docs/functions-and-directives#apply-directive

### What is the expected behavior?

leave the classname as it is @apply something/80 not adding spaces or removing them.

### What do you see instead?

Transpiler of Bun will convert the classnames to @apply something / 80 making a syntax error.

**Comment by zackradisic** [comment]
Could you please provide a minimal reproduction? Is this happening with `bun-plugin-tailwind`?

**Comment by WaveringAna** [comment]
im running into an issue where the parser doesnt run. 
documented here: https://www.youtube.com/watch?v=Y5JrsqBt7sI by theo too

it is happening with `bun-plugin-tailwind`

**Comment by AlbertSabate** [comment]
@WaveringAna that's correct, it is in the minute 17. I couldn't make it to work with the plugin. Also, I'm unclear in how to add a custom theme for example.

I also tried using postcss directly by importing the css file on my tsx file.
In 1.1.45 the import copied the css file and I was reading that file and applying:
```typescript
import tailwindcss from '@tailwindcss/postcss';
import postcss from 'postcss';
async transpileCSS(pathname: string, content: string) {
      const transpiledContent = await postcss([tailwindcss]).process(content, {
        from: pathname,
      });

      return transpiledContent.css;
    }
```
In the version 1.2 if i do the import in the tsx file, bun will reformat the code, losing or adding spaces and breaking tailwindcss postcss to be able to parse the wrongly formatted css file.

I'll try to make a minimal reproduction shortly, if that helps.

**Comment by AlbertSabate** [comment]
Reproduction here: https://github.com/AlbertSabate/small-reproduction

**Comment by zackradisic** [comment]
This should be fixed now, please update to `bun-plugin-tailwind@0.0.14`.

**Comment by WaveringAna** [comment]
https://github.com/WaveringAna/bunsite/tree/test im still unable to get the tailwindcss to parse correctly. it gets bundled in but the css doesnt apply. let me know if this is the wrong place to put this or if whats on https://bun.sh/docs/bundler/fullstack is the wrong way to do it
