### ISSUE TITLE
Bun.serve types disallow routes and websocket being specified together

### ISSUE THREAD

**Issue by mayfieldiv** [oven-sh/bun#17871]
I assume this is unintentional because:
1. Bun seems to serve the routes and websocket just fine when they're both defined (as well as the fetch for the upgrade and other non-websocket routes)
2. the `static` property that `routes` is replacing works fine alongside `websocket`

### Example of what I'm trying to do:
```ts
import index from "./index.html";
import { Elysia } from "elysia";

const app = new Elysia(); // ...

Bun.serve({
  routes: { "/": index }, // ERROR in typescript
  // static: { "/": index }, // typescript is happy with this (though it's deprecated)
  fetch: (req, server) => {
    if (!server.upgrade(req)) {
      return app.handle(req);
    }
  },
  websocket: {
    message: (ws, message) => { /* ... */ },
  },
});
```

### Relevant Bun code:
https://github.com/oven-sh/bun/blob/078318f33cdd399093560500b82f9385a9672fd8/packages/bun-types/bun.d.ts#L4495-L4512
https://github.com/oven-sh/bun/blob/078318f33cdd399093560500b82f9385a9672fd8/packages/bun-types/bun.d.ts#L4107-L4124

**Comment by lgarron** [comment]
I'm also unable to implement `routes` due to this issue. Is there any sort of short-term workaround?

**Comment by giansegato** [comment]
this seems to be a dupe of https://github.com/oven-sh/bun/issues/17849

a short term fix to make TS happy would be overriding typing; something like this:

```ts
} as Omit<ServeOptions, "fetch"> & { routes: any; websocket: WebSocketHandler<WebSocketData> });
```

**Comment by alii** [comment]
Fixed in #18121

**Comment by Salman9000** [comment]
Hello. I am still facing this issue.

![Image](https://github.com/user-attachments/assets/188f9a16-1dfe-4097-acb3-3c5ba2d3e2ab)
If i add routes, then websocket is giving error. 

```
"dependencies": {
    "@axiomhq/js": "^1.3.1",
    "@types/bun": "^1.2.10",
    "@types/papaparse": "^5.3.15",
    "@xyflow/react": "^12.6.0",
    "bullmq": "^5.51.0",
    "classnames": "^2.5.1",
    "clsx": "^2.1.1",
    "date-fns": "^3.6.0",
    "dayjs": "^1.11.13",
    "easy-currencies": "^1.8.3",
    "export-to-csv": "^1.4.0",
    "fetch-to-curl": "^0.6.0",
    "html2pdf.js": "^0.10.3",
    "ioredis": "^5.6.1",
    "jsep": "^1.4.0",
    "libphonenumber-js": "^1.12.7",
    "lodash": "^4.17.21",
    "next-axiom": "^1.9.1",
    "papaparse": "^5.5.2",
    "phone": "^3.1.59",
    "pocketbase": "^0.24.0",
    "react": "latest",
    "react-aria": "^3.39.0",
    "react-dom": "latest",
    "react-hot-toast": "^2.5.2",
    "tailwind-merge": "^2.6.0"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.9.4",
    "@iconify/react": "^5.2.1",
    "@types/js-cookie": "^3.0.6",
    "@types/node": "20.11.25",
    "@types/react": "18.2.64",
    "@types/react-dom": "^18.3.6",
    "@types/react-window": "^1.8.8",
    "autoprefixer": "^10.4.21",
    "dotenv": "^16.5.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.2.6",
    "prettier": "^3.5.3",
    "sass": "^1.87.0",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.8.3"
  }
```
