### ISSUE TITLE
Support LynxJS

### ISSUE THREAD

**Issue by tommy141x** [oven-sh/bun#18025]
### How can we reproduce the issue?

When trying to run ``bun dev`` or ``bun run build`` on a brand new Lynx project via ``bun create rspeedy@latest``, a compilation error is received, however it compiles fine when using npm/node instead.

### Bun 1.2.5 Compilation Error
```shell
$ rspeedy dev

  Rspeedy v0.8.3 (Rsbuild v1.2.15, Rspack v1.2.7)

start   build started...
lynx/ERROR [bytecode_generator.cc:78]: [21468:ERROR:bytecode_generator.cc(78)] Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:
    at :8775:2


error   Compile error:
Failed to compile, check the errors for troubleshooting.
× Error: encode error: {"status":1,"error_msg":"Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:\n    at :8775:2\n","data":{"filePath":""}}
  │     at <anonymous> (C:\users\Tommy\Documents\lynx-test\node_modules\@lynx-js\tasm\index.js:27:15)
  │     at processTicksAndRejections (native:7:39)
```

### Bun 1.2.4 Segmentation Fault (Initial Issue)

```shell
lynx-test bun run rspeedy dev

  Rspeedy v0.8.3 (Rsbuild v1.2.15, Rspack v1.2.7)

start   build started...
============================================================
Bun v1.2.4 (fd9a5ea6) Windows x64
Windows v.win11_dt
CPU: sse42 avx avx2
Args: "bun" "C:\Users\Tommy\Documents\lynx-test\node_modules\@lynx-js\rspeedy\bin\rspeedy.js" "dev"
Features: Bun.stderr Bun.stdin(2) Bun.stdout(3) http_server jsc transpiler_cache(15) tsconfig(28) process_dlopen
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:inspector"
Elapsed: 1360ms | User: 5812ms | Sys: 1640ms
RSS: 1.09GB | Peak: 1.09GB | Commit: 10.37GB | Faults: 320272

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Bun 1.2.4 Stack Trace (bun.report)

Bun v1.2.4 ([`fd9a5ea`](<https://github.com/oven-sh/bun/tree/fd9a5ea668e9ffce5fd5f25a7cfd2d45f0eaa85b>)) on windows x86_64 [_]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- *2 unknown/js code*

Features: Bun.stderr, jsc, standalone\_executable

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5298323857/">BUN-85</a></strong></sub>

**Comment by tommy141x** [comment]
When trying with the canary version of bun (v1.2.5-canary.116 cd4d75ee) I get further, but receive a compile error.

```➜  lynx-test bun dev
$ rspeedy dev

  Rspeedy v0.8.3 (Rsbuild v1.2.15, Rspack v1.2.7)

start   build started...
lynx/ERROR [bytecode_generator.cc:78]: [21468:ERROR:bytecode_generator.cc(78)] Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:
    at :8775:2


error   Compile error:
Failed to compile, check the errors for troubleshooting.
× Error: encode error: {"status":1,"error_msg":"Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:\n    at :8775:2\n","data":{"filePath":""}}
  │     at <anonymous> (C:\users\Tommy\Documents\lynx-test\node_modules\@lynx-js\tasm\index.js:27:15)
  │     at processTicksAndRejections (native:7:39)
```

**Comment by Hangovers** [comment]
Exact same thing here using bun 1.25
```
$ rspeedy dev

  Rspeedy v0.8.3 (Rsbuild v1.2.15, Rspack v1.2.7)

start   build started...
lynx/ERROR [bytecode_generator.cc:78]: [21468:ERROR:bytecode_generator.cc(78)] Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:
    at :8775:2


error   Compile error: 
Failed to compile, check the errors for troubleshooting.
× Error: encode error: {"status":1,"error_msg":"Compile error: lepusng exception: SyntaxError: unexpected token in expression: ')' backtrace:\n    at :8775:2\n","data":{"filePath":""}}
  │     at <anonymous> (...\node_modules\@lynx-js\tasm\index.js:27:15)
  │     at processTicksAndRejections (native:7:39)

error: script "dev" exited with code 58
info    Gracefully shutting down. Please wait... (Press Ctrl+C again to force exit)
```

am on windows 11 atm, exact same steps

**Comment by tommy141x** [comment]
Fixed in [#400](https://github.com/lynx-family/lynx-stack/pull/400)

**Comment by dmjio** [comment]
@tommy141x can we re-open. Still experiencing this error

```bash
bun create rspeedy@latest && cd bun-rspeedy && bunx upgrade-rspeedy-canary@0.9.0-canary-20250402-df637229 && bun install && bun run dev
```

```
error   ResolveMessage: Cannot find module './client/hmr/WebSocketClient.js' from '/Users/dmjio/Desktop/bun-rspeedy/node_modules/@lynx-js/rspeedy/dist/src_plugins_dev_plugin_ts.js'
```

`bun-v1.2.8`, `Sequoia-15.4`

**Comment by tommy141x** [comment]
@dmjio That's a different error which has already been fixed in [#428](https://github.com/lynx-family/lynx-stack/pull/428) 👍

**Comment by dmjio** [comment]
@tommy141x @colinaaa 

Per @paperclover 's analysis, this issue is resolved when `node` is present in `PATH`. I do not have `node` installed globally so the paths were being rewritten to use `bun` and it was triggering the above path error (`Cannot find module './client/hmr/WebSocketClient.js' ).`

Once `node` is in my PATH the issue resolves.

```bash
$ nix-shell -p nodejs --run 'bun run dev'
```

![Image](https://github.com/user-attachments/assets/1529b6f4-90d3-48d6-babe-5b7340fd3bb3)

**Comment by tommy141x** [comment]
@dmjio Could you check if this remains an issue referencing:

> Hi @abdu-frh, could you try upgrading to Bun v1.2.9? This version supports [`require.resolve` with `paths`](https://bun.sh/blog/bun-v1.2.9#support-for-require-resolve-paths-option). 

 _Originally posted by @colinaaa in [#253](https://github.com/lynx-family/lynx-stack/issues/253#issuecomment-2801940594)_
