### ISSUE TITLE
bun add/install "failed to resolve"

### ISSUE THREAD

**Issue by jdb8** [oven-sh/bun#1830]
### What version of Bun is running?

0.5.0

### What platform is your computer?

Linux 5.4.0-1068-aws x86_64 x86_64

### What steps can reproduce the bug?

Whenever I try to `bun add` or `bun install` with the default or custom registry, dependencies fail to install with `failed to resolve`. For example:

```bash
❯ cd `mktemp -d`
❯ bun add react --verbose
bun add v0.5.0 (2db04ef9)
Enqueue package manifest for download: react
  🔍 Resolving [1/1]     [6.78ms]
 Downloaded react versions
error: react@latest failed to resolve
❯ rm -rf ~/.bun/install/cache
❯ BUN_CONFIG_REGISTRY=https://<my_known_registry> bun add react
bun add v0.5.0 (2db04ef9)
error: react@latest failed to resolve
```

It's not specific to react:

```bash
❯ bun add lodash
bun add v0.5.0 (2db04ef9)
error: lodash@latest failed to resolve
```

I've been experiencing this for all prior versions of bun, so it's also not specific to 0.5.0.

I have a suspicion that it's some kind of firewall at play, but that wouldn't make sense when it comes to my custom registry, which definitely works on this machine.

For comparison, `npm install` works:

```bash
❯ npm install react
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp.4VOpfXx7KY No description
npm WARN tmp.4VOpfXx7KY No repository field.
npm WARN tmp.4VOpfXx7KY No license field.

+ react@18.2.0
added 3 packages from 2 contributors in 0.911s
```

### What is the expected behavior?

Bun installs packages without `failed to resolve` errors.

### What do you see instead?

```
❯ bun add react --verbose
bun add v0.5.0 (2db04ef9)
Enqueue package manifest for download: react
  🔍 Resolving [1/1]     [6.78ms]
 Downloaded react versions
error: react@latest failed to resolve
```

**Comment by alexlamsl** [comment]
Fixed by #1854

**Comment by jdb8** [comment]
@alexlamsl great! Just to confirm, is it expected that the canary version of `bun` should contain that PR?

I tried installing it via `bun upgrade --canary`, but the error above still persists:

```
❯ bun add react
bun add v0.5.2 (be79f6e8)
error: react@latest failed to resolve
```

Seems like be79f6e8 should have https://github.com/oven-sh/bun/pull/1854 included?

**Comment by alexlamsl** [comment]
Just tested with latest version of `--canary`:
```console
$ bun upgrade --canary
[5.97s] Upgraded.

Welcome to bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/aa9e56edfeee3089dc9a3d820d021be20542d3da...main
```
```console
$ mkdir test-react
$ cd test-react
$ bun init -y
Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts
```
```console
$ bun add react
bun add v0.5.2 (be79f6e8)

 installed react@18.2.0


 3 packages installed [283.00ms]
```
If this is still failing for you, please provide more details so I may be able to reproduce the issue you encounter.

**Comment by jdb8** [comment]
@alexlamsl are there additional logs I can provide that would be helpful? 

I tried `--verbose` as shown above, but it doesn't print much more.

My suspicion as mentioned above is that there's some kind of firewall at play - "failed to resolve" makes me think that bun is trying to reach out somewhere during install. The confusing part is that this also occurs when I provide a custom registry in `bunfig.toml`, at which point `--verbose` shows:

```
❯ bun add react --verbose
bun add v0.5.2 (be79f6e8)
Enqueue package manifest for download: react
  🔍 Resolving [1/1] Request: GET /react
	Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
	Connection: keep-alive
	User-Agent: Bun/0.5.2
	Host: <my_registry_domain>
	Accept-Encoding: gzip, deflate

Request: GET /react
	Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
	Connection: keep-alive
	User-Agent: Bun/0.5.2
	Host: <my_registry_domain>
	Accept-Encoding: gzip, deflate

Request: GET /react
	Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
	Connection: keep-alive
	User-Agent: Bun/0.5.2
	Host: <my_registry_domain>
	Accept-Encoding: gzip, deflate

    [110.24ms]
 Downloaded react versions
error: react@latest failed to resolve
```

Is there any way to see what's happening between "Downloaded react versions" and "error: react@latest failed to resolve"? Is bun expecting something specific from the registry response that it's not getting? 

Also - should this issue be reopened? I'm not sure https://github.com/oven-sh/bun/pull/1854 was necessarily relevant to the original issue I was running into.

**Comment by alexlamsl** [comment]
`bun add react` does require downloading said dependency from the `npm` registry, so if somehow have network-related issues with that then it won't work &minus; does `npm add react` work under the same conditions, and if so, what is under `.npmrc`, i.e. network configurations etc.?

**Comment by jdb8** [comment]
@alexlamsl `npm install react` (and `yarn add react`) do work with my custom registry set globally:

```
❯ npm install react
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp.Bq8A3qgwK9 No description
npm WARN tmp.Bq8A3qgwK9 No repository field.
npm WARN tmp.Bq8A3qgwK9 No README data
npm WARN tmp.Bq8A3qgwK9 No license field.

+ react@18.2.0
added 3 packages from 2 contributors in 0.562s
```

```
❯ yarn add react
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ react@18.2.0
info All dependencies
├─ js-tokens@4.0.0
├─ loose-envify@1.4.0
└─ react@18.2.0
Done in 0.43s.
```

As mentioned, though, this bug still persists in bun even with a custom registry set in `bunfig.toml` - since the verbose logs show that bun is indeed fetching from this custom registry, it makes me think that bun may also be reaching out to an external server too?

Is there any way to have bun print out more verbose logging to see what's actually failing? The fact that it's able to get to `Downloaded react versions` makes me think that it could also be failing internally after that stage - likely at the integrity verification step. I'm unable to work out how to log more info to verify that assumption, though.

For context, the custom registry domain is an internal implementation, so I'd be curious to know if bun is expecting specific fields/integrity hash behaviour or similar which npm and yarn are more permissive about. That could give us a clue as to why only bun appears to have issues here.
