### ISSUE TITLE
node:test errors with "Failed to get caller source origin"

### ISSUE THREAD

**Issue by Conaclos** [oven-sh/bun#18474]
### What version of Bun is running?

1.2.6

### What platform is your computer?

Linux 6.13.8-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Here a reproduction:

```
❯ ls
file.test.js

❯ cat file.test.js 
// Use the Node.js test API in your Bun projects
import test from "node:test";

test("basic functionality", (t) => {
  // Your test code here
});

❯ bun test file.test.js 
bun test v1.2.6 (8ebd5d53)

file.test.js:

# Unhandled error between tests
-------------------------------
194 |       let filePath = s.getFileName();
195 |       if (filePath && !isBuiltinModule(filePath))
196 |         return filePath;
197 |       return @undefined;
198 |     })?.getFileName();
199 |     throw new Error("Failed to get caller source origin");
                                                ^
error: Failed to get caller source origin
      at callerSourceOrigin (node:test:199:11)
      at node:test (node:test:4:73)
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 tests across 1 files. [18.00ms]
```

### What is the expected behavior?

No error.

### What do you see instead?

I got an error while `node --test`/`deno test` succeed.

**Comment by xseman** [comment]
I'm having same issiue

test.ts

```ts
// Use the Node.js test API in your Bun projects
import test from "node:test";

test("basic functionality", (t) => {
	// Your test code here
});
```
output

```plain
$ bun test.ts
194 |       let filePath = s.getFileName();
195 |       if (filePath && !isBuiltinModule(filePath))
196 |         return filePath;
197 |       return @undefined;
198 |     })?.getFileName();
199 |     throw new Error("Failed to get caller source origin");
                                                ^
error: Failed to get caller source origin
      at callerSourceOrigin (node:test:199:11)
      at node:test (node:test:4:73)

Bun v1.2.8-canary.26+7021c42cf (Linux x64)
```

**Comment by jordanebelanger** [comment]
@Electroid  Just to bring more attention here, I am also having the same issue on v1.2.8.

The only problem remaining on my porting of my huge turborepo powered monorepo from node/pnpm to bun 😅 🙏

**Comment by Jarred-Sumner** [comment]
<img width="571" alt="Image" src="https://github.com/user-attachments/assets/8f2eb04e-5307-40d0-951d-01fd527ed206" />

Fixed in Bun v1.2.11. To try it now, run `bun upgrade --canary`

**Comment by xseman** [comment]
@Jarred-Sumner tested, works now 👍 👍

**Comment by jordanebelanger** [comment]
@xseman For me, there is still an issue whereas only the first file has its tests ran and the other files' tests are ignored.

**Comment by xseman** [comment]
@jordanebelanger I tested it on two of my projects with multiple files and nested tests, and everything worked fine. Could you provide a reproducible example so we can dig into the issue?

**Comment by jordanebelanger** [comment]
@xseman all the files will appear as if they were tested but only one file actually has its tests executed

<img width="1023" alt="Image" src="https://github.com/user-attachments/assets/bae9f008-3f34-453f-9f0f-dd645ffe569a" />

**Comment by xseman** [comment]
What output do you get when running with `--coverage`
