### ISSUE TITLE
HTTP 400 responses with empty body in tests after upgrading to Bun 1.2.6

### ISSUE THREAD

**Issue by PatricioPoncini** [oven-sh/bun#18501]
### What version of Bun is running?

1.2.6

### What platform is your computer?

Linux 6.8.0-48-generic x86_64 x86_64

### What steps can reproduce the bug?

The way to reproduce the bug is to run the test cases using Bun's `serve` and inject the routes, then test with `bun test.` At this point, the test cases that should return 404 errors for missing records instead return 400 errors with an empty body.

Additionally, I'm using Bun's `fetch` after injecting the routes, and my backend is built with Hono.

### What is the expected behavior?

The expected response for each test case (e.g., a `404` for a resource not found in the database).

### What do you see instead?

A `400` HTTP status code with an empty response body.

### Additional information

I updated Bun to version 1.2.6 (latest at the time), and some of my test cases started failing unexpectedly. The failing tests return HTTP status code 400 with no response body. I reviewed my code to ensure the issue wasn't caused by any recent changes on my end—I didn't update dependencies or modify anything related to these tests.

To verify, I downgraded to Bun 1.2.5 and reran the tests multiple times. In version 1.2.5, all tests passed consistently without issues. This leads me to believe that the problem may have been introduced in Bun 1.2.6.

**Comment by PatricioPoncini** [comment]
> Sorry you ran into this while upgrading! Is there anyway to share some code, or do you have any way we could try to reproduce?

Unfortunately the code is related to a corporate project and I cannot share it due to privacy restrictions. However, the issue only occurred during manual endpoint testing. When I was manually testing the endpoints or making requests in development, this didn't happen.

**Comment by PatricioPoncini** [comment]
Hi @Electroid, I updated some more information. I was able to temporarily resolve the issue by downgrading to Bun version 1.2.5, where no problems occur. My test cases fail with DELETE, POST, PUT, and GET methods. When I log the response in the test cases, the data is literally `data: ""` with a 400 HTTP status code.

With version 1.2.7, the error still occurs in the same way. The failing tests and their count are random, and all I get is a `400` status code with an empty response body.

**Comment by cirospaciari** [comment]
@PatricioPoncini I believe this was fixed in bun `v1.2.8` can you check if solves the Issue on your project?

**Comment by PatricioPoncini** [comment]
> [@PatricioPoncini](https://github.com/PatricioPoncini) I believe this was fixed in bun `v1.2.8` can you check if solves the Issue on your project?

Yeah, the problem is solved. Do you have any idea what caused it?

**Comment by cirospaciari** [comment]
> > [@PatricioPoncini](https://github.com/PatricioPoncini) I believe this was fixed in bun `v1.2.8` can you check if solves the Issue on your project?
> 
> Yeah, the problem is solved. Do you have any idea what caused it?

We changed the way we wait for data and resume socket pooling for sockets in node:http this fixed similar regression

**Comment by Bader-Idris** [comment]
> > > [@PatricioPoncini](https://github.com/PatricioPoncini) I believe this was fixed in bun `v1.2.8` can you check if solves the Issue on your project?
> > 
> > Yeah, the problem is solved. Do you have any idea what caused it?
> 
> We changed the way we wait for data and resume socket pooling for sockets in node:http this fixed similar regression

Yet in secured layer of Https and with reverse proxy of nginx for instance, this issue is still occuring
