### ISSUE TITLE
The "options.encoding" property must be of type string. Received undefined

### ISSUE THREAD

**Issue by dmythro** [oven-sh/bun#18700]
### What version of Bun is running?

1.2.8+adab0f64f

### What platform is your computer?

Darwin 24.4.0 arm64 arm

### What steps can reproduce the bug?

I use `next-auth` 4.24.11. Here's an error and a stack trace:

```
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error The "options.encoding" property must be of type string. Received undefined {
  error: {
    message: "The \"options.encoding\" property must be of type string. Received undefined",
    stack: "TypeError: The \"options.encoding\" property must be of type string. Received undefined\n    at setAAD (native)\n    at <anonymous> (node:crypto:505:32)\n    at gcmEncrypt (webpack-internal:///(rsc)/./node_modules/jose/dist/node/cjs/runtime/encrypt.js:40:22)\n    at <anonymous> (webpack-internal:///(rsc)/./node_modules/jose/dist/node/cjs/jwe/flattened/encrypt.js:154:67)\n    at processTicksAndRejections (native)",
    name: "TypeError",
  },
  providerId: "google",
  message: "The \"options.encoding\" property must be of type string. Received undefined",
}
```

### Additional information

The issue goes with Google OAuth Provider. We also use the most recent Next.js 15 and React 19 versions.
It was all working fine in Bun 1.2.5, after this version auth is broken.

**Comment by dmythro** [comment]
I don't see this fixed in Bun 1.2.9.
Am I missing something? @cirospaciari 

<img width="1284" alt="Image" src="https://github.com/user-attachments/assets/2ce2c071-df00-4f7b-983d-87bbf91b5ba4" />

**Comment by FlorianLebecque** [comment]
Hello, the issue seems to be still present in 1.2.9. But only appear on system without nodejs installed :

```bash
GET /signin 200 in 9272ms
 GET /api/auth/session 200 in 1210ms
 GET /api/auth/providers 200 in 575ms
 GET /api/auth/csrf 200 in 334ms
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE "public"."User"."name" = $1 LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE "public"."User"."email" = $1 LIMIT $2 OFFSET $3
 ⨯ Error [TypeError]: The "options.encoding" property must be of type string. Received undefined
    at setAAD (null)
    at processTicksAndRejections (null) {
  code: 'ERR_INVALID_ARG_TYPE',
  toString: [Function: toString]
}
 ⨯ Error [TypeError]: The "options.encoding" property must be of type string. Received undefined
    at setAAD (null)
    at processTicksAndRejections (null) {
  page: '/api/auth/callback/login',
  code: 'ERR_INVALID_ARG_TYPE',
  toString: [Function: toString]
}
 ○ Compiling /_error ...
[BABEL] Note: The code generator has deoptimised the styling of /ORMI-CORE/ormi-app/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
 ✓ Compiled /_error in 2.1s
```


Here is my DockerFile that managed to fix the issue : 

```dockerfile
# Use latest Node.js LTS version
FROM node:lts-bullseye

# Set the timezone to UTC
ENV TZ=UTC
# Set the locale to UTF-8
ENV LANG=C.UTF-8


# Install Bun
RUN curl -fsSL https://bun.sh/install | bash && \
    mv /root/.bun/bin/bun /usr/local/bin/bun


# Set working directory
WORKDIR /ORMI-CORE

# Copy all folders from the host to the container
COPY . .

# Copy the entrypoint script
COPY ormi_entrypoint.sh /ormi_entrypoint.sh

# Make scripts executable and run the build script (installs deps, links packages)
RUN chmod +x /ormi_entrypoint.sh \
    && chmod +x build.sh \
    && ./build.sh

# Set the working directory for the application runtime
WORKDIR /ORMI-CORE/ormi-app

# Set the entrypoint
ENTRYPOINT ["/ormi_entrypoint.sh"]
```

Change the image back to the latest bun will break (1.2.9)

**Comment by cirospaciari** [comment]
> Hello, the issue seems to be still present in 1.2.9. But only appear on system without nodejs installed :
> 
> GET /signin 200 in 9272ms
>  GET /api/auth/session 200 in 1210ms
>  GET /api/auth/providers 200 in 575ms
>  GET /api/auth/csrf 200 in 334ms
> prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE "public"."User"."name" = $1 LIMIT $2 OFFSET $3
> prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE "public"."User"."email" = $1 LIMIT $2 OFFSET $3
>  ⨯ Error [TypeError]: The "options.encoding" property must be of type string. Received undefined
>     at setAAD (null)
>     at processTicksAndRejections (null) {
>   code: 'ERR_INVALID_ARG_TYPE',
>   toString: [Function: toString]
> }
>  ⨯ Error [TypeError]: The "options.encoding" property must be of type string. Received undefined
>     at setAAD (null)
>     at processTicksAndRejections (null) {
>   page: '/api/auth/callback/login',
>   code: 'ERR_INVALID_ARG_TYPE',
>   toString: [Function: toString]
> }
>  ○ Compiling /_error ...
> [BABEL] Note: The code generator has deoptimised the styling of /ORMI-CORE/ormi-app/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
>  ✓ Compiled /_error in 2.1s
> Here is my DockerFile that managed to fix the issue :
> 
> # Use latest Node.js LTS version
> FROM node:lts-bullseye
> 
> # Set the timezone to UTC
> ENV TZ=UTC
> # Set the locale to UTF-8
> ENV LANG=C.UTF-8
> 
> 
> # Install Bun
> RUN curl -fsSL https://bun.sh/install | bash && \
>     mv /root/.bun/bin/bun /usr/local/bin/bun
> 
> 
> # Set working directory
> WORKDIR /ORMI-CORE
> 
> # Copy all folders from the host to the container
> COPY . .
> 
> # Copy the entrypoint script
> COPY ormi_entrypoint.sh /ormi_entrypoint.sh
> 
> # Make scripts executable and run the build script (installs deps, links packages)
> RUN chmod +x /ormi_entrypoint.sh \
>     && chmod +x build.sh \
>     && ./build.sh
> 
> # Set the working directory for the application runtime
> WORKDIR /ORMI-CORE/ormi-app
> 
> # Set the entrypoint
> ENTRYPOINT ["/ormi_entrypoint.sh"]
> Change the image back to the latest bun will break (1.2.9)

This was fixed in https://github.com/oven-sh/bun/pull/18905 with will be present in `1.2.10` sorry that you are hitting this issue, `bun upgrade --canary` should solve this issue
