### ISSUE TITLE
ReadbleStream reads to completion in server, does not stream

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#1886]
### What version of Bun is running?

0.5.1

### What platform is your computer?

x86_64 GNU/Linux

### What steps can reproduce the bug?

bun_server.js

```
import { serve, file, } from 'bun';

serve({
  port: 8443,
  keyFile: './certificate.key',
  certFile: './certificate.pem',
  async fetch(req, server) {
    console.log(
      'fetch',
      req,
    );
    let arr = 'abcdefg'.split('');
    let body = new ReadableStream({
      async pull(c) {
        while (arr.length) {
          c.enqueue(arr.splice(0, 1)[0]);
          await new Promise((resolve) => setTimeout(resolve, 1000));
        } 
        c.close();
      }
    }); // TextEncoderStream() is undefined
    return new Response(
      body
      , {
          headers: {
            'Access-Control-Allow-Origin':'*',
            'Access-Control-Allow-Private-Network': 'true'
          }
        }
    )
  },
})
```

```
 ./bun run --no-install --hot bun_server.js
```

At `console` on Chromium 111

```
(await fetch('https://localhost:8443', {
  // duplex:'half'
})).body
  .pipeThrough(new TextDecoderStream())
  .pipeTo(new WritableStream({
  write(v) {
    console.log(v);
  }, 
  close() {
    console.log('Stream closed.');
  }
}));
```

### What is the expected behavior?

```
a
b
c
d
e
f
g
Stream closed.
```

### What do you see instead?

```
abcdefg
Stream closed.
```

### Additional information

Using `deno` we get the expected result

```
const server = Deno.listenTls({
  port: 8443,
  certFile: 'certificate.pem',
  keyFile: 'certificate.key',
  alpnProtocols: ['h2', 'http/1.1'],
});

// Connections to the server will be yielded up as an async iterable.
for await (const conn of server) {
  // In order to not be blocking, we need to handle each connection individually
  // without awaiting the function
  serveHttp(conn);
}

async function serveHttp(conn) {
  // This "upgrades" a network connection into an HTTP connection.
  const httpConn = Deno.serveHttp(conn);
  // Each request sent over the HTTP connection will be yielded as an async
  // iterator from the HTTP connection.
  for await (const requestEvent of httpConn) {
    // The native HTTP server uses the web standard `Request` and `Response`
    // objects.
    let body = null;
    if (requestEvent.request.method === 'GET') {
      let arr = 'abcdefg'.split('');
      body = new ReadableStream({
        async pull(c) {
          while (arr.length) {
            c.enqueue(arr.splice(0, 1)[0]);
            await new Promise((resolve) => setTimeout(resolve, 100));
          }
          c.close();
        }
      }).pipeThrough(new TextEncoderStream());
    }
    // The requestEvent's `.respondWith()` method is how we send the response
    // back to the client.
    requestEvent.respondWith(
      new Response(body, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Private-Network': 'true',
        },
      })
    );
  }
}
```

**Comment by Jarred-Sumner** [comment]
definitely a bug

It's supposed to send off the stream as soon as the async tick happens

In the meantime, could you try:
1) set `type` to `"direct"` in ReadableStreamSource (object where `pull` is defined)
2) instead of .enqueue, call `.write`

**Comment by guest271314** [comment]
```
let body = new ReadableStream({
      type: 'direct',
      async pull(c) {
        while (arr.length) {
          c.write(arr.splice(0, 1)[0]);
          await new Promise((resolve) => setTimeout(resolve, 1000));
        } 
        c.close();
      }
    }); // TextEncoderStream() is undefined
```

At `console` on Chromium 111

```
(await fetch('https://localhost:8443', {
  //duplex:'half'
})).body
  .pipeThrough(new TextDecoderStream())
  .pipeTo(new WritableStream({
  write(v) {
    console.log(v);
  }, 
  close() {
    console.log('Stream closed.');
  }
}))

Welcome to Bun! To get started, return a Response object.
Stream closed.
```

Wow. Where did that come from? 

The stream still awaits the `Promise` in the server.

**Comment by Jarred-Sumner** [comment]
What if you do this

```js
let body = new ReadableStream({
      type: 'direct',
      async pull(c) {
        while (arr.length) {
          c.write(arr.splice(0, 1)[0]);
          c.flush();
          await new Promise((resolve) => setTimeout(resolve, 1000));
        } 
        c.close();
      });
```

**Comment by guest271314** [comment]
```
a
Stream closed.
```

**Comment by guest271314** [comment]
Why is there a `direct` parameter in the `ReadableStream` constructor ?

https://streams.spec.whatwg.org/#locking
> A readable stream reader, or simply reader, is an object that allows direct reading of [chunks](https://streams.spec.whatwg.org/#chunk) from a [readable stream](https://streams.spec.whatwg.org/#readable-stream).

**Comment by cirospaciari** [comment]
Flush was fixed on https://github.com/oven-sh/bun/pull/3073

**Comment by guest271314** [comment]
> Flush was fixed on https://github.com/oven-sh/bun/pull/3073

This is not fixed. 

./bun --version 
0.6.3

What is the expected behavior?
a
b
c
d
e
f
g
Stream closed.

What do you see instead?
abcdefg
Stream closed.

**Comment by guest271314** [comment]
@cirospaciari Nothing changed. Bun ReadableStream still reads to completion in server, does not stream.

What specific code in the linked PR was supposed to fix this issue?

**Comment by Jarred-Sumner** [comment]
Confrming that this is not fixed, `curl` reported no output until the final chunk was received. 
<img width="385" alt="image" src="https://github.com/oven-sh/bun/assets/709451/fe3ec6d7-1c52-48d9-ac1f-2f444887cb83">

<img width="308" alt="image" src="https://github.com/oven-sh/bun/assets/709451/6a404478-a591-4e14-9398-f5e88249b0c2">

**Comment by Jarred-Sumner** [comment]
It is fixed with `"type": "direct"`, however.

```js
import { serve, file } from "bun";

serve({
  port: 8443,
  async fetch(req, server) {
    console.log("fetch", req);
    var remain = 10;
    let body = new ReadableStream({
      type: "direct",
      async pull(c) {
        while (remain--) {
          c.write(new Date().toTimeString() + "\n");
          c.flush();
          await new Promise((resolve) => setTimeout(resolve, 1000));
        }

        c.close();
      },
    }); // TextEncoderStream() is undefined
    return new Response(body, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Private-Network": "true",
      },
    });
  },
});

```

**Comment by guest271314** [comment]
> It is fixed with "type": "direct", however.

No, it's not.

**Comment by Jarred-Sumner** [comment]
> > It is fixed with "type": "direct", however.
> 
> No, it's not.

Can you paste the snippet with `"type": "direct"` that isn't working? The above prints timestamps one-by-one

**Comment by guest271314** [comment]
It's the same code at OP with the Bun-specific {type:'direct'} key and value in object passed to ReadableStream. I'm testing on Chromium 115 Dev Channel. I'm rather sure Deno, Node.js, and certainly not SeviceWorker implementation waits for the stream to be read in the server before sending the entire stream.

I'll compare Node.js, Deno, ServiceWorker Streams API implementation on Chromium and Firefox lastest tomorrow.

**Comment by guest271314** [comment]
![Screenshot_2023-05-26_19-11-49](https://github.com/oven-sh/bun/assets/4174848/450c429b-908a-456a-abed-aedce3275f7c)

**Comment by Jarred-Sumner** [comment]
are you on the canary build of bun? `bun upgrade --canary`

**Comment by guest271314** [comment]
I downloaded the release from this repository. bun-linux-x64-baseline.

I upgraded manually with `curl -fsSL https://bun.sh/install | bash`.

Same result. ReadbleStream reads to completion in server, does not stream.

We shouldn't have to specifiy an option for a `ReadableStream` to be direct, whatever behaviour is defined for direct should be default, else the implementation is not streaming.

**Comment by guest271314** [comment]
I just tested `deno` using `serveTls` from Deno std https://deno.land/std@0.167.0/http/server.ts?s=serveTls.

```
async function serve() {
  const responseInit = {
    duplex: 'half',
    keepalive: true,
    headers: {
      'Content-Type': 'text/plain',
      'Cross-Origin-Opener-Policy': 'unsafe-none',
      'Cross-Origin-Embedder-Policy': 'unsafe-none',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Private-Network': 'true',
      'Access-Control-Allow-Headers': 'Access-Control-Request-Private-Network',
      'Access-Control-Allow-Methods': 'OPTIONS,POST,GET,HEAD',
    },
  };
  const controller = new AbortController();
  const { signal } = controller;
  await serveTls(
    async (request) => {
      let body = null;
      if (request.method === 'OPTIONS' || request.method === 'HEAD') {
        return new Response(null, responseInit);
      }
     let encoder = new TextEncoder();
     let arr = 'abcdefg'.split('');
     body = new ReadableStream({
      async pull(c) {
        while (arr.length) {
          c.enqueue(encoder.encode(arr.splice(0, 1)[0]));
          await new Promise((resolve) => setTimeout(resolve, 1000));
        } 
        c.close();
      }
    }); 
    return new Response(
      body
      , responseInit
    )
    },
    {
      certFile: 'certificate.pem',
      keyFile: 'certificate.key',
      signal,
    }
  );
}
```

![Screenshot_2023-05-26_23-05-31](https://github.com/oven-sh/bun/assets/4174848/eb958b56-7d43-48d9-9d0b-9ff8093d98b6)


Updated bun server code handling OPTIONS request, the same as the Deno server

```
import { serve, file, } from 'bun';

const responseInit = {
    duplex: 'half',
    keepalive: true,
    headers: {
      'Content-Type': 'audio/wav',
      'Cross-Origin-Opener-Policy': 'unsafe-none',
      'Cross-Origin-Embedder-Policy': 'unsafe-none',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Private-Network': 'true',
      'Access-Control-Allow-Headers': 'Access-Control-Request-Private-Network',
      'Access-Control-Allow-Methods': 'OPTIONS,POST,GET,HEAD',
    },
  };

serve({
  port: 8443,
  keyFile: './certificate.key',
  certFile: './certificate.pem',
  async fetch(req, server) {
    console.log(
      'fetch',
      req,
    );
    if (req.method === 'OPTIONS' || req.method === 'HEAD') {
        return new Response(null, responseInit);
      }
    let arr = 'abcdefg'.split('');
    let encoder = new TextEncoder();
    let body = new ReadableStream({
      async pull(c) {
        while (arr.length) {
          c.enqueue(encoder.encode(arr.splice(0, 1)[0]));
          await new Promise((resolve) => setTimeout(resolve, 1000));
        } 
        c.close();
      }
    }); // TextEncoderStream() is undefined
    return new Response(
      body
      , responseInit
    )
  },
})
```

![Screenshot_2023-05-26_23-06-59](https://github.com/oven-sh/bun/assets/4174848/c8b43322-40d7-43f6-86a7-81cf1b9cdb4e)

**Comment by guest271314** [comment]
Thia ia how Streams API should work https://plnkr.co/edit/0hoSBayPyMBGGGTE. Using a `ServiceWorker`, `respondWith()`, and `fetch()`. Tested on Chromium 115 and 116, and Mozilla Firefox 115.0a1.

**Comment by unkhz** [comment]
Can confirm that the issue still exists. No change in behaviour with `type: 'direct'` or without it.  Nothing is received from the stream before controller.close is called. After first request, "Welcome to Bun! To get started, return a Response object." is received instead of the streamed response.
```
$ bun upgrade --canary
Congrats! You're already on the latest canary build of bun
$ bun --version
0.6.12
```

**Comment by unkhz** [comment]
Adding the "\n" into the output seems to make it work, though, but only with `type: 'direct'`. 🤔 

This does not work:
```typescript
let i = 0
serve({
  port: SERVER_PORT,
  fetch(req) {
    let body = new ReadableStream({
      type: 'direct',
      async pull(controller) {
        while (i++ < 10) {
          controller.write(i.toString()) // <------- this line
          controller.flush()
          await wait(1000)
        }
        controller.close()
      },
    })
    return new Response(body, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Private-Network': 'true',
      },
    })
  },
})
```
This works as expected:
```typescript
let i = 0
serve({
  port: SERVER_PORT,
  fetch(req) {
    let body = new ReadableStream({
      type: 'direct',
      async pull(controller) {
        while (i++ < 10) {
          controller.write(i.toString() + '\n') // <------- this line
          controller.flush()
          await wait(1000)
        }
        controller.close()
      },
    })
    return new Response(body, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Private-Network': 'true',
      },
    })
  },
})

**Comment by guest271314** [comment]
That's very Bun-specific behaviour. `type:'direct'` really makes no sense when using Streams Standard as the stream should actually stream and there is no `type:'direct'` nor `write()` and `flush()` defined on `ReadableStreamDefaultController` in that specification https://streams.spec.whatwg.org/.
