### ISSUE TITLE
zsh: segmentation fault  bun install

### ISSUE THREAD

**Issue by cmark1302** [oven-sh/bun#1945]
### What platform is your computer?

Macos

### How did you attempt to install or upgrade?

bun install with workspace

### What do you see instead?

Install successful with workspace

**Comment by Electroid** [comment]
Hey, thanks for reporting this issue! We just released Bun v0.5.2 (like a few minutes ago), could you try again after running: `bun upgrade`.

Also, if possible, could you share your `package.json`?

**Comment by cmark1302** [comment]
Yes, this is still happening. this is a private project and we aren't allow to share the package.json. Sorry

**Comment by Jarred-Sumner** [comment]
Can you try in the canary build of bun? `bun upgrade --canary`

**Comment by coratgerl** [comment]
Same issue with workspace usage. I try with ```bun upgrade --canary```

**Comment by furkankinyas** [comment]
I solved the problem by changing the name of DATABASE_URL -> DATABASEURL in the env file

**Comment by Electroid** [comment]
We fixed that particular `.env` issue a while ago.
