### ISSUE TITLE
fs.constants is undefined and not implemented

### ISSUE THREAD

**Issue by yharaskrik** [oven-sh/bun#1958]
### What version of Bun is running?

0.5.3

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

require `fs.constants` and see it is undefined

### What is the expected behavior?

`fs.constants` should contain valid constants

### What do you see instead?

`undefined`

### Additional information

I can see in the bun codebase that in `fs.exports.js` `constants` is exported, but the variable does not exist anywhere (ie. it is not defined). Should it be imported from somewhere or is it not implemented yet? From my investigation the values don't particularly matter just that they are defined and all unique.

More than happy to do some investigation and implement this unless this is already in the plan.

**Comment by Electroid** [comment]
Thanks for reporting, yea this is likely a bug in how it's exported. Will see if we can get it fixed in 0.5.4

**Comment by yharaskrik** [comment]
> Thanks for reporting, yea this is likely a bug in how it's exported. Will see if we can get it fixed in 0.5.4

Thank you!

**Comment by yharaskrik** [comment]
Just upgraded to v0.5.4 and tried this out and I am still getting the same error.

`tmp` (the library from npm) does this

```javascript
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const _c = { fs: fs.constants, os: os.constants };
const rimraf = require('rimraf');
```

if you log `_c` you get:

```
{
  fs: undefined,
  os: {
    errno: {
      E2BIG: 7,
      EACCES: 13,
      EADDRINUSE: 48,
      EADDRNOTAVAIL: 49,
      EAFNOSUPPORT: 47,
      EAGAIN: 35,
      EALREADY: 37,
      EBADF: 9,
      EBADMSG: 94,
      EBUSY: 16,
      ECANCELED: 89,
      ECHILD: 10,
      ECONNABORTED: 53,
      ECONNREFUSED: 61,
      ECONNRESET: 54,
      EDEADLK: 11,
      EDESTADDRREQ: 39,
      EDOM: 33,
      EDQUOT: 69,
      EEXIST: 17,
      EFAULT: 14,
      EFBIG: 27,
      EHOSTUNREACH: 65,
      EIDRM: 90,
      EILSEQ: 92,
      EINPROGRESS: 36,
      EINTR: 4,
      EINVAL: 22,
      EIO: 5,
      EISCONN: 56,
      EISDIR: 21,
      ELOOP: 62,
      EMFILE: 24,
      EMLINK: 31,
      EMSGSIZE: 40,
      EMULTIHOP: 95,
      ENAMETOOLONG: 63,
      ENETDOWN: 50,
      ENETRESET: 52,
      ENETUNREACH: 51,
      ENFILE: 23,
      ENOBUFS: 55,
      ENODATA: 96,
      ENODEV: 19,
      ENOENT: 2,
      ENOEXEC: 8,
      ENOLCK: 77,
      ENOLINK: 97,
      ENOMEM: 12,
      ENOMSG: 91,
      ENOPROTOOPT: 42,
      ENOSPC: 28,
      ENOSR: 98,
      ENOSTR: 99,
      ENOSYS: 78,
      ENOTCONN: 57,
      ENOTDIR: 20,
      ENOTEMPTY: 66,
      ENOTSOCK: 38,
      ENOTTY: 25,
      ENXIO: 6,
      EOPNOTSUPP: 45,
      EOVERFLOW: 84,
      EPERM: 1,
      EPIPE: 32,
      EPROTO: 100,
      EPROTONOSUPPORT: 43,
      EPROTOTYPE: 41,
      ERANGE: 34,
      EROFS: 30,
      ESPIPE: 29,
      ESRCH: 3,
      ESTALE: 70,
      ETIME: 101,
      ETIMEDOUT: 60,
      ETXTBSY: 26,
      EXDEV: 18
    },
    signals: {
      SIGHUP: 1,
      SIGINT: 2,
      SIGQUIT: 3,
      SIGILL: 4,
      SIGTRAP: 5,
      SIGABRT: 6,
      SIGIOT: 6,
      SIGBUS: 10,
      SIGFPE: 8,
      SIGKILL: 9,
      SIGUSR1: 30,
      SIGSEGV: 11,
      SIGUSR2: 31,
      SIGPIPE: 13,
      SIGALRM: 14,
      SIGTERM: 15,
      SIGCHLD: 20,
      SIGCONT: 19,
      SIGSTOP: 17,
      SIGTSTP: 18,
      SIGTTIN: 21,
      SIGTTOU: 22,
      SIGURG: 16,
      SIGXCPU: 24,
      SIGXFSZ: 25,
      SIGVTALRM: 26,
      SIGPROF: 27,
      SIGWINCH: 28,
      SIGIO: 23,
      SIGPOLL: 7,
      SIGINFO: 29,
      SIGSYS: 12
    },
    priority: {
      PRIORITY_LOW: 19,
      PRIORITY_BELOW_NORMAL: 10,
      PRIORITY_NORMAL: 0,
      PRIORITY_ABOVE_NORMAL: -7,
      PRIORITY_HIGH: -14,
      PRIORITY_HIGHEST: -20
    },
    dlopen: {
      RTLD_LAZY: 1,
      RTLD_NOW: 2,
      RTLD_GLOBAL: 8,
      RTLD_LOCAL: 4
    },
    UV_UDP_REUSEADDR: 4
  }
}
```

Did the fix not make it in? (The linked commit is tagged as 0.5.4 so id assume it did?)

**Comment by Jarred-Sumner** [comment]
It was supposed to but the fix only applied to development builds of bun which is not useful

In canary, it is fixed for both (and with a test to prevent this from happening again)

```
bun upgrade --canary
```

**Comment by yharaskrik** [comment]
> It was supposed to but the fix only applied to development builds of bun which is not useful
> 
> In canary, it is fixed for both (and with a test to prevent this from happening again)
> 
> ```
> bun upgrade --canary
> ```

Thanks Jarrod! I'll try canary (before I posted this I did try to upgrade to canary but it didn't upgrade back 0.5.4 so maybe canary wasn't out at that point?

**Comment by yharaskrik** [comment]
Upgrade still says 0.5.4 after using `--canary`.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/9469090/215928928-7aba7b55-8e3c-4755-a678-f74fd1c0daee.png">

**Comment by yharaskrik** [comment]
Ok looks like it is there now!
