### ISSUE TITLE
Bun is using 100% CPU of a core on Linux and MacOS when Debugging and more. 1.3.1 - 1.0.0

### ISSUE THREAD

**Issue by hunterwilhelm** [oven-sh/bun#21654]
### What version of Bun is running?

* 1.2.19+aad3abead
* 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983
* And every version in between, gave up trying to go to an older version

### What platform is your computer?

We tested on these platforms with VSCode and Cursor, they all have the 100% CPU issue.

* Darwin 24.4.0 arm64 arm
* Darwin 24.5.0 arm64 arm
* Linux 6.12.39-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

https://github.com/hunterwilhelm/bun-max-cpu-bug

What is the issue?

Bun will consistently use 100% when debugging.

To reproduce the issue:

```bash
bun install
```

To run the script:

#### Run the script with VSCode debugger

1. Go to Run and Debug
1. Click on the "Launch Bun Debugger" configuration

or
```bash
bun run --inspect-wait=localhost:6499/debugger --watch index.ts
# then attach to the debugger in VSCode
```
or
```bash
bun run inspect-wait
# then attach to the debugger in VSCode
```
or
```bash
bun run inspect
# then attach to the debugger in https://debug.bun.sh/#localhost:6499/debugger
```

<img width="952" height="496" alt="Image" src="https://github.com/user-attachments/assets/6ce4fdb4-3756-47ff-a52b-03517eff4000" />

### Additional information

We've seen this 100% CPU issue occur with the following items, and we believe they are all related. However, for these things, I wasn't able to create a reproducible example because the debugger also has the issue.

* WorkOS's nodejs SDK createSchema function is triggering it
* Drizzle's node-postgres when connecting to a Neon Instance, but not when connecting locally. Switching to drizzle's neon-serverless and or neon-http fixed the 100% issue on that repo.

**Comment by MatthewAry** [comment]
So I am able to see this behavior with the built-in debugger (webkit dev tools) for bun too.

**Comment by RiskyMH** [comment]
I can see that when using `debugger` for the breakpoint it uses 100% cpu. I'm assuming it's a bad way to keep it paused by keeping the cpu busy so nothing can run. Did the other cases of 100% cpu happen with breakpoint or is there just many ways it maxes out?

**Comment by hunterwilhelm** [comment]
The other cases were happening without any breakpoints. It didn't matter how I triggered the breakpoint, whether through the debugger keyword, or through the ui, they both cause 100% CPU.

However, a fix was deployed in 1.2.20: "Over-scheduling the garbage collector when idling had a serious impact on idle CPU usage."
I haven't tested to see if my other cases were fixed by this yet. I'll keep you posted.

**Comment by gregerolsson** [comment]
This was the problem for me: https://github.com/oven-sh/bun/issues/23536

Corrected in upcoming 1.3.2 via PR https://github.com/oven-sh/bun/pull/24015

I verified it by fetching a build of Bun with the PR applied and using that:

```
> bunx bun-pr 24015
> bun-24015 vite dev  # or
> bun-24015 wss.js  # from example above
```

@hunterwilhelm I run macOS 15.3.1 (24D70) (Sequoia) arm64 on a Mac Mini M4, using Bun (1.3.1+89fa0f343)

**Comment by ViktorTrojan** [comment]
> This was the problem for me: [#23536](https://github.com/oven-sh/bun/issues/23536)
> 
> Corrected in upcoming 1.3.2 via PR [#24015](https://github.com/oven-sh/bun/pull/24015)
> 
> I verified it by fetching a build of Bun with the PR applied and using that:
> 
> ```
> > bunx bun-pr 24015
> > bun-24015 vite dev  # or
> > bun-24015 wss.js  # from example above
> ```
> 
> [@hunterwilhelm](https://github.com/hunterwilhelm) I run macOS 15.3.1 (24D70) (Sequoia) arm64 on a Mac Mini M4, using Bun (1.3.1+89fa0f343)

This pr did not fix it for me. I also tried older versions as far back as "1.1.45" which also had the 100% cpu issue for me when pausing on breakpoints

**Comment by codebyafri** [comment]
Issue still persists. ESLint seems to be the worst offender.

**Comment by Jarred-Sumner** [comment]
@robobun fix this. Replace the spin loop with something more reasonable, like a condvar or maybe just bun.Waker. Push a PR.

**Comment by robobun** [comment]
🔍 Reproducing — the spin loop in `BunInspectorConnection::runWhilePaused` is the culprit. Replacing with `WTF::Condition`...
