### ISSUE TITLE
Cannot read properties of undefined (reading 'Component')

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#2958]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Bundling react project using: 
```bun build  --outdir out ./src/index.js --target browser --format esm```

Getting Cannot read properties on undefined (reading 'Component') error (when loading app in browser)
<img width="1107" alt="image" src="https://github.com/oven-sh/bun/assets/68567770/0911cffc-e26c-4b57-85ad-3d7227dde7af">

**Comment by Jarred-Sumner** [comment]
haven't managed to narrow this down yet

**Comment by samopus1io** [comment]
Let me know if we can help by providing more information or anything else. Happy to help where we can.

**Comment by Jarred-Sumner** [comment]
If you set NODE_ENV=production does it still happen

**Comment by samopus1io** [comment]
looks like it yes

**Comment by samopus1io** [comment]
tried with 0.6.7 and the issue persists.
<img width="673" alt="image" src="https://github.com/oven-sh/bun/assets/68567770/a2000acf-dc55-4225-831f-9930d4f00485">

One thing that might be helpful (or not) - our project ends up bundling multiple versions of react (due to older dependencies - we are trying to get rid of them over time). Could that be the cause of this issue?

Let me how we can help troubleshoot this. Thanks!

**Comment by atjeff** [comment]
@Jarred-Sumner are bundler bugs still in priority? This is the only remaining blocker for my team

**Comment by atjeff** [comment]
This seems to have been fixed by https://github.com/oven-sh/bun/pull/3538 and or the latest release, for me

**Comment by samopus1io** [comment]
sadly, still having the problem with .7.0

Same error but on a different component - dependency of a dependency of our project (node_modules/react-virtualized-auto-sizer/dist/react-virtualized-auto-sizer.esm.js

<img width="904" alt="image" src="https://github.com/oven-sh/bun/assets/68567770/7bc7ea92-aa67-4a78-b95a-59558064543c">

<img width="743" alt="image" src="https://github.com/oven-sh/bun/assets/68567770/ab78adc4-5604-4b10-8c74-d055654953d0">

**Comment by barisozcetin** [comment]
Having the same issue with 1.1.21

<img width="510" alt="image" src="https://github.com/user-attachments/assets/27a94b5e-d38a-4980-96f0-2d81565577c2">
<img width="645" alt="image" src="https://github.com/user-attachments/assets/7e569766-d8d4-4cd5-829f-7d202349864f">
