### ISSUE TITLE
Reading files fails with exit code 1 (SIGHUP)

### ISSUE THREAD

**Issue by johannesschaffer** [oven-sh/bun#2982]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Reading in a file, e.g. with `await Bun.file('test.text').text()`.

### What is the expected behavior?

To not exit the script and actually read in the file.

### What do you see instead?

It ends the script with exit code 1. It doesn't give any result back. It ends immediatly.

### Additional information

The only thing that works is `Bun.file().stream()`. I can read the file like that:
```javascript
const file = Bun.file(path)
const reader = await file.stream().getReader().read()
return new TextDecoder().decode(reader.value)
```
Writing works as intended.

**Comment by erikhansenal** [comment]
Same problem on Rocky Linux 9 (Linux  5.14.0-284.11.1.el9_2.x86_64). Works fine on current Manjaro (Linux 6.1.29-1-MANJARO).

Can be reproduced in a container on Manjaro as well: `podman run --rm -it  docker.io/library/rockylinux:9`.

**Comment by Hanaasagi** [comment]
Perhaps this issue has already been fixed in version 0.6.11. Here is a Dockerfile for validation:

```Dockerfile
FROM rockylinux:9

WORKDIR /app

RUN dnf -y install unzip
RUN curl -fsSL https://bun.sh/install | bash
RUN echo "file content" > "test.text"
RUN echo "console.log(await Bun.file('test.text').text())" > index.js

CMD ["/root/.bun/bin/bun", "index.js"]

```

I tested the Rocky Linux 9 container on ArchLinux 6.3.9-arch1-1, and file reading works fine.

```
>> docker build . -t bun-test && docker run bun-test
```

**Comment by redraskal** [comment]
> Perhaps this issue has already been fixed in version 0.6.11. Here is a Dockerfile for validation:
> 
> ```dockerfile
> FROM rockylinux:9
> 
> WORKDIR /app
> 
> RUN dnf -y install unzip
> RUN curl -fsSL https://bun.sh/install | bash
> RUN echo "file content" > "test.text"
> RUN echo "console.log(await Bun.file('test.text').text())" > index.js
> 
> CMD ["/root/.bun/bin/bun", "index.js"]
> ```
> 
> I tested the Rocky Linux 9 container on ArchLinux 6.3.9-arch1-1, and file reading works fine.
> 
> ```
> >> docker build . -t bun-test && docker run bun-test
> ```

I no longer experience this problem on WSL

**Comment by erikhansenal** [comment]
Still fails for me using `podman/buildah` with the same `Dockerfile`.

**Comment by honzabit** [comment]
Same here, using `oven/bun:0.6.14` docker image. The file I/O is used by a cache system that writes the file without any problems, but when trying to get the contents, the docker container fails without any application-level logs. The same code works fine on my local environment (MacOS Monterey 12.6).

**Comment by redraskal** [comment]
now fails for me on a new WSL instance (.json() also crashes)

**Comment by youmustfight** [comment]
Failing for me on AWS ECS docker containers running `oven/bun:0.7.3` when I'm trying to await `arrayBuffer()` on font files, but works fine on my local machine.

**Comment by eugene1g** [comment]
This still crashes under Bun `1.0`, inside a RHEL9 container run via Podman.
`Linux 5.14.0-284.18.1.el9_2.x86_64`

**Comment by enesflow** [comment]
Same for me with `Bun 1.0.3` on `Centos 9-Stream` `5.14.0-368.el9.x86_64`

**Comment by Electroid** [comment]
Duplicate of #6371

**Comment by johannesschaffer** [comment]
1. How is this a duplicate, if my issue here was created months earlier than the other issue?
2. Why is this closed as not planned? It's a big problem that this doesn't work

**Comment by Electroid** [comment]
> 1. How is this a duplicate, if my issue here was created months earlier than the other issue?
> 2. Why is this closed as not planned? It's a big problem that this doesn't work

For duplicate issues, we keep the one around that has the most upvotes and/or context. This sometimes means a newer issue will get kept around instead of the original one.

For the "not planned", it's an unfortunate design of GitHub's interface: "Not planned" includes "Duplicate". To be clear, we will fix this, it is indeed planned.
