### ISSUE TITLE
Bun dev command fails with SystemOudated

### ISSUE THREAD

**Issue by Assassinduck** [oven-sh/bun#307]
On Ubuntu 22.04 LTS through WSL, the bun dev command immediately fails with the error: 
`error: Failed to initialize network thread: SystemOutdated. HTTP requests will not work. Please file an issue and run strace().`

Here is the strace for the command:

`execve("/home/assassinduck/.bun/bin/bun", ["bun", "dev"], 0x7ffffe651758 /* 30 vars */) = 0
brk(NULL)                               = 0x7fdb000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fffd3f26610) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f19685f0000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=19865, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 19865, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f19685ab000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=14432, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 16424, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f19685a0000
mmap(0x7f19685a1000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f19685a1000
mmap(0x7f19685a2000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f19685a2000
mmap(0x7f19685a3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f19685a3000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=940560, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 942344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f19684b0000
mmap(0x7f19684be000, 507904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7f19684be000
mmap(0x7f196853a000, 372736, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8a000) = 0x7f196853a000
mmap(0x7f1968595000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe4000) = 0x7f1968595000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=21448, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 16424, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f19685a6000
mmap(0x7f19685a7000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f19685a7000
mmap(0x7f19685a8000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f19685a8000
mmap(0x7f19685a9000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f19685a9000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\211\303\313\205\371\345PFwdq\376\320^\304A"..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1968280000
mmap(0x7f19682a8000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f19682a8000
mmap(0x7f196843d000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7f196843d000
mmap(0x7f1968495000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7f1968495000
mmap(0x7f196849b000, 52816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f196849b000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1968270000
mmap(NULL, 339968, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1968210000
arch_prctl(ARCH_SET_FS, 0x7f1968261140) = 0
set_tid_address(0x7f1968261410)         = 2441
set_robust_list(0x7f1968261420, 24)     = 0
rseq(0x7f1968261ae0, 0x20, 0, 0x53053053) = -1 ENOSYS (Function not implemented)
mprotect(0x7f1968495000, 16384, PROT_READ) = 0
mprotect(0x7f19685a9000, 4096, PROT_READ) = 0
mprotect(0x7f1968595000, 4096, PROT_READ) = 0
mprotect(0x7f19685a3000, 4096, PROT_READ) = 0
mprotect(0x4c89000, 765952, PROT_READ)  = 0
mprotect(0x7f19685e8000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
munmap(0x7f19685ab000, 19865)           = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=711695900}) = 0
getrandom("\xf8\x5f\xc9\xc1\x5c\x79\x92\x95\xb5\x66\xa2\x10\x5d\xd7\x9f\xee\x82\x18\xd4\x88\x89\xf8\x66\x89\xa4\xf6\x7f\xe5\x8a\x37\xe7\x79", 32, GRND_NONBLOCK) = 32
openat(AT_FDCWD, "/proc/sys/vm/overcommit_memory", O_RDONLY) = 3
read(3, "0\n", 32)                      = 2
close(3)                                = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=712290800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=712366200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=712447600}) = 0
getrandom("\x93\x79\x4c\xdd\x19\x8a\x4c\x17", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x7fdb000
brk(0x7ffc000)                          = 0x7ffc000
futex(0x62f0cfc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x62f0d08, FUTEX_WAKE_PRIVATE, 2147483647) = 0
prlimit64(0, RLIMIT_STACK, {rlim_cur=12500*1024, rlim_max=12500*1024}, NULL) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGABRT, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO|0xffffffff00000000, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1657147563, tv_nsec=621909000}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, 0x7fffd3f26540)        = -1 ENOTTY (Inappropriate ioctl for device)
clock_gettime(CLOCK_REALTIME, {tv_sec=1657147563, tv_nsec=622280000}) = 0
access("/sys/devices/system/node/node1", R_OK) = -1 ENOENT (No such file or directory)
mmap(0x3c4d8000000, 67108864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x3c4d8000000
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=715698700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=715781500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=715861800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=715941100}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=716020900}) = 0
getcwd("/home/assassinduck/bun", 4096)  = 23
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=716191900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=716269900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=716349300}) = 0
openat(AT_FDCWD, "/home/assassinduck/bun/bunfig.toml", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
readlink("/home", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck/bun", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck/bun/node_modules.bun", 0x7fffd3f0e530, 1023) = -1 ENOENT (No such file or directory)
readlink("/home", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck/bun", 0x7fffd3f0e530, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/assassinduck/bun/node_modules.server.bun", 0x7fffd3f0e530, 1023) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717460400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717538300}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717616800}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=1551, tv_nsec=717702500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717788200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717870700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=717955300}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718051800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718126500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718236500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718402900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718478600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718557300}) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=64*1024, rlim_max=64*1024}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=718949200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=719135600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=719325700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=719545200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=719659100}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=719830900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720034600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720123200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720277600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720426000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720728200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=720999100}) = 0
openat(AT_FDCWD, "/home/assassinduck/bun/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 3
lseek(3, 0, SEEK_SET)                   = 0
getdents64(3, 0x7fffd3f0bd78 /* 5 entries */, 8192) = 184
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=721604300}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=721686400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=721766900}) = 0
getdents64(3, 0x7fffd3f0bd78 /* 0 entries */, 8192) = 0
openat(AT_FDCWD, "/home/assassinduck/bun", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 4
openat(4, "index.html", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/assassinduck/bun/index.html", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=722797300}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=722913000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=722995500}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=1551, tv_nsec=723195000}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=1551, tv_nsec=723284600}) = 0
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 5
lseek(5, 0, SEEK_SET)                   = 0
getdents64(5, 0x7fffd3f10180 /* 25 entries */, 8192) = 632
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=723727700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=723807800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=723887900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=723975700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=724054100}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=724131700}) = 0
getdents64(5, 0x7fffd3f10180 /* 0 entries */, 8192) = 0
openat(AT_FDCWD, "/home/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 6
lseek(6, 0, SEEK_SET)                   = 0
getdents64(6, 0x7fffd3f10180 /* 3 entries */, 8192) = 80
getdents64(6, 0x7fffd3f10180 /* 0 entries */, 8192) = 0
openat(AT_FDCWD, "/home/assassinduck/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 7
lseek(7, 0, SEEK_SET)                   = 0
getdents64(7, 0x7fffd3f10180 /* 18 entries */, 8192) = 632
getdents64(7, 0x7fffd3f10180 /* 0 entries */, 8192) = 0
openat(AT_FDCWD, "/home/assassinduck/bun/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 8
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=725473000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=725617500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=725717900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=725823600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=725923700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=726110000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=726335200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=726417800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=726491800}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1657147563, tv_nsec=633615200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=726693900}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727336400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727429700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727536200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727632000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727711700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727850000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=727976400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728135400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728343400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728453700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728536500}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728632200}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728711700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728788400}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=728953000}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=729031600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=729108700}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=729415300}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=729497100}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1551, tv_nsec=729574500}) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=64*1024, rlim_max=64*1024}) = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 9
setsockopt(9, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(9, SOL_SOCKET, SO_REUSEPORT, [0], 4) = 0
bind(9, {sa_family=AF_INET, sin_port=htons(3000), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(9, 1280)                         = 0
getsockname(9, {sa_family=AF_INET, sin_port=htons(3000), sin_addr=inet_addr("0.0.0.0")}, [128 => 16]) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1657147563, tv_nsec=638282600}) = 0
write(2, "[16.00ms] bun!! v0.1.1\n\n\n  Link:"..., 57[16.00ms] bun!! v0.1.1

  Link: http://localhost:3000

) = 57
rt_sigaction(SIGRT_1, {sa_handler=0x7f19683118f0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f19682c2520}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
mmap(NULL, 16781312, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f1967200000
mprotect(0x7f1967201000, 16777216, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f1968200910, parent_tid=0x7f1968200910, exit_signal=0, stack=0x7f1967200000, stack_size=0xfaf500, tls=0x7f1968200640}, 88) = -1 ENOSYS (Function not implemented)
clone(child_stack=0x7f19681af4f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2442], tls=0x7f1968200640, child_tidptr=0x7f1968200910) = 2442
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
accept4(9, error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
 <unfinished ...>)           = ?
+++ exited with 1 +++`

**Comment by evanwashere** [comment]
running `wsl --update` in admin powershell should fix it

**Comment by Assassinduck** [comment]
Got `No updates are available`
the Kernel version is  5.10.102.1


checked and I still get the SystemOutdated error

@evanwashere

**Comment by artokun** [comment]
make sure you also run `wsl --shutdown` after updating

**Comment by 4nkitd** [comment]
i also had same issue `wsl --update` did solve it, Thanks

**Comment by Coding-Crashkurse** [comment]
Same issue here, I tried Ubuntu 20.04 and 22.04. 
Ran apt-get upgrade && apt-get update and installed unzip.

`wsl --update` did not solve it for me

**Comment by FinnRG** [comment]
@Data-Mastery Could you please run ```wsl -l -v``` to check that you're using WSL2? If not, please update.

**Comment by Assassinduck** [comment]
i have done all of the things suggested in this thread and nothing has resolved the issue

**Comment by Assassinduck** [comment]
Setting the WSL version to 2 on the distro I was using solved the issue!
