### ISSUE TITLE
Fastify error throwing

### ISSUE THREAD

**Issue by Calemy** [oven-sh/bun#313]
```js
const fastify = require('fastify')()

fastify.listen({ port: 3000 })
console.log("Fastify API running")
```

this throws an error on behalf of the fasitfy module. i do not know if this is just a fastify issue (which works normal on node) or if this is related to bun.

![Error Screenshot](https://user-images.githubusercontent.com/45440100/177663521-bf83d60d-caff-4af9-bdc6-2b89772b2036.jpeg)

**Comment by Jarred-Sumner** [comment]
There are a number of things that need to be fixed before something like fastify will run in Bun:
- `https` / `http` module
- `tty` module
- `tls` module probably

**Comment by s1nistr4** [comment]
Can we reopen this? The error is slightly different but it still doesn't work, this time saying that the port doesn't work.

**Comment by SaadFarooq-Dev** [comment]
Current Error:

``` js
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})

// Declare a route
fastify.get('/', function (request, reply) {
  reply.send({ hello: 'world' })
})

// Run the server!
fastify.listen({ port: 4242 }, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  console.log(`Server is now listening on ${address}`)
})
```

<img width="924" alt="image" src="https://github.com/oven-sh/bun/assets/89783597/f4bcb94f-6991-4889-89fc-e5b019cd1cbc">

**Comment by sirenkovladd** [comment]
@SaadFarooq-Dev in canary it was fixed `bun upgrade --canary`
https://github.com/oven-sh/bun/pull/5689

**Comment by blankuserrr** [comment]
> @SaadFarooq-Dev in canary it was fixed `bun upgrade --canary`
> https://github.com/oven-sh/bun/pull/5689

do you know if this fix will be implemented in the next stable version of bun?

**Comment by Electroid** [comment]
This has been fixed as of Bun v1.0.7.

```
❯ bun fastify.js
Fastify API running
```

```
❯ bun fastify.js
{"level":30,"time":1698182897573,"pid":5274,"hostname":"...","msg":"Server listening at http://[::1]:4242"}
{"level":30,"time":1698182897577,"pid":5274,"hostname":"...","msg":"Server listening at http://127.0.0.1:4242"}
Server is now listening on http://[::1]:4242
```

If you run into the same problem, please feel free to re-open this issue.

**Comment by IbrahimOwner2020** [comment]
![Screenshot 2024-07-04 at 14 04 45](https://github.com/oven-sh/bun/assets/65255510/efab1993-6ba9-4373-b10e-e3de9c102703)

Still getting the error on bun v 1.1.17 any solutions
