### ISSUE TITLE
Bun.spawnSync crash within Bun.serve fetch

### ISSUE THREAD

**Issue by patlux** [oven-sh/bun#3480]
### What version of Bun is running?

0.6.12

### What steps can reproduce the bug?

```tsx
// index.ts
Bun.serve({
  fetch(req: Request) {
    Bun.spawnSync(["echo"])
    return new Response(`<meta charset="UTF-8">
    <h1>Hello World from bun 🤩</h1>
    `, {
        headers: {
            'Content-Type': 'text/html',
        }
    });
  },
  error(error: Error) {
    return new Response("Uh oh!!\n" + error.toString(), { status: 500 });
  },
  port: 1337
})

console.log("Bun is cool!")
```

```sh
bun run index.ts
```

https://codedamn.com/playground/DdxMhLbxgZxzHhn6SJYfD

### What is the expected behavior?

Should work

### What do you see instead?

Crash:

```
Bun is cool!
Error: Cork buffer must not be held across event loop iterations!

uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.6.11 (2eb885c1) Linux x64 #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022
RunCommand: 
Elapsed: 3088ms | User: 3ms | Sys: 9ms
RSS: 33.55MB | Peak: 35.20MB | Commit: 33.55MB | Faults: 7
----- bun meta -----

0   0x5621907ef2bb

Crash report saved to:
  ~.bun-crash/v0.6.11-1688200263609.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

[1]    144 abort (core dumped)  bun run index.ts
```

### Additional information

`Bun.spawn` works.

**Comment by v3nntrnx** [comment]
I can check what's wrong with it

*Updates*:
Output of debug build of bun: <https://hastebin.skyra.pw/tanikovoga.csharp>
The error comes from uws(?, src/deps/uws/src/Loop.h Line 64)

**Comment by v3nntrnx** [comment]
you said you're on 0.6.12, but in the crash message it says bun v0.6.11, it does happen on v0.6.12 but still.

Next time you report errors be 100% sure that the version is correct

**Comment by patlux** [comment]
> you said you're on 0.6.12, but in the crash message it says bun v0.6.11, it does happen on v0.6.12 but still.
> 
> Next time you report errors be 100% sure that the version is correct

i tested all versions beginning from 0.6.0 and non works. So it doesn’t matter. Locally it was 0.6.12 initially and the crash log is from the linked playground so you can reproduce it easily. Thanks.

**Comment by Jarred-Sumner** [comment]
> Next time you report errors be 100% sure that the version is correct

This is rude

> i tested all versions beginning from 0.6.0 and non works. So it doesn’t matter. Locally it was 0.6.12 initially and the crash log is from the linked playground so you can reproduce it easily. Thanks.

I suspect the cause is re-entrant event loop. We dispatch HTTP requests skipping the ordinary task queue. Will be tricky to fix.

**Comment by Jarred-Sumner** [comment]
@patlux as a temporary workaround, can you use Bun.spawn() and await the exited value?

**Comment by patlux** [comment]
@Jarred-Sumner Yes, already using it :) Thank you!

**Comment by v3nntrnx** [comment]
> This is rude


I didn't mean it to be rude, sorry if it did sound rude.

**Comment by W2Wizard** [comment]
Got the same issue, was able to "fix" it by just `await req.json()` before running a process.

**Comment by janwilmake** [comment]
Having this issue too when using HTMLRewriter in a Bun.serve

**Comment by JonnyBurger** [comment]
Reproduction for Bun 1.0.1:

1. repro.ts
```ts
Bun.serve({
  port: 8080,
  fetch: (req, res) => {
    const aha = Bun.spawnSync(["nproc"], {});
    return new Response("Hello world!");
  },
});
```

2.
```
bun repro.ts
```

3. Open http://localhost:8080 in browser

Should repro on any OS (linux / macos)

**Comment by arno-fukuda** [comment]
same

**Comment by JonnyBurger** [comment]
It has been fixed in 1.0.3! Verified with both my and @patlux's repro.

Thank you 🙏

**Comment by shiny** [comment]
> It has been fixed in 1.0.3! Verified with both my and @patlux's repro.
> 
> Thank you 🙏

The code above still have a core dump error
> Trace/breakpoint trap (core dumped)

Bun veriosn: 1.0.8

```typescript
Bun.serve({
    port: 8080,
    async fetch(req) {
        const proc = Bun.spawn(["echo", "hello"])
        await proc.exited
        return new Response(proc.stdout)
    },
});
```

**Comment by Jarred-Sumner** [comment]
> > It has been fixed in 1.0.3! Verified with both my and @patlux's repro.
> > Thank you 🙏
> 
> The code above still have a core dump error
> 
> > Trace/breakpoint trap (core dumped)
> 
> Bun veriosn: 1.0.8
> 
> ```ts
> Bun.serve({
>     port: 8080,
>     async fetch(req) {
>         const proc = Bun.spawn(["echo", "hello"])
>         await proc.exited
>         return new Response(proc.stdout)
>     },
> });
> ```

Please open another issue for this. It is a different bug with a different fix
The specific bug is here: https://github.com/oven-sh/bun/blob/c425949a3ae36e5c12ce6ed660ae79a5ff1c72f6/src/bun.js/api/server.zig#L2698

`File` can happen when it is from a ReadableStream that was created via `Bun.spawn`.

<img width="1117" alt="image" src="https://github.com/oven-sh/bun/assets/709451/17972417-6a49-44dd-9590-686e1191e1a6">
