### ISSUE TITLE
`bun x` throws `error: unrecognised dependency format`

### ISSUE THREAD

**Issue by james-elicx** [oven-sh/bun#3675]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run the following in your terminal window, using a custom registry's url instead of a package from npm.

```sh
bun x https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386
```

### What is the expected behavior?

It should install and execute the package from the provided web address.

When you run it with `npx` instead of `bun x`, everything works as expected - it will install and execute the package.

```sh
$ npx https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386
⚡️ @cloudflare/next-on-pages CLI v.0.0.0-77f3b08 (prerelease for PR #386)

...
```

### What do you see instead?

```
error: unrecognised dependency format: https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386
```

**Comment by Jarred-Sumner** [comment]
This should be fixed as of Bun v1.0.3

**Comment by james-elicx** [comment]
> This should be fixed as of Bun v1.0.3

Still happening in 1.0.4

![image](https://github.com/oven-sh/bun/assets/10815538/bbc5ea7a-319c-4da8-a6f4-5e3f28435297)

**Comment by Jarred-Sumner** [comment]
oh you're doing `bun x` i see

**Comment by james-elicx** [comment]
Ah I didn't know there was a difference with how `bun x` and `bunx` treat it. Interestingly, `bunx` results in a different error.

![image](https://github.com/oven-sh/bun/assets/10815538/417b93d7-73db-4ce8-8634-ffb1ecd3a38e)

**Comment by btakita** [comment]
I also get a loading error when running `bun -b astro dev`. It seems like the problem occurs when invoking a subprocess which requires a '.node' file, as running `bun` directly on the source file does not cause the error.

```
1:24:42 AM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
../../node_modules/@resvg/resvg-js/js-binding.js:1:3269: ERROR: No loader is configured for ".node" files: ../../node_modules/@resvg/resvg-js-linux-x64-musl/resvgjs.linux-x64-musl.node
../../node_modules/@resvg/resvg-js/js-binding.js:1:3501: ERROR: No loader is configured for ".node" files: ../../node_modules/@resvg/resvg-js-linux-x64-gnu/resvgjs.linux-x64-gnu.node
    at failureErrorWithLog (/home/brian/work/btakita/btakita-dev/node_modules/vite/node_modules/esbuild/lib/main.js:1649:17)
    at <anonymous> (/home/brian/work/btakita/btakita-dev/node_modules/vite/node_modules/esbuild/lib/main.js:1058:17)
    at <anonymous> (/home/brian/work/btakita/btakita-dev/node_modules/vite/node_modules/esbuild/lib/main.js:1525:9)
    at processTicksAndRejections (:55:77)
```

**Comment by itea-dev** [comment]
This bug can be reproduced on bun 1.3.1. On node it seems to work as it fails with a 404 error.

Bun / Bunx
```sh
error: unrecognised dependency format: @https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386
```

Npx
```sh
npm error code E404
npm error 404 Not Found - GET https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386
npm error 404
npm error 404  The requested resource 'https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/5592910039/npm-package-next-on-pages-386' could not be found or you do not have permission to access it.
npm error 404 This package name is not valid, because 
npm error 404  1. name can only contain URL-friendly characters
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/bun/.npm/_logs/[DATE-TIME]-debug-0.log

```
