### ISSUE TITLE
Bun global types not being recognized on VsCode

### ISSUE THREAD

**Issue by brunoeduardodev** [oven-sh/bun#4586]
### What version of Bun is running?

1.0.0

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

1- Create a folder
2- run "bun init"
3- open vscode at the folder
4- go to index.ts

The following error will appear:
Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.ts(2584)

### What is the expected behavior?

Bun globals should be recognized

### What do you see instead?

Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.ts(2584)

### Additional information

from some messing around, it seems to be related to this commit:

https://github.com/oven-sh/bun/commit/4360ec83b4146e15344b304573795f084f86a7c2#diff-a65d88ebc29ed6f4f501937676ec79db7c7b9a3ccf9e04e04ac0fbf83d4f8549

where it's importing node:lts

![image](https://github.com/oven-sh/bun/assets/50559336/fd44c1a2-da1f-4013-aba2-ae33ef3b883c)

commenting this line, and where it references tls is making vscode recognize bun globals again

discord thread:
https://discord.com/channels/876711213126520882/1149718098904096878

**Comment by chungweileong94** [comment]
Apparently it can't to install the `bun-types` properly.
![image](https://github.com/oven-sh/bun/assets/15154097/922182c5-27a1-43c7-85cd-da34fe030734)

**Comment by Electroid** [comment]
This is now fixed, if you update `bun-types` it should be fixed.

**Comment by chungweileong94** [comment]
So apparently it doesn't seem to work for me, and turns out there's a bug while installing deps on external drive, #362

**Comment by ralcorta** [comment]
**I leave this comment for those who came here and still have the same problem even in newer versions of bun.**

What I did was update the version of Typescript that vscode uses to read the .ts files from your project's workspace. Previously I had it in `4.6.*` and I solved it by changing it to the last one installed in the project under the devDependency of the package.json, in my case `5.2.2`.

I followed this guide that I found in a stackoverflow answer that explains very well how to change it:
[https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it#:~:text=Changing%20the%20local%20TypeScript%20version](https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it#:~:text=Changing%20the%20local%20TypeScript%20version)

**In summary, what he says there is the following: (adapted to bun)**

1. Open the project in VS Code
2. Install the desired TypeScript version locally, for example `bun install -d typescript@latest`
3. The -d will update your project's package.json, adding the TypeScript version you installed as a devDependency.
4. Open VS Code Workspace Settings (F1 > Open Workspace Settings)
5. Update/Insert `typescript.tsdk`: `./node_modules/typescript/lib`
6. Now only the project you installed this TypeScript version in will use that TypeScript version, the global installation will be ignored by VS Code in this project.
7. Having added the typescript.tsdk entry it's then also necessary to use the VS Code UI to select the new version:

 - Click on the version displayed in the VS Code footer:
![image](https://github.com/oven-sh/bun/assets/19806540/8b7fc9a1-87cf-49f8-a7f1-5156ecb1bb0d)
 - Select it in the UI: 
![image](https://github.com/oven-sh/bun/assets/19806540/99ba7d64-a330-4444-bda1-a7a272e09d26)

I hope it helps you if you have this problem!
