### ISSUE TITLE
Bun & Docker issue

### ISSUE THREAD

**Issue by acmacalister** [oven-sh/bun#4723]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create a new SvelteKit app as outlined in the docs: https://bun.sh/guides/ecosystem/sveltekit

Create a `Dockerfile` like so:

```docker
FROM oven/bun:1.0

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY . .

# start app
CMD ["bun", "run", "dev"]
```

Create a `docker-compose.yml` for convenience:

```yaml
version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
``` 

Start the environment with `docker-compose up`

### What is the expected behavior?

Running in a docker container shouldn't produce errors, just like when you run it on the host machine. tldr, it works fine on the host but fails in a Dockerized environment with file descriptor issues.

### What do you see instead?

```bash
docker-compose up
[+] Running 1/1
 ⠿ Container my-app-ui-1  Recreated                                                                         0.5s
Attaching to my-app-ui-1
my-app-ui-1  | $ vite dev --host
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /app): [EBADF] Bad file descriptor
my-app-ui-1  | undefined
my-app-ui-1  |    code: "EBADF"
my-app-ui-1  |  syscall: "fstat"
my-app-ui-1  |    errno: -9
my-app-ui-1  | 
my-app-ui-1  | 
my-app-ui-1  |   VITE v4.4.9  ready in 711 ms
my-app-ui-1  | 
my-app-ui-1  |   ➜  Local:   http://localhost:5173/
my-app-ui-1  |   ➜  Network: http://172.20.0.2:5173/
```

It appears to be have file descriptor errors trying to load a PostCSS config. I'm investigating where this comes from, but not familiar with SvelteKit/Vite generation of those files.

**Comment by matt8707** [comment]
Seeing this as well, only `RUN bun run build` fails, if building locally (macos) and copying that in Dockerfile, the production server starts up fine.

**Comment by egidiusmengelberg** [comment]
Having the same issue with building nuxt in docker using bun.

**Comment by PierrePerrin** [comment]
I also have the same issue with Next.js in a Docker environment.

**Comment by egidiusmengelberg** [comment]
Bun v1.0.1 does not fix the issue.

**Comment by patrickelectric** [comment]
Having the same issue here, macos running bun in a docker

**Comment by onionhammer** [comment]
Same with astro in docker on Mac M2

**Comment by xmlking** [comment]
same issue with turbo build

**Comment by AndreasPB** [comment]
Having same issue on M1 Mac

**Comment by pdigre** [comment]
oven/bun:1.0.2 on M2, I removed all dependencies on TailwindCSS and PostCSS, but still get the same exact error. The same Dockerfile builds and deploys ok on Google Cloud Run.

**Comment by Maclay74** [comment]
Tried 1.0.3, still the same.

**Comment by itsyoboieltr** [comment]
The same happened to me with SolidStart, trying to build with Bun in a docker container.

**Comment by subtosharki** [comment]
same issue here on mac m2

**Comment by itsyoboieltr** [comment]
@Jarred-Sumner you can also run docker compose up in this repository to reproduce the bug on m1/m2 macs
https://github.com/itsyoboieltr/dbest-stack

**Comment by itsyoboieltr** [comment]
Btw, I believe this is an issue with Bun supporting Vite/Rollup, as Astro, Nuxt, SvelteKit, SolidStart are all using it under the hood, and the cause of the errors seem to be originating from there.

**Comment by Maclay74** [comment]
Checked 1.0.4, still doesn't work.

**Comment by neoReuters** [comment]
Yep, this is still an ongoing issue - tried my hand at debugging but no luck. From a fresh `bun create vite` - created a React app with Typescript & swc enabled - all I've attempted to do is add the application as a Docker container and it gets this error here.

**Comment by 81reap** [comment]
I seem to be having a similar issue with Astro and Bun inside a Docker container.

```Dockerfile
# https://docs.astro.build/en/recipes/bun/
FROM oven/bun:1.0.4
WORKDIR /home/bun/app

ENV HOST=0.0.0.0
ENV PORT=4321

COPY . . 
RUN bun install

# vv lines in question vv
RUN mkdir -p /root/.config 
RUN bun run astro telemetry disable
# ^^ lines in question ^^

RUN bunx --bun astro build

EXPOSE 4321
CMD bunx --bun ./dist/server/entry.mjs
```

I used to get a similar stack trace as y'all but these two things helped me move further, but not quite out of the woods yet.
- Without `/root/.config`, Telemery on ::
```
docker build --no-cache -t astro . && docker run -it astro /bin/sh

[+] Building 11.0s (10/10) FINISHED                                                                                                                                                        docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 106B                                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 475B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/oven/bun:1.0.4                                                                                                                                                  0.6s
 => [1/6] FROM docker.io/oven/bun:1.0.4@sha256:61c1da6a46c312befcc4f01beb17e3e9ee80b072fb965cf03f462ef58fd00e20                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 6.13kB                                                                                                                                                                        0.0s
 => CACHED [2/6] WORKDIR /home/bun/app                                                                                                                                                                     0.0s
 => [3/6] RUN mkdir -p /home/bun/.config                                                                                                                                                                   0.2s
 => [4/6] COPY . .                                                                                                                                                                                         0.0s
 => [5/6] RUN bun install                                                                                                                                                                                  9.5s
 => ERROR [6/6] RUN bunx --bun astro build                                                                                                                                                                 0.6s
------
 > [6/6] RUN bunx --bun astro build:
0.558  error   Bad file descriptor
------
Dockerfile:15
--------------------
  13 |
  14 |     # RUN bun run astro telemetry disable
  15 | >>> RUN bunx --bun astro build
  16 |
  17 |     EXPOSE 4321
--------------------
ERROR: failed to solve: process "/bin/sh -c bunx --bun astro build" did not complete successfully: exit code: 1
```
- With `/root/.config`, Telemetry on :: 
```
docker build --no-cache -t astro . && docker run -it astro /bin/sh

[+] Building 11.8s (11/11) FINISHED                                                                                                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 474B                                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 106B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/oven/bun:1.0.4                                                                                                                                                  0.5s
 => [1/7] FROM docker.io/oven/bun:1.0.4@sha256:61c1da6a46c312befcc4f01beb17e3e9ee80b072fb965cf03f462ef58fd00e20                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 6.13kB                                                                                                                                                                        0.0s
 => CACHED [2/7] WORKDIR /home/bun/app                                                                                                                                                                     0.0s
 => [3/7] RUN mkdir -p /root/.config                                                                                                                                                                       0.2s
 => [4/7] RUN mkdir -p /home/bun/.config                                                                                                                                                                   0.1s
 => [5/7] COPY . .                                                                                                                                                                                         0.0s
 => [6/7] RUN bun install                                                                                                                                                                                  9.4s
 => ERROR [7/7] RUN bunx --bun astro build                                                                                                                                                                 1.6s
------
 > [7/7] RUN bunx --bun astro build:
0.578   ◆ Astro collects completely anonymous usage data.
0.578     This optional program helps shape our roadmap.
0.578     Run `yarn run astro telemetry disable` to opt-out.
0.578     Details: https://astro.build/telemetry
0.578
1.176 ENOENT: No such file or directory
1.176  syscall: "stat"
1.176    errno: -2
1.176
1.205 Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app): [EBADF] Bad file descriptor
1.205 undefined
1.205    code: "EBADF"
1.205  syscall: "fstat"
1.205    errno: -9
1.205
1.205 Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app): [EBADF] Bad file descriptor
1.205 undefined
1.205    code: "EBADF"
1.205  syscall: "fstat"
1.205    errno: -9
1.205
1.205 Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app): [EBADF] Bad file descriptor
1.205 undefined
1.205    code: "EBADF"
1.205  syscall: "fstat"
1.205    errno: -9
1.205
1.205 Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app): [EBADF] Bad file descriptor
1.205 undefined
1.205    code: "EBADF"
1.205  syscall: "fstat"
1.205    errno: -9
1.206
1.516  error   No such file or directory
------
Dockerfile:15
--------------------
  13 |
  14 |     # RUN bun run astro telemetry disable
  15 | >>> RUN bunx --bun astro build
  16 |
  17 |     EXPOSE 4321
--------------------
ERROR: failed to solve: process "/bin/sh -c bunx --bun astro build" did not complete successfully: exit code: 1
```
- With `/root/.config`, Telemery off ::
```

[+] Building 10.4s (12/12) FINISHED                                                                                                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 472B                                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 106B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/oven/bun:1.0.4                                                                                                                                                  0.4s
 => [1/8] FROM docker.io/oven/bun:1.0.4@sha256:61c1da6a46c312befcc4f01beb17e3e9ee80b072fb965cf03f462ef58fd00e20                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 6.13kB                                                                                                                                                                        0.0s
 => CACHED [2/8] WORKDIR /home/bun/app                                                                                                                                                                     0.0s
 => [3/8] RUN mkdir -p /root/.config                                                                                                                                                                       0.2s
 => [4/8] RUN mkdir -p /home/bun/.config                                                                                                                                                                   0.1s
 => [5/8] COPY . .                                                                                                                                                                                         0.0s
 => [6/8] RUN bun install                                                                                                                                                                                  8.0s
 => [7/8] RUN bun run astro telemetry disable                                                                                                                                                              0.6s
 => ERROR [8/8] RUN bunx --bun astro build                                                                                                                                                                 1.0s
------
 > [8/8] RUN bunx --bun astro build:
0.946 ENOENT: No such file or directory
0.946  syscall: "stat"
0.946    errno: -2
0.946
0.970  error   No such file or directory
------
Dockerfile:15
--------------------
  13 |
  14 |     RUN bun run astro telemetry disable
  15 | >>> RUN bunx --bun astro build
  16 |
  17 |     EXPOSE 4321
--------------------
ERROR: failed to solve: process "/bin/sh -c bunx --bun astro build" did not complete successfully: exit code: 1
```

I think the issue may be with systems like Astro trying to save and access system files that do not exist in the default bun Container. Also notably, while I do use Tailwind CSS, [the template I use](https://github.com/eliancodes/brutal) does not have a PostCSS config?

**Comment by lucianoratamero** [comment]
same here, with sveltekit too. I tried with all variations of the docker image, so it seems to be a common problem between all of them.

**Comment by rotu** [comment]
The bun docker image also gives me this problem on MacOS, but using a `node` base image and installing via `npm` seems to work alright for me:

```dockerfile
FROM --platform=$BUILDPLATFORM docker.io/library/node:current
RUN npm install --global bun
```

**Comment by neoReuters** [comment]
@acmacalister I would suggest changing the title of this issue to something more generic - I don't think it's a sveltekit specific problem. It actually seems to be a `vite build` problem with the bun Docker images, from what I can tell.

**Comment by 81reap** [comment]
Expanding on @rotu's fix, here's what I'm doing now. It works on my M1 mac and should also work on x86.
```
FROM node:alpine
WORKDIR /app

# Install the correct glibc to run Bun
RUN if [[ $(uname -m) == "aarch64" ]] ; \
    then \
    # aarch64
    wget https://raw.githubusercontent.com/squishyu/alpine-pkg-glibc-aarch64-bin/master/glibc-2.26-r1.apk ; \
    apk add --no-cache --allow-untrusted --force-overwrite glibc-2.26-r1.apk ; \
    rm glibc-2.26-r1.apk ; \
    else \
    # x86_64
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk ; \
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub ; \
    apk add --no-cache --force-overwrite glibc-2.28-r0.apk ; \
    rm glibc-2.28-r0.apk ; \
    fi
RUN npm install -g bun

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321

COPY . . 
RUN bun install

RUN bun run astro telemetry disable
RUN bunx --bun astro build
```

**Comment by Maclay74** [comment]
Checked on 1.0.5, the issue still there.

**Comment by komiljonmaksudov** [comment]
sadly the same issue on 1.0.6

**Comment by lafllamme** [comment]
Same issue here. Any updates on this? Running Docker on M1 Pro with oven/bun:debian image

```
root@49d95c5b2930:/home/bun/app/vue3# bun run dev
$ vite
Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9


  VITE v4.4.11  ready in 790 ms

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.22.0.2:8080/
  ➜  press h to show help
EBADF: Bad file descriptor
    at writeFileSync (native)
    at runOptimizeDeps (/home/bun/app/vue3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:45813:58)
    at <anonymous> (/home/bun/app/vue3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:45192:20)
    at processTicksAndRejections (:55:39)
error: script "dev" exited with code 1 (SIGHUP)
root@49d95c5b2930:/home/bun/app/vue3# bun run dev
$ vite
Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9

Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/bun/app/vue3): [EBADF] Bad file descriptor
undefined
   code: "EBADF"
 syscall: "fstat"
   errno: -9


  VITE v4.4.11  ready in 700 ms

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.22.0.2:8080/
  ➜  press h to show help
EBADF: Bad file descriptor
    at writeFileSync (native)
    at runOptimizeDeps (/home/bun/app/vue3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:45813:58)
    at <anonymous> (/home/bun/app/vue3/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:45192:20)
    at processTicksAndRejections (:55:39)
error: script "dev" exited with code 1 (SIGHUP)
root@49d95c5b2930:/home/bun/app/vue3# 

```

**Comment by rotu** [comment]
@lafllamme as far as I can tell, using `npm install bun` is the best approach for now:
https://github.com/oven-sh/bun/issues/4723#issuecomment-1752381407
On alpine, you need to install `glibc` as well:
https://github.com/oven-sh/bun/issues/4723#issuecomment-1754014023

**Comment by janswist** [comment]
I have similar issue: https://github.com/oven-sh/bun/issues/6666 Error is still not resolved and, in fact, so evil it has only sixes in the issue number

**Comment by jabarihunt** [comment]
Same issue here on bun 1.0.7.  Also running...

- SvelteKit 1.20.4
- Vite 4.1.4
- Tailwind 3.3.3
- Postcss 8.4.28

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.0.10. It will release later tonight, but in the meantime, run `bun upgrade --canary`

**Comment by pouryapb** [comment]
1.1.3 this error still persists

**Comment by pouryapb** [comment]
1.1.3 and I am still getting this error

EDIT:
nvm, I changed extension of postcss.config from cts to cjs and it worked.
