### ISSUE TITLE
RedirectURLTooLong downloading package manifest

### ISSUE THREAD

**Issue by cjsewell** [oven-sh/bun#4748]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

Using a private [Artifact Registry in Google cloud](https://cloud.google.com/artifact-registry/docs/nodejs/manage-packages) I get the error 

```
error: RedirectURLTooLong downloading package manifest @my-namespace/my-package
```

### What is the expected behavior?

Bun to install the packages

### What do you see instead?

The verbose log is:
```
  🔍 @my-namespace/my-package [415/416] Response: < 307 Temporary Redirect
<       Content-Type: text/html; charset=utf-8
<       Location: /artifacts-downloads/namespaces/my-package/repositories/npm/downloads/some-long-hash
<       X-Content-Type-Options: nosniff
<       X-Frame-Options: SAMEORIGIN
<       X-Xss-Protection: 0
<       Date: Sun, 10 Sep 2023 00:34:43 GMT
<       Transfer-Encoding: chunked
<       Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

Note the Location path is 6000+ characters long.

**Comment by Electroid** [comment]
Thanks for reporting this bug!

It looks like the URL to download the manifest is larger than `4096` bytes.

https://github.com/oven-sh/bun/blob/620f6c51cec26dcb2df24af52f9140932467244f/src/http_client_async.zig#L36

https://github.com/oven-sh/bun/blob/620f6c51cec26dcb2df24af52f9140932467244f/src/http_client_async.zig#L3408-L3419

We'll need to fix this code so it can handle cases where the URL is above that buffer limit.

**Comment by hemantai1101** [comment]
same issue for me when trying to connect to my npm registry on gcp artifact registry.

**Comment by montoyaaguirre** [comment]
@hemantai1101  I'm facing the same issue. 
By the way, did you manage to connect without explicitly adding the token? At the moment my config is:
```
[install.scopes]
# registry as string
"@myorg" = { token = "XXXX", url = "myArtifactUrl"}
```
On yarn, I don't need to provide a token as long as I do `gcloud auth login`

**Comment by hemantai1101** [comment]
> @hemantai1101 I'm facing the same issue. By the way, did you manage to connect without explicitly adding the token? At the moment my config is:
> 
> ```
> [install.scopes]
> # registry as string
> "@myorg" = { token = "XXXX", url = "myArtifactUrl"}
> ```
> 
> On yarn, I don't need to provide a token as long as I do `gcloud auth login`

nope i think the problem is not authorising to the registry but when bun tries to pull it.

but i also tested what you suggested. and yes bun reads auth from `bunfig.toml`
without the token`bun install` just return `forbidden`

**Comment by cjsewell** [comment]
No, I manually added the token. I believe gcloud just inserts the token in to ~/.npmrc for you. So gcloud would have to support bun in the same way unless #643 gets fixed of course.

I ran in to the auth issue when updating to yarn 2 as it doesn't read .npmrc either.
I didn't want to update yarnrc.yml manually every time my token expired. To work around this I created a a service account token which doesn't expire for use in yarrnc.yml. Same token works for bun but I'm hoping #643 will make it a non issue

**Comment by cjsewell** [comment]
FYI I don't _think_ auth is related to this issue.

Just seems Google decided to make their urls far larger than bun expects

**Comment by ggobbe** [comment]
This issue can be closed, it was fixed with the `1.0.3` release

**Comment by Electroid** [comment]
That was a temporary fix, this issue could still persist if the string was long enough.

**Comment by cjsewell** [comment]
Nice! Works on my machine
