### ISSUE TITLE
amqplib not connecting in Bun

### ISSUE THREAD

**Issue by Indicardo** [oven-sh/bun#4791]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

Install the latest version of amqplib and run this code snippet. In my case I'm also running a RabbitMQ server locally:

```
import amqplib from "amqplib";

(async () => {
  await amqplib.connect("amqp://localhost");
  console.log("Connected");
})();

``` 

### What is the expected behavior?

```
$ ts-node index.ts
Connected
```

### What do you see instead?

```
$ bun index.ts    
[0.49ms] ".env"
SystemError: Failed to connect
 syscall: "connect"
 ```

**Comment by jmezo** [comment]
I get the same error trying to connect to a local postgres instance using the [pg](https://www.npmjs.com/package/pg) package. Same platform.
```ts
import { Client } from "pg";

const connectionString = "postgres://postgres:postgres@localhost:5432/postgres";
const database = new Client({ connectionString });
await database.connect();
```

I ran the above code on a different platform (6.2.10-arch1-1 x86_64) and it works without any issues.

**Comment by daniel-habib** [comment]
for what's it worth:
bun 1.0.3
on macos 13.4.1 arm

this works:
```js
import amqplib from "amqplib";
 
(async () => {
  await amqplib.connect("amqp://guest:guest@localhost");
  console.log("Connected");
})();
```

**Comment by Electroid** [comment]
Between Bun v1.0 and v1.0.7, we've made a lot of fixes to TCP/TLS connections. The "Failed to connect" errors should be fixed. If you are still experiencing this error, after upgrading, please re-open this issue and we'll investigate.

**Comment by AlexRobinson66** [comment]
@Electroid, thank you for the update, unfortuantely even after upgrading to v1.0.7 this issue remains. :-( 

Are you able to reopen? (I'm unable to)

**Comment by tkovis** [comment]
> I get the same error trying to connect to a local postgres instance using the [pg](https://www.npmjs.com/package/pg) package. Same platform.
> 
> ```ts
> import { Client } from "pg";
> 
> const connectionString = "postgres://postgres:postgres@localhost:5432/postgres";
> const database = new Client({ connectionString });
> await database.connect();
> ```
> 
> I ran the above code on a different platform (6.2.10-arch1-1 x86_64) and it works without any issues.

macOS Sonoma 14.1, similar issue with Bun v1.0.7 and v1.0.9 when using localhost as host

```
const pool = new Pool(options);
pool.connect();
// ECONNREFUSED: Failed to connect
// syscall: "connect"
```

works if I use "127.0.0.1" instead of localhost

**Comment by coppy-team** [comment]
Also see the same issue when connecting to local PostgreSQL with `pg` with bun `1.0.21`. Works fine when I run it locally on MacOS Ventura, but fails when I run the same code on GitHub actions runner (latest Ubuntu). Also, the same connection works, if I run it with node (both locally on MacOS and on Ubuntu runner).

Tried to use `localhost` and `127.0.0.1` but neither worked.
```
ECONNREFUSED: Failed to connect
syscall: "connect"
```

**Comment by coppy-team** [comment]
Was tryin got migrate to the `Postgres.js` from `pg`. But have the same issue: everything works fine either with bun on MacOS or with node on both MacOS and GitHub Actions Ubuntu runner. But when I try to connect with bun on Ubuntu, I get an error:
```
ECONNREFUSED: Failed to connect
syscall: "connect"
```

**Comment by futpib** [comment]
This has to be related to IPv6 cause `localhost` and `::1` do not work for me but `127.0.0.1` does.

**Comment by Bidek56** [comment]
Using `rhea` I end up with a similar [issue](https://github.com/amqp/rhea/issues/416)

**Comment by rperello** [comment]
bun 1.1.0
macos Sonoma 14.4.1 arm

I confirm localhost does raise the mentioned error. Using 127.0.0.1 does work

**Comment by Bidek56** [comment]
Maybe I am missing something, but this simple code does not work with ActiveMQ Artemis local docker image.
```
var container = require('rhea');

const connection = container.connect({
    port: 5672, // AMQP port (default is 5672)
    host: '127.0.0.1', // ActiveMQ broker hostname or IP address
    username: 'artemis',
    password: 'artemis'
});

// Handle events (e.g., message handling, error handling) on the connection
// For example:
connection.on('message', (context) => {
    console.log('Received message:', context.message.body);
});

// Open a sender or receiver (based on your use case)
// For example:
const sender = connection.open_sender('my_queue');
sender.on('sendable', (context) => {
    const message = { body: 'Hello from Rhea!' };
    sender.send(message);
});
```
it throws `[connection-1] disconnected` on the bun side
it throws `ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) on acceptor "amqp" during protocol handshake with /192.168.10.1:56123 has occurred.` on the ActiveMq side.

**Comment by nektro** [comment]
this is now fixed as of [Bun 1.1.9](https://bun.sh/blog/bun-v1.1.9#improved-ipv4-ipv6-vpn-connectivity)

**Comment by Jarred-Sumner** [comment]
The DNS issue preventing ampqlib from connecting over localhost was fixed in Bun v1.1.9. The invalid frame / data being sent is being tracked separately in #5627. Please follow along in #5627

**Comment by maxime-aubry** [comment]
Hello.

I have the same issue with Bun 1.1.29 and Docker on WSL.

``` Powerhell
auth-1    | [Nest] 8  - 10/09/2024, 7:16:44 AM   ERROR [Server] Connection to transport failed. Trying to reconnect...
auth-1    | [Nest] 8  - 10/09/2024, 7:16:44 AM   ERROR [Server] ECONNREFUSED: Failed to connect
```

**Comment by mrcaidev** [comment]
Connection is still failing when the hostname is a Docker container name, e.g. `amqp://rabbitmq:rabbitmq@rabbitmq:5672`.

**Comment by Bidek56** [comment]
Is anyone able to get [this](https://github.com/oven-sh/bun/issues/4791#issuecomment-2066903999) example working?

**Comment by soknifedev** [comment]
I'm using rascal and it connects but crash regularly.


To reproduce: create a rascal client connection and create 'subscription' to a queue, then receive some messages, the entire bun process crash. 
```

364 |   }
365 | }
366 | 
367 | function error (stream, err) {
368 |   setImmediate(() => {
369 |     stream.emit('error', err)
                 ^
error: the worker has exited
      at emitError (node:events:47:13)
      at <anonymous> (/Users/..../node_modules/thread-stream/index.js:369:12)
error: script "dev" exited with code 1

```

**Comment by soknifedev** [comment]
I'm using rascal and it connects but crash regularly.


To reproduce: create a rascal client connection and create 'subscription' to a queue, then receive some messages, the entire bun process crash. 
```

364 |   }
365 | }
366 | 
367 | function error (stream, err) {
368 |   setImmediate(() => {
369 |     stream.emit('error', err)
                 ^
error: the worker has exited
      at emitError (node:events:47:13)
      at <anonymous> (/Users/..../node_modules/thread-stream/index.js:369:12)
error: script "dev" exited with code 1

```

Sometimes, another error before crashing appears :
```

364 |   }
365 | }
366 | 
367 | function error (stream, err) {
368 |   setImmediate(() => {
369 |     stream.emit('error', err)
                 ^
TypeError: destination.write is not a function. (In 'destination.write(toWrite)', 'destination.write' is undefined)
      at emitError (node:events:47:13)
      at <anonymous> (/Users/.../node_modules/thread-stream/index.js:369:12)
```

**Comment by kravetsone** [comment]
> I'm using rascal and it connects but crash regularly.
> 
> 
> To reproduce: create a rascal client connection and create 'subscription' to a queue, then receive some messages, the entire bun process crash. 
> ```
> 
> 364 |   }
> 365 | }
> 366 | 
> 367 | function error (stream, err) {
> 368 |   setImmediate(() => {
> 369 |     stream.emit('error', err)
>                  ^
> error: the worker has exited
>       at emitError (node:events:47:13)
>       at <anonymous> (/Users/..../node_modules/thread-stream/index.js:369:12)
> error: script "dev" exited with code 1
> 
> ```
> 
> Sometimes, another error before crashing appears :
> ```
> 
> 364 |   }
> 365 | }
> 366 | 
> 367 | function error (stream, err) {
> 368 |   setImmediate(() => {
> 369 |     stream.emit('error', err)
>                  ^
> TypeError: destination.write is not a function. (In 'destination.write(toWrite)', 'destination.write' is undefined)
>       at emitError (node:events:47:13)
>       at <anonymous> (/Users/.../node_modules/thread-stream/index.js:369:12)
> ```

Let's create separate issue?

**Comment by soknifedev** [comment]
> > I'm using rascal and it connects but crash regularly.
> > To reproduce: create a rascal client connection and create 'subscription' to a queue, then receive some messages, the entire bun process crash.
> > ```
> > 
> > 364 |   }
> > 365 | }
> > 366 | 
> > 367 | function error (stream, err) {
> > 368 |   setImmediate(() => {
> > 369 |     stream.emit('error', err)
> >                  ^
> > error: the worker has exited
> >       at emitError (node:events:47:13)
> >       at <anonymous> (/Users/..../node_modules/thread-stream/index.js:369:12)
> > error: script "dev" exited with code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sometimes, another error before crashing appears :
> > ```
> > 
> > 364 |   }
> > 365 | }
> > 366 | 
> > 367 | function error (stream, err) {
> > 368 |   setImmediate(() => {
> > 369 |     stream.emit('error', err)
> >                  ^
> > TypeError: destination.write is not a function. (In 'destination.write(toWrite)', 'destination.write' is undefined)
> >       at emitError (node:events:47:13)
> >       at <anonymous> (/Users/.../node_modules/thread-stream/index.js:369:12)
> > ```
> 
> Let's create separate issue?

Hmm, I'm not sure because it is related to rabbitmq at the end... However What I've found is that the mongodb driver is not connecting / working properly in bun too. I'll create a new issue for it.
