### ISSUE TITLE
Support AdonisJS 6

### ISSUE THREAD

**Issue by RomainLanz** [oven-sh/bun#4822]
This is a tracking issue to get bun's node.js compatibility far enough along to support https://adonisjs.com

- [x] Support `Intl.ListFormat` #808
- [x] Pino Pretty fail #4280|
- [x] Issue when parsing Stacktrace #4693
- [x] Inconsistency when loading ESM modules
- [ ] TypeScript Metadata #6326
- [x] Node.js subpath import not working #10001

Current Status : https://github.com/oven-sh/bun/issues/4822#issuecomment-2869863670

**Comment by RomainLanz** [comment]
Current AdonisJS 6 fails to run because of `Intl.ListFormat` not yet available.

Tracking: https://github.com/oven-sh/bun/issues/808

**Comment by fareeda0** [comment]
Just tried on Linux https://github.com/oven-sh/bun/issues/1843#issuecomment-1710732503 and managed to get the server to start.

It's still throwing a few errors (file watch mode doesn't seem to work), but it's running!

<img width="2056" alt="Screenshot 2023-09-10 at 21 29 56" src="https://github.com/oven-sh/bun/assets/48023586/588afa53-c0d1-431e-bf2e-dc625ea6fa61">

**Comment by fareeda0** [comment]
I suspect there's a lot more going on but adding

```
fs.inotify.max_user_watches=524288
```

to `/etc/sysctl.conf`

gets file watching to work 👍

**Comment by fareeda0** [comment]
Running on Linux (https://github.com/oven-sh/bun/issues/1843#issuecomment-1710732503) seems to get a bit further.

Ace seems to run, and can run some commands.

However, server is still not running  (`error: expected ":" separator`.)

#### Running ace:

<img width="1032" alt="Screenshot 2023-09-11 at 08 18 02" src="https://github.com/oven-sh/bun/assets/48023586/8397db16-39d1-48a4-9de4-84aaf2a56b60">

#### Running ace commands:

<img width="1033" alt="Screenshot 2023-09-11 at 08 19 37" src="https://github.com/oven-sh/bun/assets/48023586/b8a8ac29-37b2-4e90-9865-7647348e84bb">

#### Running server (doesn't work):

<img width="1038" alt="Screenshot 2023-09-11 at 08 20 16" src="https://github.com/oven-sh/bun/assets/48023586/a5d5555b-d9d7-40d9-8079-ccdf331fc9db">

**Comment by RomainLanz** [comment]
The `Intl.ListFormat` issue has been fixed in the latest canary release of Bun.

```sh
bun upgrade --canary
```

Now running the ace command line breaks directly with the error `error: expected ":" separator`.

Running directly the `server.ts` script ends up with a similar error.

```sh
bun bin/server.ts
[0.78ms] ".env"
221 |   const callback = args[args.length - 1];
222 |   if (typeof callback !== "function")
223 |     @throwTypeError("Callback must be a function");
224 |   fs.readdir(...args).then((result) => callback(null, result), callback);
225 | 
226 | }, readFile = function readFile2(...args) {
                                                                   ^
TypeError: Invalid path string: can't be empty
 code: "ERR_INVALID_ARG_TYPE"

      at readFile2 (node:fs:226:64)
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:60:6
      at new Promise (:1:20)
      at _getFrameSource (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:59:11)
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:95:17
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:91:31
      at map (:1:20)
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:91:8
      at new Promise (:1:20)
      at _parseError (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:88:11)
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:323:6
      at new Promise (:1:20)
      at toJSON (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:322:11)
      at /Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/core/build/index.js:33:38
      at processTicksAndRejections (:55:76)
```

It seems to be linked to an issue of Bun not sending back a file path when parsing the stack trace (using [stacktracey](https://github.com/xpl/stacktracey)). https://github.com/poppinss/youch/pull/49

This is maybe due to Bun having a different format to display stack trace. https://github.com/xpl/stacktracey/blob/master/stacktracey.js#L49 - https://github.com/oven-sh/bun/issues/185

**Comment by RomainLanz** [comment]
Monkey patching the `Youch` module in the meanwhile end up with an issue to resolve the `router` from the IoC Container.

```sh
bun bin/server.ts
[1.13ms] ".env"

   TypeError: undefined is not an object (evaluating 'router.get')
```

This is probably due to a different way of initializing ESM modules.

The code that is breaking is:

```ts
import router from '@adonisjs/core/services/router'

router.get('/', async () => 'It works!')
````

The `router` instance is instantiated with the following.

```ts
import app from './app.js';
let router;

/**
 * Returns a singleton instance of the router class from
 * the container
 */
await app.booted(async () => {
    router = await app.container.make('router');
});

export { router as default };
```

**Comment by RomainLanz** [comment]
It also appears to randomly fail on some `pino` transport mechanisms.

```sh
bun bin/server.ts
[0.20ms] ".env"

   TypeError: undefined is not an object (evaluating 'callers')
   
   
   ⁃ fixTarget
     node_modules/pino/lib/transport.js:129
   ⁃ <anonymous>
     node_modules/pino/lib/transport.js:93
   ⁃ transport
     node_modules/pino/lib/transport.js:90
```

The `pino` module does not run the same on Node.js and Bun.

```ts
function transport (fullOptions) {
  const { pipeline, targets, levels, dedupe, options = {}, worker = {}, caller = getCallers() } = fullOptions

  // Backwards compatibility
  const callers = typeof caller === 'string' ? [caller] : caller
  console.log(callers)
  
  // ...
```

Bun outputs `undefined` whereas Node.js outputs:
```sh
[
  'file:///Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/logger/build/src/pino.js',
  'file:///Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/logger/build/src/logger.js',
  'file:///Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/logger/build/src/logger_manager.js',
  'file:///Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/core/build/providers/app_provider.js'
]
```

Tracking: https://github.com/oven-sh/bun/issues/4280

**Comment by capaj** [comment]
@RomainLanz see the latest comment in #4280, with a small hackfix pino runs nicely in bun

**Comment by RomainLanz** [comment]
> @RomainLanz see the latest comment in #4280, with a small hackfix pino runs nicely in bun

This fixed it, but yeah, it is a hack fix since having an `if (global.bun)` is not the way to go. 😄 

I still have some random ESM loading issues (see https://github.com/oven-sh/bun/issues/4822#issuecomment-1722181339)

```sh
bun bin/server.ts
[1.70ms] ".env"
[0.00ms] ".env"

   TypeError: undefined is not an object (evaluating 'router.get')
 
   at module code start/routes.ts:2
   1|  /*
 ❯ 2|  |--------------------------------------------------------------------------
   3|  | Routes file
   4|  |--------------------------------------------------------------------------
   5|  |
   6|  | The routes file is used for defining the HTTP routes.
   7|  |
   ```
   
   But running it another time seems to be good for the core of the framework!
   
   ```sh
bun bin/server.ts
[0.71ms] ".env"
[0.00ms] ".env"
[11:38:34.865] INFO (81972): started HTTP server on localhost:3333
```

![CleanShot 2023-09-16 at 11 39 41@2x](https://github.com/oven-sh/bun/assets/2793951/226687eb-ef0d-47bd-88d6-57ab1c3d0433)

**Comment by coratgerl** [comment]
> The `Intl.ListFormat` issue has been fixed in the latest canary release of Bun.
> 
> ```shell
> bun upgrade --canary
> ```
> 
> Now running the ace command line breaks directly with the error `error: expected ":" separator`.
> 
> Running directly the `server.ts` script ends up with a similar error.
> 
> ```shell
> bun bin/server.ts
> [0.78ms] ".env"
> 221 |   const callback = args[args.length - 1];
> 222 |   if (typeof callback !== "function")
> 223 |     @throwTypeError("Callback must be a function");
> 224 |   fs.readdir(...args).then((result) => callback(null, result), callback);
> 225 | 
> 226 | }, readFile = function readFile2(...args) {
>                                                                    ^
> TypeError: Invalid path string: can't be empty
>  code: "ERR_INVALID_ARG_TYPE"
> 
>       at readFile2 (node:fs:226:64)
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:60:6
>       at new Promise (:1:20)
>       at _getFrameSource (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:59:11)
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:95:17
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:91:31
>       at map (:1:20)
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:91:8
>       at new Promise (:1:20)
>       at _parseError (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:88:11)
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:323:6
>       at new Promise (:1:20)
>       at toJSON (/Users/romainlanz/workspace/lab/bun-test/node_modules/youch/src/Youch.js:322:11)
>       at /Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/core/build/index.js:33:38
>       at processTicksAndRejections (:55:76)
> ```
> 
> It seems to be linked to an issue of Bun not sending back a file path when parsing the stack trace (using [stacktracey](https://github.com/xpl/stacktracey)). [poppinss/youch#49](https://github.com/poppinss/youch/pull/49)
> 
> This is maybe due to Bun having a different format to display stack trace. https://github.com/xpl/stacktracey/blob/master/stacktracey.js#L49 - #185

This bug is fixed in #4693

**Comment by jaspersmitNL** [comment]
I'm unable to to start it up, even using the bun canary build

1. git clone https://github.com/adonisjs/slim-starter-kit
2. cd slim-starter-kit
3. bun install
4. cp .env.example .env
5. bun bin/server.ts

```
bun bin/server.ts   
[0.06ms] ".env"

   TypeError: undefined is not an object (evaluating 'callers')
 

   ⁃ fixTarget
     node_modules/pino/lib/transport.js:129
   ⁃ <anonymous>
     node_modules/pino/lib/transport.js:93
   ⁃ transport
     node_modules/pino/lib/transport.js:90
```

**Comment by RomainLanz** [comment]
> I'm unable to to start it up, even using the bun canary build
> 
>     1. git clone https://github.com/adonisjs/slim-starter-kit
> 
>     2. cd slim-starter-kit
> 
>     3. bun install
> 
>     4. cp .env.example .env
> 
>     5. bun bin/server.ts
> 
> 
> ```
> bun bin/server.ts   
> [0.06ms] ".env"
> 
>    TypeError: undefined is not an object (evaluating 'callers')
>  
> 
>    ⁃ fixTarget
>      node_modules/pino/lib/transport.js:129
>    ⁃ <anonymous>
>      node_modules/pino/lib/transport.js:93
>    ⁃ transport
>      node_modules/pino/lib/transport.js:90
> ```

Yes, it still does not work well with `pino`.
You can monkey patch your node_modules to make it work.

Please, look at the latest comment of https://github.com/oven-sh/bun/issues/4280#issuecomment-1722188648.

**Comment by jaspersmitNL** [comment]
> > I'm unable to to start it up, even using the bun canary build
> > ```
> > 1. git clone https://github.com/adonisjs/slim-starter-kit
> > 
> > 2. cd slim-starter-kit
> > 
> > 3. bun install
> > 
> > 4. cp .env.example .env
> > 
> > 5. bun bin/server.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > bun bin/server.ts   
> > [0.06ms] ".env"
> > 
> >    TypeError: undefined is not an object (evaluating 'callers')
> >  
> > 
> >    ⁃ fixTarget
> >      node_modules/pino/lib/transport.js:129
> >    ⁃ <anonymous>
> >      node_modules/pino/lib/transport.js:93
> >    ⁃ transport
> >      node_modules/pino/lib/transport.js:90
> > ```
> 
> Yes, it still does not work well with `pino`. You can monkey patch your node_modules to make it work.
> 
> Please, look at the latest comment of [#4280 (comment)](https://github.com/oven-sh/bun/issues/4280#issuecomment-1722188648).

I'm getting the same error, Even with the patched version.

**Comment by deevus** [comment]
> > I'm unable to to start it up, even using the bun canary build
> > ```
> > 1. git clone https://github.com/adonisjs/slim-starter-kit
> > 
> > 2. cd slim-starter-kit
> > 
> > 3. bun install
> > 
> > 4. cp .env.example .env
> > 
> > 5. bun bin/server.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > bun bin/server.ts   
> > [0.06ms] ".env"
> > 
> >    TypeError: undefined is not an object (evaluating 'callers')
> >  
> > 
> >    ⁃ fixTarget
> >      node_modules/pino/lib/transport.js:129
> >    ⁃ <anonymous>
> >      node_modules/pino/lib/transport.js:93
> >    ⁃ transport
> >      node_modules/pino/lib/transport.js:90
> > ```
> 
> Yes, it still does not work well with `pino`. You can monkey patch your node_modules to make it work.
> 
> Please, look at the latest comment of [#4280 (comment)](https://github.com/oven-sh/bun/issues/4280#issuecomment-1722188648).

Just attempted with latest version of bun (1.0.3)

```
➜ bun bin/server.ts 
[11:48:06.838] INFO (191609): started HTTP server on localhost:3333
```

I get the message "It works!" in the browser.

**Comment by RomainLanz** [comment]
With version `1.0.6` of Bun, we can run an AdonisJS Slim boilerplate with some issues loading ESM module with TLA.

```bash
bun bin/server.ts

   TypeError: undefined is not an object (evaluating 'router.get')

   at module code start/routes.ts:13
    8|   */
    9|
   10|  import HellosController from '#controllers/hellos_controller'
   11|  import router from '@adonisjs/core/services/router'
   12|
 ❯ 13|  router.get('/', async () => 'It works!')
   14|  router.get('/hello', [HellosController, 'greet'])
   15|
```

`router` is `undefined` but should not be. It is a flaky behavior.

We cannot run the `ace` file directly, but running the server works with `bun bin/server.ts`.

```bash
bun ace.js serve --watch
error: expected ":" separator
```

--

Trying out Dependency Injection, Bun seems not to emit metadata, making it unusable.

```ts
import { inject } from '@adonisjs/core';
import HelloService from '#services/hello_service';

@inject()
export default class HellosController {
  constructor(private helloService: HelloService) { }

  greet() {
    return this.helloService.hello('world');
  }
}
```

This is causing the code to fail because `HelloService` is not kept.

```bash
bun bin/server.ts
[12:40:52.521] INFO (69034): started HTTP server on 0.0.0.0:3333
[12:41:04.535] ERROR (69034): Cannot construct "[class HellosController]" class. Container is not able to resolve its dependencies
    request_id: "tkkwx1bcn7h2ce96u0xkarzn"
    x-request-id: "tkkwx1bcn7h2ce96u0xkarzn"
    err: {
      "type": "RuntimeException",
      "message": "Cannot construct \"[class HellosController]\" class. Container is not able to resolve its dependencies",
      "stack":
          Error: Cannot construct "[class HellosController]" class. Container is not able to resolve its dependencies
              at new Exception (/Users/romainlanz/workspace/lab/bun-test/node_modules/@poppinss/utils/build/index.js:43:50)
              at new RuntimeException (:1:33)
              at createError (/Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/fold/build/index.js:293:36)
              at <anonymous> (/Users/romainlanz/workspace/lab/bun-test/node_modules/@adonisjs/fold/build/index.js:365:12)
              at asyncFunctionResume (native)
              at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
              at promiseReactionJob (native)
              at processTicksAndRejections (native)
      "name": "RuntimeException",
      "status": 500,
      "code": "E_RUNTIME_EXCEPTION"
    }
```

**Comment by fareeda0** [comment]
> Trying out Dependency Injection, Bun seems not to emit metadata, making it unusable

Tried with version `1.0.7` and emit metadata works with a flattened `tsconfig.json`. Seems related to https://github.com/oven-sh/bun/issues/6326.

Flaky TLA import issue is still there though.

**Comment by fareeda0** [comment]
Interestingly, if you add `./node_modules` to the `extends` path it also works:

```
{
  "extends": "./node_modules/@adonisjs/tsconfig/tsconfig.app.json",
  "compilerOptions": {
    // 
  }
}
```
Look related to: https://github.com/oven-sh/bun/issues/5277

**Comment by RomainLanz** [comment]
The following commit will probably fix ESM loading issue: https://github.com/oven-sh/WebKit/commit/00ae02e4c661357fd30a8153c58905eccc57be78

**Comment by RomainLanz** [comment]
The next version of Bun [should arrive next Tuesday](https://x.com/jarredsumner/status/1718401937690001743).
It will probably fix the flaky behavior when loading ESM module using TLA.

**Comment by RomainLanz** [comment]
With Bun `1.0.8`, we still have flaky behavior when loading ESM module using TLA.

```sh
bun bin/server.ts

   TypeError: undefined is not an object (evaluating 'router.get')

   at module code start/routes.ts:13
    8|   */
    9|
   10|  import HellosController from '#controllers/hellos_controller'
   11|  import router from '@adonisjs/core/services/router'
   12|
 ❯ 13|  router.get('/', async () => 'It works!')
   14|  router.get('/hello', [HellosController, 'greet'])
   15|
```

**Comment by RomainLanz** [comment]
Bun `1.0.11` still has the issue above.

**Comment by RomainLanz** [comment]
Same with `1.0.12`

**Comment by Banashek** [comment]
Tested today on WSL2 with the steps [above](https://github.com/oven-sh/bun/issues/4822#issuecomment-1722981304) and it seems to start up fine.

OS: Windows 10
WSL2 linux version: `Linux DESKTOP-4B5CT4E 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Bun version: `1.0.13`

![image](https://github.com/oven-sh/bun/assets/7094571/612b7e7e-cfef-45ab-a643-700c8ad82261)

![image](https://github.com/oven-sh/bun/assets/7094571/8d55687a-a017-4864-9202-eecffe4348e9)

**Comment by fareeda0** [comment]
It's a flaky behaviour. Run `bun run bin/server.ts` a few times and you'll see It will fail sometimes.

```
   TypeError: undefined is not an object (evaluating 'router.use')
 
   at module code start/kernel.ts:36
   31|  router.use([() => import('@adonisjs/core/bodyparser_middleware')])
   32|  
   33|  /**
   34|   * Named middleware collection must be explicitly assigned to
   35|   * the routes or the routes group.
 ❯ 36|   */
   37|  export const middleware = router.named({})
   38|  
```

Tested with bun `1.0.13`

**Comment by Banashek** [comment]
Interesting, I wasn't able to reproduce:

![image](https://github.com/oven-sh/bun/assets/7094571/13d96222-9847-428d-bc38-f7aab6bc7ad7)

What OS are you on?

**Comment by fareeda0** [comment]
macOS 14.1 (Sonoma)

**Comment by Banashek** [comment]
I just tested on macos 13.5.1 and also was unable to reproduce.

I'll test out using more features to see if I can reproduce later when I have some time.

**Comment by Banashek** [comment]
Cloned the web-starter-kit as well and tested:

![image](https://github.com/oven-sh/bun/assets/7094571/aae07756-90e3-4ffc-b3a3-d9398dac8e03)

Added in a dynamic bit to the template and the js script to see if it would build things and render out properly (still used `node ace build` to build since `bun ace` doesn't work immediately):

![image](https://github.com/oven-sh/bun/assets/7094571/d2e2fb1b-ec32-456f-881d-1ac0cde5ab2e)

**Comment by RomainLanz** [comment]
I can confirm that it is still not working on Bun `1.0.14`.

```sh
bun ./bin/server.ts

   TypeError: undefined is not an object (evaluating 'router.get')
```

@Banashek Are you doing anything special to make it work?

I am on a macOS Sonoma 14.0.

**Comment by RomainLanz** [comment]
I will check to create a proper issue with a reproduction so the Bun team can address the bug.

**Comment by mattkenefick** [comment]
I was getting mixed results with `1.0.14` and the slim clone. Here's a video of me commenting and uncommenting a line with mixed results. In the middle of the video, you'll see that I don't actually change anything but it fails twice, then works.

Seems like it's some sort of cache / build / signature issue perhaps.

When I first installed it and ran it, I received the same issue as @RomainLanz 

```
   TypeError: undefined is not an object (evaluating 'router.get')
```

Which then turn into the issue you see in the video of:

```
   TypeError: undefined is not an object (evaluating 'router.use')
```

And then became a mixed bag of working / not working. I started commenting pieces how to see how far the app would get before an error, and that's when it worked / failed / worked again in both commented and uncommented scenarios.

Later in the video (0:53) there's another new error which is interesting because I'm not changing anything significant in how I'm testing it.

```
ReferenceError: Cannot access uninitialized variable.
```

https://github.com/oven-sh/bun/assets/149809/69b9e3fc-e001-4783-b1ab-ca0afbc7dba1

**Comment by Banashek** [comment]
@RomainLanz Nothing to my knowledge:
![image](https://github.com/oven-sh/bun/assets/7094571/b78a8451-819e-4646-b3a5-7ac1b92eaae1)

Perhaps there's a chance packages are cached either on my side?
I'll try again on a fresh computer when I get a chance.

**Comment by mattkenefick** [comment]
> @RomainLanz Nothing to my knowledge
> Perhaps there's a chance packages are cached either on my side? I'll try again on a fresh computer when I get a chance.

@Banashek 

Try stopping, starting, stopping, starting, etc.

In my video above, I was able to produce both of your results with one install.

**Comment by RomainLanz** [comment]
> @RomainLanz Nothing to my knowledge: ![image](https://private-user-images.githubusercontent.com/7094571/286430651-b78a8451-819e-4646-b3a5-7ac1b92eaae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjMwMzYsIm5iZiI6MTcwMTc2MjczNiwicGF0aCI6Ii83MDk0NTcxLzI4NjQzMDY1MS1iNzhhODQ1MS04MTllLTQ2NDYtYjNhNS03YWMxYjkyZWFhZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDc1MjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY5YTdkZmE1OWYzZTIzYzlmNGNiNzBiM2FhOWNhNGI5ZDM0ZDEyM2QzNzU2ODM4OTE0ZDMxMzEwMWUxZGU1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BMRN_Ocyt4ijxcgGp8eF_WBp8hRGlVmldYdxb8re7ZE)
> 
> Perhaps there's a chance packages are cached either on my side? I'll try again on a fresh computer when I get a chance.

This is an AdonisJS 5 application, that is the difference! 😄

**Comment by RomainLanz** [comment]
I still have the issue with the latest release (`1.0.25`).

```sh
bun bin/server.ts
   TypeError: undefined is not an object (evaluating 'router.get')
```

I have added some logs inside the `router` resolution and it seems correct:

```ts
let router;
/**
 * Returns a singleton instance of the router class from
 * the container
 */
await app.booted(async () => {
  console.log('booted')
  console.log(await app.container.make('router'))
    router = await app.container.make('router');
});

export { router as default }
```

```sh
bun bin/server.ts
booted
Router { .... }
   TypeError: undefined is not an object (evaluating 'router.get')
```

--

I tried to create a minimal reproduction of the bug but it wasn't successful. It seems the bug is not directly linked to TLA, I will need to troubleshoot further.

```js
// router.js

async function sleepThen(ms, callback) {
  await new Promise(resolve => setTimeout(resolve, ms));
  callback();
}

let router

await sleepThen(10, async () => {
  router = { get() { console.log('working') }}
})

export default router
```

```js
// app.js

import router from './router.js'

router.get()
```

```sh
bun app.js
// working
```

**Comment by xxCosta** [comment]
having the same issues, ran it on docker and wsl2

**Comment by xxCosta** [comment]
`bun run bin/server.ts` is fully functional for me on the latest version (1.0.29) using the slim and api adonis templates.  Tried it on wsl2 and docker.

**Comment by RomainLanz** [comment]
I still have the issue with `1.0.29` on macOS.

![CleanShot 2024-03-04 at 08 32 24@2x](https://github.com/oven-sh/bun/assets/2793951/2d9e0d2e-eee3-4f6d-bd6a-70a386cd77fb)

**Comment by RomainLanz** [comment]
I tried Bun `1.1` with my Windows setup, and it seems to not support Node.js subpath imports.

```
PS C:\workspace\lab\bun-adonis> bun run .\bin\server.ts

   ResolveMessage: Cannot find module "#start/env" from "C:\workspace\lab\bun-adonis\bin\server.ts"
```

**Comment by RomainLanz** [comment]
Tracking subpath import: https://github.com/oven-sh/bun/issues/10001

**Comment by RomainLanz** [comment]
Side note, it is still flacky on macOS with version `1.1.1` with the same error related to ESM loading. I wasn't able yet to create a minimal reproduction but I didn't really had the time to do so.

If anyone want to try it. 👍🏻

**Comment by genesiscz** [comment]
> Tracking subpath import: #10001

Isn't the subpath import fixable by just doing the same imports in tsconfig.json? 

BTW how did you get rid of the `error: expected ":" separator` message?

Any progress on this?

**Comment by RomainLanz** [comment]
> Isn't the subpath import fixable by just doing the same imports in tsconfig.json?

There is no need to replicate the imports in the `tsconfig.json` file. TypeScript already reads the `package.json` entry. It all depends on which version of TypeScript Bun uses.

> BTW how did you get rid of the error: expected ":" separator message?

I am not running the code through `ace` but directly.

**Comment by genesiscz** [comment]
> > Isn't the subpath import fixable by just doing the same imports in tsconfig.json?
> 
> There is no need to replicate the imports in the `tsconfig.json` file. TypeScript already reads the `package.json` entry. It all depends on which version of TypeScript Bun uses.
> 
> > BTW how did you get rid of the error: expected ":" separator message?
> 
> I am not running the code through `ace` but directly.

But if you want to run `serve --watch`, you have to at least run the console command somehow. 

I got as far as trying `NODE_DEBUG=chokidar:ts bun bin/console.ts serve --watch` which points me to the error being in the 

`const parsedConfig = this.#ts.getParsedCommandLineOfConfigFile(` line of chokidar-ts.

**Comment by RomainLanz** [comment]
Yes, we have to troubleshoot further why Ace command do not work.

Also, we are soon releasing an HMR feature for our CLI, meaning you will not have to use `--watch` anymore!

**Comment by kaanrkaan** [comment]
Another compatibility issue that I noticed was with the test

```
SyntaxError: Export named 'Recoverable' not found in module 'repl'.

   at (syntax error) SyntaxError: Export named 'Recoverable' not found in module 'repl'.
```
   
As bun.js doesn't implemented the node:repl unit tests doesn't work on the adonisjs6 with bun

ps. there is an experimental bun:repl package. However, Recoverable is not implemented in that package either

The workaround is disabling repl for the test environment (I don't know if it does break functionality)

on `adonisrc.ts` file edit the providers (starting from 27th line in the api-starter)

```js
  providers: [
    () => import('@adonisjs/core/providers/app_provider'),
    () => import('@adonisjs/core/providers/hash_provider'),
    {
      file: () => import('@adonisjs/core/providers/repl_provider'),
      environment: ['repl'],
    },
    () => import('@adonisjs/core/providers/vinejs_provider'),
    () => import('@adonisjs/cors/cors_provider'),
    () => import('@adonisjs/lucid/database_provider'),
  ],
```

this resolves the repl not found issue as it disables the repl_provider for the test environment.

did a simple test of 

```js
import { test } from '@japa/runner'

function sum(a, b) {
  return a + b
}

test('add two numbers', ({ assert }) => {
  assert.equal(sum(2, 2), 4)
})

```
and can confirm that the jabba tests are now working

<img width="350" alt="image" src="https://github.com/oven-sh/bun/assets/52722679/4d6786a0-4167-4952-bdbe-83755a7952e4">

**Comment by genesiscz** [comment]
> Yes, we have to troubleshoot further why Ace command do not work.
> 
> Also, we are soon releasing an HMR feature for our CLI, meaning you will not have to use `--watch` anymore!

I actually made some progress. 

The `error: expected ":" separator` comes from bun when you pass `"--loader=ts-node/esm"` to the command itself:

`bun --loader=ts-node/esm bin/console.ts serve --watch`

Because the console command `serve` tries to run it with the `loader`, it fails. Unfortunatelly you can't just delete the loader even though Bun doesn't need it.

https://github.com/adonisjs/assembler/blob/develop/src/helpers.ts#L31

**Comment by kaanrkaan** [comment]
> > Yes, we have to troubleshoot further why Ace command do not work.
> > Also, we are soon releasing an HMR feature for our CLI, meaning you will not have to use `--watch` anymore!
> 
> I actually made some progress.
> 
> The `error: expected ":" separator` comes from bun when you pass `"--loader=ts-node/esm"` to the command itself:
> 
> `bun --loader=ts-node/esm bin/console.ts serve --watch`
> 
> Because the console command `serve` tries to run it with the `loader`, it fails. Unfortunatelly you can't just delete the loader even though Bun doesn't need it.
> 
> https://github.com/adonisjs/assembler/blob/develop/src/helpers.ts#L31

Can't we use simple if statement like this to bypass the loader when run via bun?

```js
if (process.versions.bun) {
  // this code will only run when the file is run with Bun
}
```

**Comment by RomainLanz** [comment]
> > > Yes, we have to troubleshoot further why Ace command do not work.
> > > Also, we are soon releasing an HMR feature for our CLI, meaning you will not have to use `--watch` anymore!
> > 
> > 
> > I actually made some progress.
> > The `error: expected ":" separator` comes from bun when you pass `"--loader=ts-node/esm"` to the command itself:
> > `bun --loader=ts-node/esm bin/console.ts serve --watch`
> > Because the console command `serve` tries to run it with the `loader`, it fails. Unfortunatelly you can't just delete the loader even though Bun doesn't need it.
> > https://github.com/adonisjs/assembler/blob/develop/src/helpers.ts#L31
> 
> Can't we use simple if statement like this to bypass the loader when run via bun?
> 
> ```js
> if (process.versions.bun) {
>   // this code will only run when the file is run with Bun
> }
> ```

Nope. Bun should support Node.js code as per their claim. We don't want to patch the AdonisJS codebase to make it work on Bun; they should adapt.

**Comment by kaanrkaan** [comment]
> > > > Yes, we have to troubleshoot further why Ace command do not work.
> > > > Also, we are soon releasing an HMR feature for our CLI, meaning you will not have to use `--watch` anymore!
> > > 
> > > 
> > > I actually made some progress.
> > > The `error: expected ":" separator` comes from bun when you pass `"--loader=ts-node/esm"` to the command itself:
> > > `bun --loader=ts-node/esm bin/console.ts serve --watch`
> > > Because the console command `serve` tries to run it with the `loader`, it fails. Unfortunatelly you can't just delete the loader even though Bun doesn't need it.
> > > https://github.com/adonisjs/assembler/blob/develop/src/helpers.ts#L31
> > 
> > 
> > Can't we use simple if statement like this to bypass the loader when run via bun?
> > ```js
> > if (process.versions.bun) {
> >   // this code will only run when the file is run with Bun
> > }
> > ```
> 
> Nope. Bun should support Node.js code as per their claim. We don't want to patch the AdonisJS codebase to make it work on Bun; they should adapt.

that makes sense 👍🏻 , meanwhile using the native watcher of the bun seems to do the job well

**Comment by RomainLanz** [comment]
There are still some inconsistencies with Bun `1.1.9`.

```sh
$ bun bin/server.ts
[12:05:46.878] INFO (74722): started HTTP server on 0.0.0.0:3333
^C⏎   

$ bun bin/server.ts

   TypeError: undefined is not an object (evaluating 'router.get')

   at module code start/routes.ts:13
    8|   */
    9|
   10|  import HellosController from '#controllers/hellos_controller'
   11|  import router from '@adonisjs/core/services/router'
   12|
 ❯ 13|  router.get('/', async () => 'It works!')
   14|  router.get('/hello', [HellosController, 'greet'])
   15|
   ```

**Comment by a4arpon** [comment]
Any progress about it? I mean supporting adonis on Bun?

**Comment by necessarylion** [comment]
MacOS with bun --version 1.1.22

Still have issue 

- `ResolveMessage: Cannot find module "#start/env"` (Similar to #10001) and after changing the path to use directly , it got another error
- TypeError: undefined is not an object (evaluating 'router.use')

```js
➜  $ bun bin/server.ts --watch

   TypeError: undefined is not an object (evaluating 'router.use')
 
   at module code start/kernel.ts:35
   30|  
   31|  /**
   32|   * The router middleware stack runs middleware on all the HTTP
   33|   * requests with a registered route.
   34|   */
 ❯ 35|  router.use([() => import('@adonisjs/core/bodyparser_middleware'), () => import('@adonisjs/auth/initialize_auth_middleware')])
   36|  
   37|  /**
   38|   * Named middleware collection must be explicitly assigned to
   39|   * the routes or the routes group.
   40|   */
```

**Comment by dennis9779** [comment]
Still have issue 1.1.26

![image](https://github.com/user-attachments/assets/290f33f3-2ad1-4846-b723-69080c552886)

**Comment by ggaabe** [comment]
on ubuntu with bun, trying to build the adonis project, I get this:

```bash
bun run build
$ node ace build
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'register' not found in module 'module'.

Bun v1.1.26 (Linux x64)
error: script "build" exited with code 1
```

**Comment by ashokkumar88** [comment]
I am getting the below error when run `bun bin/server.ts`

`ResolveMessage: Cannot find module "#start/env" from "/slim-starter-kit/bin/server.ts"`

**Comment by httzipdev** [comment]
Is there any update on this?

**Comment by RomainLanz** [comment]
There appears to be a regression in Bun `1.1.33`. It fails to resolve files imported using Node's subpath imports.

```sh
❯ bun bin/server.ts

   ResolveMessage: Cannot find module '#start/env' from '/home/romain/workspace/lab/bun-test/bin/server.ts'
```

**Comment by RomainLanz** [comment]
I may have good news. I have changed a bit the default boilerplate of an AdonisJS application to make it work with `node --experimental-transform-types` and it was working well.

After @jaredpalmer answer on [this topic](https://github.com/oven-sh/bun/issues/10001#issuecomment-2498379634), I have tried to run the project using Bun, and it works!

![Image](https://github.com/user-attachments/assets/e5f52ddc-d288-4fef-a2d2-b3f6f43d99c3)

I will do more testing and do some benchmark!

**Comment by RomainLanz** [comment]
After more testing, I still encounter sometime the same issue shared above. I am thinking this could be an issue with a peer depencencies resolution, but not sure.

![Image](https://github.com/user-attachments/assets/9e236cec-9683-4f97-99c7-ad9cc091cd85)

When the server start, it works but we cannot use Dependency Injection yet (same in Node.js `--experimental-transform-types` runtime). The reason is we are relying on

**Comment by RomainLanz** [comment]
After additional testing, I still occasionally encounter the issue mentioned earlier. I suspect this might be related to peer dependency resolution, but I'm not certain.

![Image](https://github.com/user-attachments/assets/9e236cec-9683-4f97-99c7-ad9cc091cd85)

When the server starts, it runs successfully, but Dependency Injection isn't functional yet (similar to the Node.js `--experimental-transform-types` runtime). This happens because we are relying on legacy decorators and TypeScript types, which are removed during compilation. Node.js uses SWC under the hood (not sure about Bun), which strips these features.

We'll need to wait for TypeScript to address this issue: https://github.com/microsoft/TypeScript/pull/58101 / https://github.com/microsoft/TypeScript/issues/57533#issuecomment-2495429721

**Comment by RomainLanz** [comment]
It looks like Bun 1.2 fixed the main issue we had to start our server!

![Image](https://github.com/user-attachments/assets/7ba5353d-ab25-40cb-9015-276f130b4330)

**Comment by RomainLanz** [comment]
Here is a small benchmark of our Slim starter-kit with Bun 1.2 and Node.js `22.13`.

Using: `autocannon -c 100 -d 40 -p 10`

**Bun 1.2**
```sh
Running 40s test @ http://localhost:3333
100 connections with 10 pipelining factor


┌─────────┬───────┬───────┬───────┬───────┬──────────┬─────────┬───────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max   │
├─────────┼───────┼───────┼───────┼───────┼──────────┼─────────┼───────┤
│ Latency │ 13 ms │ 29 ms │ 31 ms │ 32 ms │ 26.31 ms │ 5.82 ms │ 56 ms │
└─────────┴───────┴───────┴───────┴───────┴──────────┴─────────┴───────┘
┌───────────┬─────────┬─────────┬────────┬─────────┬──────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%    │ 97.5%   │ Avg      │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼────────┼─────────┼──────────┼─────────┼─────────┤
│ Req/Sec   │ 35551   │ 35551   │ 37567  │ 37887   │ 37308.81 │ 587     │ 35544   │
├───────────┼─────────┼─────────┼────────┼─────────┼──────────┼─────────┼─────────┤
│ Bytes/Sec │ 5.87 MB │ 5.87 MB │ 6.2 MB │ 6.25 MB │ 6.16 MB  │ 96.7 kB │ 5.86 MB │
└───────────┴─────────┴─────────┴────────┴─────────┴──────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 40

1493k requests in 40.02s, 246 MB read
```

**Node.js 22.13**
```sh
Running 40s test @ http://localhost:3333
100 connections with 10 pipelining factor


┌─────────┬───────┬───────┬───────┬───────┬──────────┬─────────┬────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max    │
├─────────┼───────┼───────┼───────┼───────┼──────────┼─────────┼────────┤
│ Latency │ 12 ms │ 25 ms │ 29 ms │ 30 ms │ 21.69 ms │ 7.57 ms │ 483 ms │
└─────────┴───────┴───────┴───────┴───────┴──────────┴─────────┴────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 43743   │ 43743   │ 45183   │ 45407   │ 45065.6 │ 335.26  │ 43719   │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Bytes/Sec │ 9.27 MB │ 9.27 MB │ 9.58 MB │ 9.63 MB │ 9.55 MB │ 71.3 kB │ 9.27 MB │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

Req/Bytes counts sampled once per second.
# of samples: 40

1804k requests in 40.02s, 382 MB read
```

**Comment by eokic** [comment]
Wonder why **less** req/sec 🤔

**Comment by gaetandezeiraud** [comment]
Curious to know the overall memory consumption. The big difference may be there (or not).

**Comment by httzipdev** [comment]
Cool 🔥

**Comment by rgonzlz** [comment]
Any updates @Jarred-Sumner? 

This is really limiting us in my company.

**Comment by RomainLanz** [comment]
> Any updates [@Jarred-Sumner](https://github.com/Jarred-Sumner)?
> 
> This is really limiting us in my company.

Why would a company force you to use Bun?

**Comment by rgonzlz** [comment]
> > Any updates [@Jarred-Sumner](https://github.com/Jarred-Sumner)?
> > This is really limiting us in my company.
> 
> Why would a company force you to use Bun?
> 
> Also, the only pain point we have now (from my minimal testing) is because of the TypeScript team. They haven't gave us any clarity about a needed feature. [microsoft/TypeScript#57533 (comment)](https://github.com/microsoft/TypeScript/issues/57533#issuecomment-2631158273)

Hello!

Perhaps I expressed myself poorly. I'm not forced to use it, I simply like Adonis and would like to use it with Bun, because it's more comfortable than using Node.​​​​​​​​​​​​​​​​

**Comment by waml** [comment]
so does bun work with adonisjs or not? why is it slower? normally when you run bun with express you should see 2~3x performance boost

**Comment by zangopushpak** [comment]
> It looks like Bun 1.2 fixed the main issue we had to start our server!
> 
> ![Image](https://github.com/user-attachments/assets/7ba5353d-ab25-40cb-9015-276f130b4330)

Can we now use the bun with adonis js ? I am confused as issue is still open.

**Comment by LordSalmon** [comment]
Any updates here? I would like to create a new project with bun and migrate my existing projects, but I'm not 100% sure since there is no explicit 'go' / 'yes it works' call.

**Comment by terion-name** [comment]
Getting `Cannot find module '#start/env` when trying to start adonis in pure bun container

**Comment by RomainLanz** [comment]
> Any updates here? I would like to create a new project with bun and migrate my existing projects, but I'm not 100% sure since there is no explicit 'go' / 'yes it works' call.

Out of curiosity, could you share why you're considering Bun for your new project? Performance gains are often cited, but in the case of AdonisJS, you likely won’t see noticeable improvements at runtime.

That said, AdonisJS can run on Bun, but with a few caveats:

1. You'll need to modify the subpath exports in our `package.json` to point to `.ts` files instead of `.js`.
2. Dependency Injection (via IoC container) does not work, because `reflect-metadata` isn't currently supported on Bun.

We've shared some more context on this here: https://x.com/adonisframework/status/1918224864189775886

Hope that helps clarify things!

**Comment by LordSalmon** [comment]
Thanks for the reply! 

It's mostly a debate of philosophy (at least for me):
 1.  I really enjoy the journey of Bun how it evolved and the simplicity it provides (referencing S3, Shell, crypto, Sqlite, Sockets etc)
 2. I also saw the performance reviews on AdonisJS using Bun vs Node, but the Performance of the HTTP Layer is not super important to me since the deeper laying implementation of the application logic has most of my focus. That being said: I really enjoy the AdonisJS with the simplicity it provides (for the developers) and the ease of mind I have with it (compared to Hono or other rather lightweight frameworks) and I want to keep using it.
3. Unification of code bases is also a topic since I currently start all my JS based projects in Bun and wouldn't like to switch back and forth.

Good call that DI is not working right now, that means I will wait with migrating my old projects. 
Thanks again for the head up, and you're doing a wonderful work with AdonisJS :) Keep it up!

**Comment by jaspersmitNL** [comment]
> > > Any updates here? I would like to create a new project with bun and migrate my existing projects, but I'm not 100% sure since there is no explicit 'go' / 'yes it works' call.
> > 
> > Out of curiosity, could you share why you're considering Bun for your new project? Performance gains are often cited, but in the case of AdonisJS, you likely won’t see noticeable improvements at runtime.
> > 
> > That said, AdonisJS can run on Bun, but with a few caveats:
> > 
> > 1. You'll need to modify the subpath imports in your `package.json` to point to `.ts` files instead of `.js`.
> > 2. Dependency Injection (via IoC container) does not work, because `reflect-metadata` isn't currently supported on Bun.
> > 
> > We've shared some more context on this here: https://x.com/adonisframework/status/1918224864189775886
> > 
> > Hope that helps clarify things!
> 
> I just tested on bun `1.2.19` and Dependency Injection is now working.
> We just need to add `"emitDecoratorMetadata": true,` flag on `compilerOptions` of `tsconfig.json`.
> 

Sadly many bugs and its slower in bun than in nodejs
