### ISSUE TITLE
Cannot run `bun install --production` without lock file

### ISSUE THREAD

**Issue by paul-uz** [oven-sh/bun#4945]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

* run `bun install --production` with no bun.lockb file present

### What is the expected behavior?

Bun should be able to install just production dependencies without a lock file

### What do you see instead?

bun errored with the following message

> error: lockfile had changes, but lockfile is frozen

### Additional information

NPM can install production only dependencies from scratch without the need of a lockfile, so I would expect bun to be able to do this as well.

**Comment by rioastamal** [comment]
Had the same issue, I am running on Linux x64

**Comment by treeder** [comment]
I have a lock file present and it fails with:

```
Step 4/8 : RUN bun install --production
Step #0 - "Build":  ---> Running in aa3ec64993cc
Step #0 - "Build": bun install v1.0.1 (31aec4eb)
Step #0 - "Build": error: lockfile had changes, but lockfile is frozen
```

**Comment by cnnranderson** [comment]
I'm also generally getting lockfile issues along the same lines:

```
git:(main) ✗ bun i --frozen-lockfile
[0.50ms] ".env"
bun install v1.0.1 (31aec4eb)
error parsing lockfile: BufferOverflow
ignoring lockfile
error: lockfile had changes, but lockfile is frozen
```

This was first seen on our Ubuntu build agent (Azure DevOps pipeline) and I can sometimes reproduce on my Mac.

**Comment by lfniederauer** [comment]
1.0.2 as well.
Tried with several docker images from ubuntu and debian releases.

**Comment by josssch** [comment]
I am having issues using a Docker image as well, even with copying the bun.lockb file.

```dockerfile
FROM oven/bun:1.0.2

WORKDIR /app

COPY package.json .
COPY bun.lockb .

# error: lockfile had changes, but lockfile is frozen
RUN bun install --production  

# ... everything else ...

CMD bun start
```

**Comment by tuan-zigvy** [comment]
I copy bun.lockb file but not have issues  # error: lockfile had changes, but lockfile is frozen

**Comment by sob0994** [comment]
> I am having issues using a Docker image as well, even with copying the bun.lockb file.
> 
> ```dockerfile
> FROM oven/bun:1.0.2
> 
> WORKDIR /app
> 
> COPY package.json .
> COPY bun.lockb .
> 
> # error: lockfile had changes, but lockfile is frozen
> RUN bun install --production  
> 
> # ... everything else ...
> 
> CMD bun start
> ```

I got same error, but i try to make bun.lockb first with frozen-lockfile.

```
# if necessary
bun install

# then
bun install --frozen-lockfile
```

this wil produce a bun.lockb an allow to bun install --production then without error. then can use the bun.lockb to your Dockerfile

**Comment by josssch** [comment]
> > I am having issues using a Docker image as well, even with copying the bun.lockb file.
> > ```dockerfile
> > FROM oven/bun:1.0.2
> > 
> > WORKDIR /app
> > 
> > COPY package.json .
> > COPY bun.lockb .
> > 
> > # error: lockfile had changes, but lockfile is frozen
> > RUN bun install --production  
> > 
> > # ... everything else ...
> > 
> > CMD bun start
> > ```
> 
> I got same error, but i try to make bun.lockb first with frozen-lockfile.
> 
> ```
> # if necessary
> bun install
> 
> # then
> bun install --frozen-lockfile
> ```
> 
> this wil produce a bun.lockb an allow to bun install --production then without error. then can use the bun.lockb to your Dockerfile

I found this as a solution a while ago, I've only made mention of the error since I don't believe this should be the way it has to be done.

**Comment by tapz** [comment]
My dev deps fail with the docker image and --production flag does not work without a lock file. I had to create a second package.json, which does not have the dev deps. A stupid workaround for a bug that should have been fixed in bun long time ago.

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.3 https://github.com/oven-sh/bun/pull/9923

Sorry we forgot to update this issue after fixing it. Please leave a comment if you still run into an error like this

**Comment by tapz** [comment]
@Jarred-Sumner It does not install the devDependencies with --production, but it still does some processing to them as there are (disappearing) logging for not found NPM packages (which it first tries to load from npm, but then realizes this is a monorepo). Works much better and faster when I just remove the devDepencies completely before running bun install.

**Comment by CringleySDays** [comment]
@Jarred-Sumner there seems to be another issue persistent where when running `bun install --production` doesn't create the `bun.lockb` file at all. It installs the node modules, I don't think it installs any devDependencies.

To counter this issue of `bun.lockb` file not being created, I ran `bun install` to create the file and then `bun install --production`. This doesn't edit the file at all in terms of removing all devDependencies. 

bun version (via revision): 1.1.8+89d25807f
Platform: Microsoft Windows NT 10.0.19045.0 x64
Expected behaviour: like pnpm
