### ISSUE TITLE
bun install/create fails with error: ConnectionRefused downloading package manifest

### ISSUE THREAD

**Issue by PrajvalBadiger** [oven-sh/bun#4988]
### What version of Bun is running?

1.0.0+350403663e5ece8b1d09adce3a3594f8e05bf8f1

### What platform is your computer?

Linux 6.5.2-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

1. create a new directory  and cd into it then run the below commands
2. `bun init` 
3. `bun install`

or 
``` bash
$ bun create react my-app
```
### What is the expected behavior?

Should install packages from package.jdon

### What do you see instead?

``` bash
$ bun install --verbose
bun install v1.0.0 (35040366)
Enqueue package manifest for download: bun-types
Enqueue package manifest for download: figlet
  🔍 bun-types [11/12]
error: ConnectionRefused downloading package manifest bun-types
  🔍 figlet [12/12]
error: ConnectionRefused downloading package manifest figlet


warn: warn: ConnectionRefused downloading package manifest bun-types


warn: warn: ConnectionRefused downloading package manifest figlet


warn: warn: ConnectionRefused downloading package manifest bun-types


warn: warn: ConnectionRefused downloading package manifest figlet


warn: warn: ConnectionRefused downloading package manifest bun-types


warn: warn: ConnectionRefused downloading package manifest figlet


warn: warn: ConnectionRefused downloading package manifest bun-types


warn: warn: ConnectionRefused downloading package manifest figlet


warn: warn: ConnectionRefused downloading package manifest bun-types


warn: warn: ConnectionRefused downloading package manifest figlet

error: bun-types@latest failed to resolve
error: figlet@^1.6.0 failed to resolve
```
### Additional information

``` bash
$ cat package.json
{
    "name": "bun-quick-start",
    "module": "index.ts",
    "type": "module",
    "scripts": {
        "start": "bun run index.ts"
    },
    "devDependencies": {
        "bun-types": "latest"
    },
    "peerDependencies": {
        "typescript": "^5.0.0"
    },
    "dependencies": {
        "figlet": "^1.6.0"
    }
}
```

**Comment by nicu-chiciuc** [comment]
I'm having the same issue with
```fish
> bun --version
1.0.1
```

```fish
> time bun install
bun install v1.0.1 (31aec4eb)
  🔍 bun-types [6/6] 
error: ConnectionRefused downloading package manifest bun-types
error: bun-types@latest failed to resolve

________________________________________________________
Executed in  450.16 secs      fish           external
   usr time   23.79 millis    6.70 millis   17.09 millis
   sys time   34.56 millis    2.89 millis   31.67 millis
```

it took more than 7 minutes to get to this error

I'm running it on a M1 mac:
```
12.5 (21G72)
```

I assume this is caused by ipv6.

**Comment by PrajvalBadiger** [comment]
For me it immediately trows this error. I have a working Internet connection.
I also upgraded to v1.0.1 and still the same issue

``` bash
$ bun upgrade
bun v1.0.1 is out! You're on 1.0.0
[20.71s] Upgraded.

Welcome to bun v1.0.1!

Report any bugs:

    https://github.com/oven-sh/bun/issues

What's new:

    https://github.com/oven-sh/bun/releases/tag/bun-v1.0.1

Changelog:

    https://github.com/oven-sh/bun/compare/bun-v1.0.0...bun-v1.0.1
```
``` bash
$ time bun install
bun install v1.0.1 (31aec4eb)
  🔍 bun-types [11/12]
error: ConnectionRefused downloading package manifest bun-types
  🔍 figlet [12/12]
error: ConnectionRefused downloading package manifest figlet
error: bun-types@latest failed to resolve
error: figlet@^1.6.0 failed to resolve
bun install  0.02s user 0.02s system 38% cpu 0.100 total
```

**Comment by abdielbrilhante** [comment]
Having this problem in an M1 mac using 1.0.1 too, but it does work if I set IPv6 to link-local only.

**Comment by PrajvalBadiger** [comment]
I am not sure how to configure IPv6 to link-local only on linux.
For me it works when i disable IPv6 in kernel cmdline parameters

```
ipv6.disable=1
```

**Comment by jjhesk** [comment]
same problem with 1.0.2

**Comment by shamiulalamupom** [comment]
I got this when I ran `time bun install`

`bun install v1.0.3 (25e69c71)
  🔍 bun-types [6/6] 
error: FailedToOpenSocket downloading package manifest bun-types
error: bun-types@latest failed to resolve

real    1m5.533s
user    0m0.013s
sys     0m0.005s`

**Comment by giacomo-gagliano-it** [comment]
same here,
I had this issue building a docker from a remote server which is on my local network.
If I build the same image on my machine it works.

```sh
=> [internal] load build definition from Dockerfile                                          0.2s
 => => transferring dockerfile: 378B                                                          0.0s
 => [internal] load .dockerignore                                                             0.3s
 => => transferring context: 2B                                                               0.0s
 => [internal] load metadata for docker.io/oven/bun:latest                                   16.5s
 => [1/5] FROM docker.io/oven/bun:latest@sha256:4b3393b507e40a1a6a4b8d3c47c59a5a733a9f96eb0f  0.0s
 => [internal] load build context                                                             0.0s
 => => transferring context: 752B                                                             0.0s
 => CACHED [2/5] WORKDIR /src                                                                 0.0s
 => CACHED [3/5] COPY . .                                                                     0.0s
 => ERROR [4/5] RUN bun install                                                             311.6s
------                                                                                             
 > [4/5] RUN bun install:                                                                          
0.532 bun install v1.0.3 (25e69c71)                                                                
0.536  Resolving dependencies                                                                      
271.9                                                                                              
271.9 error: ConnectionClosed downloading package manifest bun-types                               
277.0 
277.0 error: ConnectionClosed downloading package manifest page
282.0 
282.0 error: ConnectionClosed downloading package manifest rehype-sanitize
287.0 
287.0 error: ConnectionClosed downloading package manifest rehype-stringify
292.0 
292.0 error: ConnectionClosed downloading package manifest remark-frontmatter
297.1 
297.1 error: ConnectionClosed downloading package manifest remark-gfm
302.1 
302.1 error: ConnectionClosed downloading package manifest remark-parse
310.5  Resolved, downloaded and extracted [185]
310.6 error: bun-types@latest failed to resolve
310.6 error: page@^1.11.6 failed to resolve
310.6 error: rehype-sanitize@^6.0.0 failed to resolve
310.6 error: rehype-stringify@^10.0.0 failed to resolve
310.6 error: remark-frontmatter@^5.0.0 failed to resolve
310.6 error: remark-gfm@^4.0.0 failed to resolve
310.6 error: remark-parse@^11.0.0 failed to resolve
```

dockerfile is pretty simple straight forward:

```Dockerfile
# Usa un'immagine base leggera di Linux
FROM oven/bun:latest as builder

# Copia i file sorgente nella directory del builder
WORKDIR /src
COPY . .

# Installa le dipendenze e esegui il comando yarn build per compilare i file
RUN bun install
RUN bun run build

# Avvia Lighttpd quando il contenitore viene eseguito
CMD ["bun", "run", "run"]
```

the behave doesn't seem to be consistent.
I successfully built couple of images, but this one seems to have issues.

**Comment by acro5piano** [comment]
Fixed by this:

https://wiki.archlinux.org/title/IPv6#Disable_IPv6


```sh
# /etc/sysctl.d/40-ipv6.conf

# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
```

Then run `sudo systemctl restart systemd-sysctl.service`

**Comment by christiannaths** [comment]
Can confirm this is still an issue for `bun 1.0.4`, I was able to work around on macos by setting IVP6 to "Link-local Only" in system settings. Including screenshot here in case it saves someone else a bit of time

<img width="668" alt="Screenshot 2023-10-08 at 9 37 37 AM" src="https://github.com/oven-sh/bun/assets/11584/7435e839-5ec0-4177-aecf-bd596a267bf1">

---
**Original error**

### What version of Bun is running?

```
$ bun --revision
1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b
```


### What platform is your computer?
```
Darwin mbp-16.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64 i386
```

### What steps can reproduce the bug?

```
$ bun create elysia hi-elysia
```

### What do you see instead?

```
error: ConnectionRefused

----- bun meta -----
Bun v1.0.4 (745b6b94) macOS x64 22.6.0
CreateCommand:
Elapsed: 75020ms | User: 20ms | Sys: 6ms
RSS: 6.80MB | Peak: 6.80MB | Commit: 34.61MB | Faults: 0
----- bun meta -----

0   0x103a9d8d0 WTFGetBacktrace

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.4-1696777966674.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

**Comment by Kitanga** [comment]
So yes, disabling or preferring IPv4 is the correct solution. Here's the process for WSL:

Open this `/etc/gai.conf` config file using this command: `sudo vi /etc/gai.conf`

Either add or uncomment this line `precedence ::ffff:0:0/96 100`, uncommenting is removing the `#` sign.

Tap Esc key and then type `:w` to save file. Close and reopen terminal, `bun install` should install now.

**N.B.:** This will **PREFER** IPv4 not necessarily turn IPv6 off.

**Comment by godismyjudge95** [comment]
Can confirm this is an issue on bun 1.0.21.
Disabling IPv6 solved the issue.
(On Debian 11)

**Comment by YoavCodes** [comment]
might be related. I get this while trying to `bun install` or `bun add` anything on an old intel mac (it's so old the latest OS available for it is Big Sur)

The error is slightly different to above 
`failed to initialize compression stream downloading package manifest`

I tried disabling IPv6 as best I could but wasn't able to move forward

![Screen Shot 2024-01-03 at 1 29 51 PM](https://github.com/oven-sh/bun/assets/75102186/fa20e7a0-c914-4952-924e-18a9516ca461)

**Comment by rinvii** [comment]
I'm also getting the same error on an old intel mac bun 1.0.21

`failed to initialize compression stream downloading package manifest`

I set ipv6 to link-local only, but that didn't work.

**Comment by baptistecs** [comment]
Hi,

Same here on a Macbook pro Mid 2014 (Intel) and MacOS Big Sur 11.7.10.

This is specific to Bun v1.0.21, it works well on v1.0.20:

```shell
bun add v1.0.21 (837cbd60)
  🔍 cowsay [6/6] 
error: failed to initialize compression stream downloading package manifest cowsay
error: cowsay@ failed to resolve

cd ..
rm -rf .bun 
curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.20"
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
Run 'bun --help' to get started
cd quickstart 
bun install cowsay
bun add v1.0.20 (09d51486)

 + @types/bun@1.0.0

 installed cowsay@1.5.0 with binaries:
  - cowsay
  - cowthink

 36 packages installed [1.52s]
```

**Comment by baptistecs** [comment]
Other thread on the same issue there:
https://discord.com/channels/876711213126520882/1192197434827345930/1192233818220924948

@Jarred-Sumner

**Comment by guotie** [comment]
yes, it's the IPV6 problem.

**Comment by WeetA34** [comment]
> Hi,
> 
> Same here on a Macbook pro Mid 2014 (Intel) and MacOS Big Sur 11.7.10.
> 
> This is specific to Bun v1.0.21, it works well on v1.0.20:
> 
> ```shell
> bun add v1.0.21 (837cbd60)
>   🔍 cowsay [6/6] 
> error: failed to initialize compression stream downloading package manifest cowsay
> error: cowsay@ failed to resolve
> 
> cd ..
> rm -rf .bun 
> curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.20"
> ######################################################################## 100.0%
> bun was installed successfully to ~/.bun/bin/bun 
> Run 'bun --help' to get started
> cd quickstart 
> bun install cowsay
> bun add v1.0.20 (09d51486)
> 
>  + @types/bun@1.0.0
> 
>  installed cowsay@1.5.0 with binaries:
>   - cowsay
>   - cowthink
> 
>  36 packages installed [1.52s]
> ```

Same "failed to initialize compression stream downloading package manifest xxx" error on macbook intel Big Sur.
Wifi with Configure IPv6 set to Link-Local only
Thank you for the tips of going back to 1.0.20

No issue on MacBook arm Sonoma

**Comment by yangfan-coder** [comment]
Is there any way to solve it? I also encountered such a problem

**Comment by baptistecs** [comment]
Check my link on Discord, you can set an environment variable in front of
“bun install”

**Comment by baptistecs** [comment]
BUN_DISABLE_COMPRESSION_FRAMEWORK=1 bun install

**Comment by silvio2402** [comment]
I'm getting this error when `bun install`ing while being connected to my mobile hotspot:
```
bun i --verbose
[0.04ms] ".env.local"
bun install v1.0.26 (c75e768a)
Loaded 1645 hoisted_dependencies
Loaded 3185 resolutions
Loaded 3185 dependencies
Loaded 40 extern_strings
Loaded 115077 string_bytes
Enqueue package manifest for download: prisma-case-format
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 prisma-case-format [6/6] 
error: FailedToOpenSocket downloading package manifest prisma-case-format
warn: warn: FailedToOpenSocket downloading package manifest prisma-case-format

warn: warn: FailedToOpenSocket downloading package manifest prisma-case-format

warn: warn: FailedToOpenSocket downloading package manifest prisma-case-format

warn: warn: FailedToOpenSocket downloading package manifest prisma-case-format

warn: warn: FailedToOpenSocket downloading package manifest prisma-case-format
error: prisma-case-format@^2.2.1 failed to resolve
```

Are there plans to fix support for IPv6 or is this just temporarily unsupported?

**Comment by terminaldweller** [comment]
disabling ipv6 is not a solution.

**Comment by escwxyz** [comment]
Any update on this? Issue still persists with v1.1.0 even when IPV6 disabled or env var passed. 

I am on macOS 14.3 M1 Max.

**Comment by JhonierNegrete10** [comment]
I encountered the issue while trying to download the package manifest for the create-astro package in Bun and Astro. The error message `error: ConnectionRefused downloading package manifest create-astro` followed by `error: create-astro@latest failed to resolve` is displayed when attempting to create a new Astro project using the command `bun create-astro@latest app --yes`.

Additionally, I faced a similar problem when trying to create a React app using the command `bun create react my-app` and `create astro@latest -- --template framework-react`. However, the `bun init` command runs without any issues.

I performed these attempts within a Docker environment using the following Dockerfile and Docker Compose configuration:

Dockerfile:
```Dockerfile
FROM oven/bun:latest
WORKDIR /app
RUN bunx create-astro@latest app --yes
USER bun
EXPOSE 4321/tcp
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

Docker Compose:
```yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./app:/app
```

It seems that the issue arises specifically when trying to download the package manifest and resolve dependencies within the Docker environment. The create-astro and React app creation commands fail to resolve dependencies properly, resulting in the mentioned errors.

I would appreciate any guidance or assistance in resolving this issue to successfully create Astro and React projects within the Docker environment using Bun.

**Comment by PeterlitsZo** [comment]
I am using a proxy on MacOS.

The origin config is:

```
export HTTP_PROXY=http://localhost:7890
export http_proxy=http://localhost:7890
export HTTPS_PROXY=http://localhost:7890
export https_proxy=http://localhost:7890
```

Another tools works well but Bun does not. I change the `localhost` to `127.0.0.1` and now it works.

**Comment by riezahughes** [comment]
Looking for a solution for this as well

**Comment by ricsam** [comment]
It worked for me when I disabled the global cache. (It might be that I have invalid entries in my global cache?) I added this to mu bunfig.toml file:

```toml
[install.cache]
# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = true

# when true, always resolve the latest versions from the registry
disableManifest = false
```

https://bun.sh/docs/install/cache

**Comment by kevin-lindsay-1** [comment]
I'm getting this issue, too. Never encountered a package manager where downloading is such a problem...

**Comment by OmkarKirpan** [comment]
> Can confirm this is still an issue for `bun 1.0.4`, I was able to work around on macos by setting IVP6 to "Link-local Only" in system settings. Including screenshot here in case it saves someone else a bit of time
> 
> <img alt="Screenshot 2023-10-08 at 9 37 37 AM" width="668" src="https://private-user-images.githubusercontent.com/11584/273458671-7435e839-5ec0-4177-aecf-bd596a267bf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjg3MjIsIm5iZiI6MTcxNjAyODQyMiwicGF0aCI6Ii8xMTU4NC8yNzM0NTg2NzEtNzQzNWU4MzktNWVjMC00MTc3LWFlY2YtYmQ1OTZhMjY3YmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZDZjMmYyZjcxZDliNDNhN2MwZDk5MjllOTg2YTA5ZTAyNmFjZDk0MGMyNmFkNDUzZGZlMGU3MTJiOGQ5NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JdPY4YXLFUEUPDR0RVkSxkEl5Su653vDhyYSeuIOOAk">
> **Original error**
> 
> ### What version of Bun is running?
> ```
> $ bun --revision
> 1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b
> ```
> 
> ### What platform is your computer?
> ```
> Darwin mbp-16.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64 i386
> ```
> 
> ### What steps can reproduce the bug?
> ```
> $ bun create elysia hi-elysia
> ```
> 
> ### What do you see instead?
> ```
> error: ConnectionRefused
> 
> ----- bun meta -----
> Bun v1.0.4 (745b6b94) macOS x64 22.6.0
> CreateCommand:
> Elapsed: 75020ms | User: 20ms | Sys: 6ms
> RSS: 6.80MB | Peak: 6.80MB | Commit: 34.61MB | Faults: 0
> ----- bun meta -----
> 
> 0   0x103a9d8d0 WTFGetBacktrace
> 
> Crash report saved to:
>   ~/.bun/.bun-crash/v1.0.4-1696777966674.crash
> 
> Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
> ```

I'm getting this issue, too. Above workaround worked for me.

**Comment by chuck1in** [comment]
## Enviroment

**Mac OS 13.6.7 (22G720)**
**Docker version 26.1.3, build b72abbb**
**Orbstack Version 1.6.4 (17192)**

## Dock file
```docker
FROM oven/bun:1.1.20 AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production
```
Run `docker build .` and get error out put bottom

```
[+] Building 13.2s (9/17)                                                                                                                   docker:orbstack
 => [internal] load build definition from Dockerfile                                                                                                   0.3s
 => => transferring dockerfile: 1.19kB                                                                                                                 0.0s
 => [internal] load metadata for docker.io/oven/bun:1.1.20                                                                                             8.1s
 => [internal] load .dockerignore                                                                                                                      0.3s
 => => transferring context: 5.26kB                                                                                                                    0.0s
 => [internal] load build context                                                                                                                      2.3s
 => => transferring context: 19.08kB                                                                                                                   2.1s
 => [base 1/2] FROM docker.io/oven/bun:1.1.20@sha256:2dd4542c8316d72cb627f0595540b5e34429e7246aded8db69535e0e65437d89                                  0.0s
 => CACHED [base 2/2] WORKDIR /usr/src/app                                                                                                             0.0s
 => CACHED [install 1/6] RUN mkdir -p /temp/dev                                                                                                        0.0s
 => CACHED [install 2/6] COPY package.json bun.lockb /temp/dev/                                                                                        0.0s
 => ERROR [install 3/6] RUN cd /temp/dev && bun install --frozen-lockfile                                                                              1.3s
------
 > [install 3/6] RUN cd /temp/dev && bun install --frozen-lockfile:
0.981 bun install v1.1.20 (ae194892)
1.021 warn: ConnectionRefused downloading tarball @esbuild/linux-x64@0.21.5
1.021
1.021 warn: ConnectionRefused downloading tarball @rollup/rollup-linux-x64-gnu@4.18.0
1.021
1.021 warn: ConnectionRefused downloading tarball @rollup/rollup-linux-x64-musl@4.18.0
1.021
1.021 warn: ConnectionRefused downloading tarball @pkgjs/parseargs@0.11.0
1.021
1.021 error: ConnectionRefused downloading tarball @playwright/test@1.44.1
1.021
1.021 error: ConnectionRefused downloading tarball @sveltejs/adapter-auto@3.2.2
1.021
1.021 error: ConnectionRefused downloading tarball @sveltejs/kit@2.5.16
1.021
1.021 error: ConnectionRefused downloading tarball @sveltejs/vite-plugin-svelte@3.1.1
1.021
1.021 error: ConnectionRefused downloading tarball @types/eslint@8.56.10
.....
------
Dockerfile:9
--------------------
   7 |     RUN mkdir -p /temp/dev
   8 |     COPY package.json bun.lockb bunfig.toml /temp/dev/
   9 | >>> RUN cd /temp/dev && bun install --frozen-lockfile
  10 |
  11 |     # install with --production (exclude devDependencies)
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /temp/dev && bun install --frozen-lockfile" did not complete successfully: exit code: 1
````

**Comment by ryoppippi** [comment]
I got this issue in this couple of days when I use bunx command

**Comment by moloxe** [comment]
Turning wifi off and on fixed the problem for me, average engineer solution

**Comment by programeoww** [comment]
> Turning wifi off and on fixed the problem for me, average engineer solution

worked for me, absolute engineering solutions

**Comment by escwxyz** [comment]
tried everything mentioned above, issue still persists. Version 1.1.24.

**Comment by F3lip3** [comment]
> Turning wifi off and on fixed the problem for me, average engineer solution

Yeah... worked for me too... lol

**Comment by jeroentvb** [comment]
I had this error because there was an old registry listed in the `.npmrc` in my user folder (windows, using git bash). Bun failed to provide an error message as to what was causing the ConnectionRefused  error, while yarn mentioned it couldn't connect to the old registry.

**Comment by Murchik0v** [comment]
PS C:\Users\2a4ev\oi\dsjs-test> bun add discord.js
bun add v1.1.38 (bf2f153f)
error: UNABLE_TO_GET_ISSUER_CERT downloading package manifest discord.js
как решить эту проблему?

**Comment by hinericubix** [comment]
If you are using WSL on Windows, please check the [Mirrored mode networking](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking). If this setting is enabled, IPv6 is supported and ConnectionRefused may occur. In fact, I turned this setting off and the error went away.

**Comment by sayjeyhi** [comment]
For me the issue was having a root level `.npmrc` which was using my job npm registeration proxy

**Comment by umrashrf** [comment]
For me having https://verdaccio.org/ turned off was the problem with custom .npmrc

**Comment by prantlf** [comment]
How about making the verbose mode more verbose? If it printed the URL, from which it tried to download the `.tgz` file, I'd see right away that it wasn't npmjs.org and I forgot to remove the NPM proxy from `registry` in `~/.bunfig.toml`...

```
❯ bun i --verbose
bun install v1.2.9 (9a329c04)
Enqueue package manifest for download: puppeteer
Enqueue package manifest for download: puppeteer-core
  🔍 Resolving [1/2] [PackageManager] waiting for 2 tasks
[PackageManager] waiting for 2 tasks
[PackageManager] waiting for 2 tasks
[PackageManager] waiting for 2 tasks
[PackageManager] waiting for 2 tasks
[PackageManager] waiting for 2 tasks
[PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
warn: FailedToOpenSocket downloading package manifest puppeteer. Retry 1/5...
warn: ConnectionRefused downloading package manifest puppeteer. Retry 2/5...
...
warn: FailedToOpenSocket downloading package manifest puppeteer-core. Retry 4/5...
warn: ConnectionRefused downloading package manifest puppeteer-core. Retry 5/5...
error: ConnectionRefused downloading package manifest puppeteer
error: FailedToOpenSocket downloading package manifest puppeteer-core
Clean lockfile: 417 packages - 417 packages in 997.1us
error: puppeteer@24.6.1 failed to resolve
error: puppeteer-core@24.6.1 failed to resolve
```

**Comment by KaKi87** [comment]
Hi,

I'm experiencing the same issue where adding dependencies to a project on a work computer made it impossible to install said dependencies from my personal computer.

I would consider it a dirty move to delete the `bun.lock` file.

Is there any Bun command that allows resetting existing packages from the default NPM registry ?

Creating a `~/.bunfig.toml` setting the default NPM registry does not work.

Thanks
