### ISSUE TITLE
Node.JS Compatibility for @sap/hana-client

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#5139]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Running bun from Docker

### What steps can reproduce the bug?

bun add @sap/hana-client
index.js : import hanaclient from '@sap/hana-client';   
run index.js

### What is the expected behavior?

No error

### What do you see instead?

/workspaces/test-bun/node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc6/hana-client.node: undefined symbol: uv_mutex_lock

**Comment by Electroid** [comment]
This issue is caused by #4959, which we will fix.

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave  in #7132

**Comment by alumni** [comment]
I still get the error even with `"trustedDependencies": ["@sap/hana-client"]`:

1. `bun init`
2. update files:

package.json:
```json
{
  ...
  "dependencies": {
    "@sap/hana-client": "^2.19.20"
  },
  "trustedDependencies": ["@sap/hana-client"]
}
```

index.ts:
```ts
import hanaClient from '@sap/hana-client';

console.log(hanaClient.getDriverVersion());
```

3. `bun install`
4. `bun run index.ts`

On MacOS I get: 
```
dyld[...]: missing symbol called
```

Or on Linux: `undefined symbol: uv_mutex_lock`

**Comment by Electroid** [comment]
> I still get the error even with `"trustedDependencies": ["@sap/hana-client"]`:
> 
> 1. `bun init`
> 2. update files:
> 
> package.json:
> 
> ```json
> {
>   ...
>   "dependencies": {
>     "@sap/hana-client": "^2.19.20"
>   },
>   "trustedDependencies": ["@sap/hana-client"]
> }
> ```
> 
> index.ts:
> 
> ```ts
> import hanaClient from '@sap/hana-client';
> 
> console.log(hanaClient.getDriverVersion());
> ```
> 
> 3. `bun install`
> 4. `bun run index.ts`
> 
> On MacOS I get:
> 
> ```
> dyld[...]: missing symbol called
> ```
> 
> Or on Linux: `undefined symbol: uv_mutex_lock`

See #6506, we will fix this issue.

**Comment by gorillamoe** [comment]
I know, this is not ideal, but it's an okay"ish" workaround for me:

I bundle with `bun bundle --target node`, then run the service with `bun --node ./app.js`.

**Comment by gorillamoe** [comment]
I had to roll out an hotfix today, because it's not working as expected. It seems that the Hana client hangs on certain calls with the production build.

It works in dev mode, but with the bundle it doesn't show any errors it just hangs.

The hotfix I deployed was basically just running the bundled app through node like `node app.js` which then works.
