### ISSUE TITLE
Segmentation Fault while doing "bun install" in npm project

### ISSUE THREAD

**Issue by adi-g15** [oven-sh/bun#532]
### Version

0.1.2

### Platform

```
Linux myhostname 5.18.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000 x86_64 GNU/Linux
```

### What steps will reproduce the bug?

Add "@strapi/strapi" to dependencies.

This may require the package.json. Example:

```json
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "dependencies": {
    "@strapi/strapi": "4.1.11"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### How often does it reproduce? Is there a required condition?

Reproduced each time. Tried twice on my system, and once on Google Cloud shell.
Can't find the required condition, other packages work fine. It maybe some package specific issue too, such as depending on some node feature.

### What is the expected behavior?

Expected to install successfully.

### What do you see instead?

Failed to install/add:

```sh
bun install v0.1.2
  🚚 @strapi/helper-plugin [503/1112] 
SegmentationFault at 188


–––– bun meta ––––
Bun v0.1.2 Linux x64 #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000
InstallCommand: 
HTTP: 607
Elapsed: 29541ms | User: 50197ms | Sys: 1515ms
RSS: 0.36GB | Peak: 0.38GB | Commit: 0.36GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**NOTE**: The package **name/count at which the Segmentation Fault occurred was different**:

* 1st time:
   ```
   🔍 html-webpack-plugin [929/1428] 
   SegmentationFault at 0
   ```
* 2nd time:
   ``` 
   🔍 @babel/plugin-transform-modules-umd [1226/1685]
   SegmentationFault at 188
   ```
* 3rd time (in Google Cloud Shell, VM):
   ```
   🚚 @strapi/helper-plugin [503/1112] 
  SegmentationFault at 188
   ```

### Additional information

Other packages, like underscore, could be successfully installed. The **problem's happening only with specifying [strapi](https://github.com/strapi/strapi)** as dependency as of now.

Maybe related to HTTP problems in #337 #490

**Comment by Jarred-Sumner** [comment]
I'm able to reproduce this, but only if I use Network Link Conditioner to set my internet to 3G speed

I believe the cause is some incorrect error handling logic in the HTTP client that tends to only happen with lots of requests taking awhile

**Comment by dqnk** [comment]
This issue also exists for me:

```
bun install v0.1.4
  🔍 caller-id [427/1254] 
SegmentationFault at 188


–––– bun meta ––––
Bun v0.1.4 Linux x64 #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000
InstallCommand: 
HTTP: 638
Elapsed: 28751ms | User: 28909ms | Sys: 301ms
RSS: 0.63GB | Peak: 0.23GB | Commit: 0.63GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```
bun version: 0.1.4 - so not resolved with closing of #337.

**Comment by dqnk** [comment]
After some debugging it seems that my issue is more similar to #499 than this. I will continue there.

**Comment by Jarred-Sumner** [comment]
Should be fixed as of Bun v0.1.12, but possibly earlier than that. Please comment if it isn't.

**Comment by shirtgpt** [comment]
> Should be fixed as of Bun v0.1.12, but possibly earlier than that. Please comment if it isn't.

![image](https://github.com/oven-sh/bun/assets/162694608/3042aec7-d9fa-4438-8ae4-6d85bed3c927)

Still facing it on V1.0.35

**Comment by Jarred-Sumner** [comment]
@jwathika I'm sorry you're running into this, but can you please open a new issue and provide a package.json that reproduces the issue? While the error message is similar, the cause will be very different as Bun's codebase has changed a lot since the time this issue was created.

**Comment by dangenendt** [comment]
Same here within gitlab docker-executor runner in a monorepo

![image](https://github.com/oven-sh/bun/assets/7514758/10e81d42-0d0c-4b20-9108-8f3e607e71a1)

I'll try to provide you a package.json because, as i stated before, this is a monorepo and not that trivial 😆
