### ISSUE TITLE
`bun install` is not recognizing the workspaces anymore

### ISSUE THREAD

**Issue by titanve** [oven-sh/bun#5413]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

run `bun install`

### What is the expected behavior?

to use workspaces correctly as it was doing yesterday

### What do you see instead?

```
error: package "@company/mypackage" not found npm.pkg.github.com/@company/mypackage 404
```

### Additional information

my workspaces section in `package.json` file is:
```
"workspaces": [
    "frontend/mypackage",
    "frontend/myotherpackage",
    "frontend/coolpackage"
  ],
```

my `bunfig.toml` file:
```
[install]
registry = { url = "https://registry.npmjs.org", token ="$NPM_GITHUB_TOKEN" }

[install.scopes]
"@company" = { url = "https://npm.pkg.github.com", token = "$NPM_GITHUB_TOKEN" }
```

**Comment by josefaidt** [comment]
I am having this same issue and came close to opening an issue but thought maybe I had done something wrong. This typically happens when I come back to an open project and run `bun install`. I just have `packages/*` set for workspaces, and this always seem to affect one specific package:

```console
➜  bun install
[0.17ms] ".env.local"
bun install v1.0.0 (822a00c4)


error: workspace dependency "my-package" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces



error: workspace dependency "my-package" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

It's like the lockfile gets clobbered somehow. I'm not sure how to reproduce this either, but as noted this seems to pop up once I come back to an open project.

As a workaround I delete the bun lockfile and reinstall with `bun install`

**Comment by elitan** [comment]
I also had issues with this. Deleting the `bun.lockb` file solved the issue for me.

**Comment by titanve** [comment]
I can confirm that by doing this (removing the `bun.lockb`) the issue is solved:
```
rm -f bun.lockb && bun install
```

**Comment by matallui** [comment]
Still finding the same issue on Bun v1.0.2.

Even thought deleting `bun.lockb` and reinstalling works, it's annoying in my use case.
Every time I'm inside my `apps/web` and run `bunx shadcn-ui@latest add component` I hit the same issue.

The workaround for me is always to temporary remove the workspace dependencies from `apps/web/package.json`, then run the `shadcn-ui` command, then re-add the dependencies, delete `bun.lockb` and rerun `bun install`.

**Comment by paulleonartcalvo** [comment]
Same issue here running 1.0.2. Running install from root appears to work (sometimes I have to delete modules + lock) but doesn't seem to work from within my app when using workspace dependencies.

**Comment by matbour** [comment]
Same issue here. I am migrating from pnpm, I was expecting to have a node_modules in each of packages, but I can only see a root node_modules... Maybe it's linked?

**Comment by paulleonartcalvo** [comment]
I specifically get the `workspace dependency x not found` when running `bun add someDep` from within my `gui/gui-my-app` directory. It only seems to happen when the GUI's dependencies have my `design-system` package as a dependency.

I don't think the details of my project will be super different from anyone else with this issue, but I'll list them anyway for the sake of clarifying possible causes:

My project structure: 

```
.
├── apps
│   └── gui
│       └── gui-my-app
│           ├── package.json
├── package.json
├── packages
│   └── design-system
│       ├── build.ts
│       ├── index.ts
│       ├── package.json
│       ├── src
│       └── tsconfig.json
├── tsconfig.base.json
└── tsconfig.json
```

My root `package.json` has the following:

```
"workspaces": [
    "packages/*",
    "apps/gui/*"
  ]
```

My `design-system/package.json` has the following:

```
"name": "@myAbitraryProjectPrefix/design-system",
...
```

And finally my `gui/gui-my-app/package.json` has the following:

```
"name": "@myAbitraryProjectPrefix/gui-my-app",
"dependencies": {
...,
"@myAbitraryProjectPrefix/design-system": "workspace:*",
...
}
```

I don't personally have a ton of experience with workspaces, but I migrated this structure from `pnpm` where it worked without issues.

**Comment by OyvindSigvaldsen** [comment]
I am experiencing the same issue using Bun v1.0.2.

**Comment by jfcieslak** [comment]
Currently, the workspaces resolution implementation seems to be very buggy. The example reffered to in the [workspaces guide](https://bun.sh/guides/install/workspaces) is not working either. Here are the issues that I found out during experimenting.

1. Bun uses package version (`workspace:*`) as a relative path to find a package.
That is why it returns this error, because it litereally searches in "./*" relative to where you run the command from:
```
error: workspace dependency "my-package" not found
Searched in "./*"
Workspace documentation: https://bun.sh/docs/install/workspaces
```
Experimenting with versions like: `"my-package":"workspace:../*"` can work, if you run, for example,  a `bun add some-npm-pkg` command from a matching relative path. But this is of course totally wrong.

2. Linking packages may resolve correctly
If you link all your workspace packages (`bun link`) then you can refer to them in the version as `"my-package":"link:my-package"` and it usually works, but then you are not really using workspaces

**Comment by maxxborer** [comment]
Did this work on previous versions?

**Comment by paulleonartcalvo** [comment]
> Did this work on previous versions?

Not that i know of

**Comment by rossanmol** [comment]
Experiencing some issue, very unpleasant to work with workspaces atm :(

**Comment by yentlprojects** [comment]
> Did this work on previous versions?

I reverted to 0.8.x and same problems seem to be happening there.

**Comment by JoltCode** [comment]
Yeah I'm having this issue on the latest bun version too

**Comment by gabrielmfern** [comment]
can confirm this problem with 1.0.3 as well

**Comment by medeiroshudson** [comment]
same here. had to perform an `rm -f bun.lockb` before install

**Comment by mateusavila** [comment]
For me, only works if I insert the full address of the package:

"dependencies": {
    "@bun-rpg/zod-validators": "workspace:../../packages/@bun-rpg/zod-validators",
}

the workspace is: 

{
  "name": "bun-rpg",
  "version": "1.0.0",
  "type": "module",
  "private": true,
  "workspaces": [
    "packages/*",
    "apps/*"
  ]
}

**Comment by ricklove** [comment]
This is happening often whenever something changes in any package.json.

But the workaround seems to work each time: `rm -f bun.lockb && bun install`

**Comment by Jarred-Sumner** [comment]
@dylan-conway is working on this

**Comment by prodkt** [comment]
Had time to give bun a spin today on a new project and unfortunately in the first 15 minutes I was also plagued by this. I couldn't overcome it and had to pivot. Looks promising though I'll keep an eye out for when the fix is implemented to give it another shot.

https://github.com/oven-sh/bun/assets/101760605/21ee4388-ea2a-439f-b44d-19a8b6d0cb66

**Comment by Jarred-Sumner** [comment]
Narrowed down the cause. The code for checking if the package.json has changed is diffing the root package.json compared to the workspace child package.json when the cwd is not the root and it is a reinstall with changes.

There was also a cache invalidation issue in the http client which was fixed a couple days ago.

**Comment by JoltCode** [comment]
@Jarred-Sumner Please can you confirm if this has now been fixed in Bun v1.0.4? Thanks so much 😄!

**Comment by Jarred-Sumner** [comment]
@dylan-conway has fixed this in v1.0.4. Please run `bun upgrade` and leave a comment if you see it still

**Comment by jfcieslak** [comment]
thx @Jarred-Sumner, it seems to be working as expected now 👌

**Comment by matallui** [comment]
@Jarred-Sumner I'm still seeing issues with my monorepo, even after recreating the bun.lockb file.

I've made this repo public [here](https://github.com/matallui/issue-bun-workspaces).

Just clone it and then:
 - `bun i`
 - `cd apps/www`
 - `bun add tailwindcss-animate`
 
 ```
❯ bun add tailwindcss-animate
bun add v1.0.4 (ea956e58)
  🔍 @mono/eslint-config [1/14]
error: package "@mono/eslint-config" not found registry.npmjs.org/@mono%2feslint-config 404
  🔍 @mono/prettier-config [2/14]
error: package "@mono/prettier-config" not found registry.npmjs.org/@mono%2fprettier-config 404
  🔍 @mono/tailwind-config [3/14]
error: package "@mono/tailwind-config" not found registry.npmjs.org/@mono%2ftailwind-config 404
  🔍 @mono/tsconfig [9/17]
error: package "@mono/tsconfig" not found registry.npmjs.org/@mono%2ftsconfig 404
error: @mono/eslint-config@* failed to resolve
error: @mono/prettier-config@* failed to resolve
error: @mono/tailwind-config@* failed to resolve
error: @mono/tsconfig@* failed to resolve

```

EDIT: Turns out if I switch the versions of the workspace packages from `*` to `workspace:*` that seems to work. So I guess we can ignore the issue, unless `*` is supposed to be supported as well.

**Comment by paulleonartcalvo** [comment]
> @Jarred-Sumner I'm still seeing issues with my monorepo, even after recreating the bun.lockb file.
> 
> I've made this repo public [here](https://github.com/matallui/issue-bun-workspaces).
> 
> Just clone it and then:
> 
> * `bun i`
> * `cd apps/www`
> * `bun add tailwindcss-animate`
> 
> ```
> ❯ bun add tailwindcss-animate
> bun add v1.0.4 (ea956e58)
>  🔍 @mono/eslint-config [1/14]
> error: package "@mono/eslint-config" not found registry.npmjs.org/@mono%2feslint-config 404
>  🔍 @mono/prettier-config [2/14]
> error: package "@mono/prettier-config" not found registry.npmjs.org/@mono%2fprettier-config 404
>  🔍 @mono/tailwind-config [3/14]
> error: package "@mono/tailwind-config" not found registry.npmjs.org/@mono%2ftailwind-config 404
>  🔍 @mono/tsconfig [9/17]
> error: package "@mono/tsconfig" not found registry.npmjs.org/@mono%2ftsconfig 404
> error: @mono/eslint-config@* failed to resolve
> error: @mono/prettier-config@* failed to resolve
> error: @mono/tailwind-config@* failed to resolve
> error: @mono/tsconfig@* failed to resolve
> ```
> 
> EDIT: Turns out if I switch the versions of the workspace packages from `*` to `workspace:*` that seems to work. So I guess we can ignore the issue, unless `*` is supposed to be supported as well.

This issue was with the docs and was updated some time ago. I believe they have been updated to `workspace:*` :)

**Comment by chakrihacker** [comment]
Can we reopen this issue @Jarred-Sumner ??

**Comment by Jarred-Sumner** [comment]
@chakrihacker please include a reproduction of the issue you’re running into. The original issue here is fixed, so a different one needs a new reproduction for us to fix it

**Comment by btakita** [comment]
I'm having an issue with bun not recognizing packages in a monorepo using git submodules.

```
(cd lib/ui--server--blog; bun add @btakita/domain--server)
[0.00ms] ".env"
bun add v1.0.4 (745b6b94)
  🔍 @btakita/domain--server [1/1]
error: package "@btakita/domain--server" not found registry.npmjs.org/@btakita%2fdomain--server 404
```

To reproduce:

```
git clone git@github.com:btakita/dev.git
cd dev
git submodule init
git submodule update
bun install
```

**Comment by satyavh** [comment]
this fixes it for me
`"some-package-in-workspace": "workspace:path/to/some-package-in-workspace"`

in other words, put the full relative path to the package in your workspace

> Bun supports simple <directory>/* globs in "workspaces".  
In other words, that section in the documentation isn't true anymore. Globe support is broken

**Comment by nyxb** [comment]
error still exists in version 1.0.14 you always have to delete the lock file. A fix would be nice. But thanks for the info on how to solve it.

**Comment by mxvsh** [comment]
> @dylan-conway has fixed this in v1.0.4. Please run `bun upgrade` and leave a comment if you see it still

still same, it doesn't work on version 1.0.14

**Comment by btakita** [comment]
After upgrading to v1.0.15, I'm unable to install workspace dependencies even after deleting bun.lockb. Downgrading to v1.0.14 fixes the issue.

```
curl -fsSl https://bun.sh/install | bash -s "bun-v1.0.14"
```

**Comment by daedlock** [comment]
Please fix this in HEAD. I also had to downgrade to `1.0.14`

**Comment by goldo** [comment]
I also have the problem (v1.0.16) I think we should re-open it

**Comment by btakita** [comment]
I fixed my issue by adding the "version" field to package.json

edit

See https://github.com/oven-sh/bun/issues/7433

Also note that you can use other means to install the packages, such as yarn or pnpm.

**Comment by corrm** [comment]
Same for `v1.0.22` had to delete `bun.lockb`

```
bun install --verbose
bun install v1.0.22 (b400b36c)
Loaded 7 hoisted_dependencies
Loaded 8 resolutions
Loaded 8 dependencies
Loaded 4 extern_strings
Loaded 498 string_bytes
   - "contracts": "packages/contracts" - contracts@workspace:packages/contracts
   - "core": "packages/core" - core@workspace:packages/core
error: workspace dependency "contracts" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

**Comment by Hatko** [comment]
The solution with deleting `bun.lockb` doesn't work anymore for `1.0.23` and `1.0.24`

**Comment by dawsondellavalle** [comment]
I encountered this in `v1.0.25`.

Using relative paths from the dependent package in its `package.json` fixed the issue.

```
"@company/core": "workspace:../core"
```

**Comment by DayFlo** [comment]
Also encountered this on `v1.0.25`.

I changed a package name from `packagex` to `packagey` and updated the dependencies only to run `bun install` getting the error:
```
error: workspace dependency "@packagey/util" not found

Searched in "./*"
```

Simple resolution was to find the related dependency in each package.json and update the semver token (`^`/`~`/`*`) to something different with each package name change, which looked like this:
```
  // package.json
  "name": "api",
  "dependencies": {
      "@packagey/util": "workspace:^",
   }
```
On the next package name change I would need to go from `workspace:^` to `workspace:*`.

**Comment by algoflows** [comment]
Same problem for using the latest Bun, been stuck on this for two days as Vercel won't deploy my svelte app as the SvelteKit workspace import of my shared components library won't resolve in CI!!! Two days, trying to get a SvelteKit app deployed. Hope Bun can roll a fix and get workspaces back on track.

**Comment by algoflows** [comment]
Okay so update on findings. Railway deploys the app fine but Vercel doesn't. My theory is that Vercel is running an older version of Bun without the workspace fix. @Jarred-Sumner

**Comment by robertherber** [comment]
For us the big problem right now is installing packages in our monorepo:
- `bun install any-npm-pkg` will only install the package to the root package.json
- `bun add any-pkg` will install it in the closest package.json, but will ruin the lockfile (only adding the dependencies for that closest package.json). It can be repaired by running a new `bun install` after, but that will end up upgrading packages we did not intent to touch (since the lockfile is broken).

The two workarounds I see working now:
- Go manually into package.json and add any-pkg, run `bun install`.
- Run `bun install any-pkg` and then manually copy the version specification from the root package.json to the project package.json.

Neither of them feels really good :)

**Comment by matallui** [comment]
Yeah, I'm experiencing the same issue as @robertherber

**Comment by alsa32** [comment]
Same issue here @robertherber

**Comment by robertherber** [comment]
We have a new workaround:
```TypeScript
#!/usr/bin/env bun
/* eslint-disable no-unused-expressions */
import { $ } from 'bun'

const args = process.argv.slice(2)

await $`bunx add-dependencies ${args.join(' ')}`

await $`bun install`
```

Feel free to use it through [@zemble/utils](https://github.com/kingstinct/zemble/blob/main/packages/utils/scripts/add-safe.ts) or copy-paste it into your own project. It uses [add-dependencies](https://www.npmjs.com/package/add-dependencies) to just add the entry to the closest package.json without actually installing it and runs a subsequent `bun install`.

@Jarred-Sumner I think getting this working properly by default is important, I'm guessing this is a biggie for all monorepos.

**Comment by shoxsz** [comment]
Hello guys, just confirming this issue is still happening, do we have a plan for a fix? it is really frustrating, we could at least update the `workspaces` page in the docs to notify about this issue, I just lost 1 hour trying to figure this out, really frustrating because all other package managers have this figured out.

**Comment by tgrushka** [comment]
Wow, this is bad. What the heck? Tell us in the instructions to delete the lockfile, or have a flag to automatically delete it.

Workspaces are very annoying in bun. I love bun except for this. You can't even build a specific subpackage of a monorepo workspace, you have to deploy all of the workspace dependencies to a container.

**Comment by christian-hackyourshack** [comment]
For this reason I gave up on Bun's workspaces for now, but if I shall consider Bun for production projects this would be a no-go.

**Comment by btakita** [comment]
To consolidate the issues, I see the following:

|                                                                             issue | workaround                                 |
|-----------------------------------------------------------------------------------|--------------------------------------------|
|                                    Cannot install workspace packages from the cli | Add the dependency in package.json instead |
|                    Package not found or bin file not added to `node_modules/.bin` | `rm bun.lockb && bun i`                    |
| `error: No version matching "..." found for specifier "..." (but package exists)` | `bun pm cache rm && bun i`                    |

Other than these issues, each of which has mitigations, bun workspaces seem to work for me. Are there any other issues to make a complete list of issues + workarounds?

To be fair to the Bun team...Bun is a new project making impressive progress. Monorepos are difficult. I have encountered inconveniences but no blocking issues. Other monorepo libraries (like yarn & pnpm) had issues over the years. If these issues make development intolerable, you can use another package manager like pnpm or yarn with bun.

**Comment by MariuzM** [comment]
bun with `1.0.29` still issue
<img width="1496" alt="image" src="https://github.com/oven-sh/bun/assets/36937039/fad9602f-dd19-431b-a0a8-2deeeef14a3a">

**Comment by MariuzM** [comment]
O have this working -> https://github.com/MariuzM/bun-workspace

<img width="1212" alt="image" src="https://github.com/oven-sh/bun/assets/36937039/29d248cc-1618-4e55-9258-0be019eb017e">

**Comment by Jarred-Sumner** [comment]
We will prioritize fixing this shortly after Bun v1.1

**Comment by MariuzM** [comment]
Just doing more examples if it helps. 

`app1` is React Vite - Works fine
`app2` is React Native Expo - Getting node modules issue. When you start the app it builds fine up to the Simulator screen and even shows the app, but after that getting error. In this case its not looking in `root` for node_modules but in project.

```
        throw new UnableToResolveError(
              ^
Error: Unable to resolve module ./node_modules/expo-router/entry from /Volumes/Dev/bun-workspace/apps/app2/.: 
```

Repo: https://github.com/MariuzM/bun-workspace/tree/main

My testing process:
1. Nuke all `node_modules` and `*.lock` files from all folders.
2. Run `bun install` from `root`
3. Run `bun app1` (works fine)
4. Run `bun app2` (error)

**Comment by danditomaso** [comment]
So I recently added bun workspace support to my app, and came across this thread. After realzing my app folders weren't actually underneth a packages folder and prompt moved, everything seemed to work pretty seemlessly. 

I'll outline how I got this working in my project and hopefully that helps anyone on this thread who is still having problems. 

1) Just like @MariuzM suggested, nuke your `node_modules` and any bun.lock, or package-lock, or just any lock files. It helps to start with a clean slate. 
2) If your parent folder is named `foo` ensure your apps/libraries are under a `packages` folder,  your directory structure should look something like this: `foo\packages\web` OR `foo\packages\api`.
3) The `name` field in all package.json files should use valid characters (and @ isn't a supported character). The NPM site has the following recommendations on package naming: `The "name" field contains your package's name, and must be lowercase and one word, and may contain hyphens and underscores.` 
4) Add workspaces support to your root package.json file, add the following line to your package.json: 
`"workspaces": ["packages/*"]`

5) BEFORE GOING FURTHER, open a terminal window and run `bun install` in your parent `foo` folder. The output should similar, if you see anything that looks like an error post it here: 
<img width="349" alt="image" src="https://github.com/oven-sh/bun/assets/12192153/b2fda433-af33-4d6f-bab7-e3031ae22b49">

6)  I did this by manually editing my `api` package.json file, but to add a workspace dependency (in my case adding a workspace dependancy to my db folder), you can add something like the following to either your `dependencies` or `devDependencies` `"db": "workspace:*"`. Assuming Step 4 went smoothly, run `bun install` in this child package folder and it should show output like the screenshot above. 

Thats it! You are now able to use ESM import syntax to import a dependency from another package in your workspace. 

I know this became a bit verbose, but hopefully it helps someone out who has been struggling with bun workspace support.

**Comment by dsogari** [comment]
I also recently added workspace support to my app, and was getting the following error:

    error: workspace dependency "<redacted>" not found
    
    Searched in "./packages/<redacted>"

I was able to overcome this by just removing the `bun.lockb` file and running `bun install` again.

**Comment by kaumac** [comment]
Really hope this would be fixed. I'm migrating an npm monorepo to use bun and wasted hours trying to figure this out :(

**Comment by Jarred-Sumner** [comment]
Bun v1.1 is shipped. We will prioritize fixing this.

**Comment by dror-weiss** [comment]
I have a multi-level workspaces setup, e.g.
```
.
├── package.json
├── packages
│   └── service
│       │     └── functions
│       │         ├── package.json
│       │         ├── src
│       │        └── tsconfig.json
│       ├── package.json
│       ├── src
│       └── tsconfig.json
```

I noticed that a single-level workspaces setup (`packages/*`) works, while my multi-level (`packages/*/*`) doesn't.

**Comment by hbthegreat** [comment]
Removing bun.lockb and running bun install is unfortunately not fixing this for me. I might be dreaming but I feel it was working a week or two ago.

**Comment by mtoader** [comment]
I see this when trying to import a named root package.json from a mononode workspace. E.g., something like this: 
```
root:
 | package.json -> 
        "name": "@scope/root"
 | child:
    + package.json -> 
           "name", "@scope/child", 
           "devDependencies:": {
              "@scope/root": "workspace:*"
           }
```
 will consistently fail with: `failed to resolve "@scope/root"` message like above.,

Still fails with `1.1.3`

**Comment by lackita** [comment]
Slightly different datapoint to help y'all with your investigations now that 1.1 is released. I can run `bun install` fine locally, and even had a primitive `Dockerfile` that was building the container as `root`. When I added in `USER bun`, though, this issue started showing up right away.

EDIT: Then again, maybe not, if I run `chown -R bun .` before changing the user things seem to work.

**Comment by wallpants** [comment]
I got this error on 1.1.8, downgraded to 1.1.7 and error went away

**Comment by amjed-ali-k** [comment]
![image](https://github.com/oven-sh/bun/assets/86785660/53d39c5e-451e-4757-8983-c61fa19b2720)
Downgrading bun worked.

**Comment by michealroberts** [comment]
Looks like this error has returned ... how disappointing.

**Comment by thecrabcode** [comment]
Any plan on sorting this out, it is quite annoying as a bug and I assume it will prevent lots of people from upgrading.

**Comment by tecoad** [comment]
Also confirm downgraded from 1.1.8 to 1.1.7 fixed it.

**Comment by kimjisena** [comment]
> Still finding the same issue on Bun v1.0.2.
> 
> Even thought deleting `bun.lockb` and reinstalling works, it's annoying in my use case. Every time I'm inside my `apps/web` and run `bunx shadcn-ui@latest add component` I hit the same issue.
> 
> The workaround for me is always to temporary remove the workspace dependencies from `apps/web/package.json`, then run the `shadcn-ui` command, then re-add the dependencies, delete `bun.lockb` and rerun `bun install`.

I'm also experiencing this issue. This workaround works but it is very annoying.

**Comment by Jarred-Sumner** [comment]
This PR by @dylan-conway https://github.com/oven-sh/bun/pull/11177 aims to address this, along with the regression in Bun v1.1.8.

**Comment by MathewsJoseph25** [comment]
@Jarred-Sumner Adding to this, the env variable is not being pulled from root now. It was working earlier. I created a [issue](https://github.com/oven-sh/bun/issues/11190) and then found this thread.

**Comment by benschac** [comment]
`"<package-name>": "*"` works for me atm.

**Comment by amjed-ali-k** [comment]
Seems fixed in Bun 1.1.9

**Comment by rholang** [comment]
I had the problem that I installed the new tailwind version in my workspace folder. Then I changed tha package.json version of tailwind to the old one back. But in the node_modules (not the root one) in my workspace folder was still the other version. I have bun v1.1.10.

**Comment by Jarred-Sumner** [comment]
I think this can be closed now, as of Bun v1.1.11/v1.1.12. The immediate issue was fixed in v1.1.9, however there were some important follow-up fixes after that. Bun v1.1.13 will also add more improvements to workspaces in Bun (which releases tomorrow)

If you continue to experience problems when using workspaces in bun, please file a new issue with a reproduction and we will fix it

**Comment by crazytweeks** [comment]
**Issue still persists in bun version 1.1.20 and 1.1.21**

![image](https://github.com/user-attachments/assets/8f92302c-e363-4d64-b7cf-de7c7306c9ea)


bun install works perfectly from root project of monorepo.
I am using turborepo

I cannot add any npm packages to any of my sub projects. I need to remove packages with the version "workspace:*" from package.json of that sub application. and run 'bun add <package_name>'. and then re add those workspace projects manually in package.json, go back to root and re run 'bun i'. This long method works. 
But its frustrates to manually add packages every time.

![image](https://github.com/user-attachments/assets/c26b5963-1843-426c-8882-0e18f678b221)

Why is it searching for package from ..\..\..\..\..\E:\bun\flash\apps\portal\*
On windows, there is no such path. Is there any way i can configure project to look for packages only one or two path above, like '../../**'

`My package.json in root already includes workspaces option
```
"workspaces": ["apps/*", "packages/*"]
```

**Comment by Jarred-Sumner** [comment]
@crazytweeks please file a new issue. We will fix it, but what you're seeing is a bug in how we handle Windows file paths, likely related to the E:\ drive letter (as opposed to the C:\ drive letter) and this issue was originally happening in all cases when installing from a subdirectory of a workspace. It would be especially helpful if you can provide a reproduction in the new issue.
