### ISSUE TITLE
Next.js with bun: Failed to construct 'Request': signal is not of type AbortSignal.

### ISSUE THREAD

**Issue by golamrabbiazad** [oven-sh/bun#5649]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

nextjs app run using `bun --bun run dev` or `bun --bun next dev`.

![image](https://github.com/oven-sh/bun/assets/35021384/c82f9908-56f9-42a0-96b1-a17e8e6cf78c)

### Additional information
![image](https://github.com/oven-sh/bun/assets/35021384/b340fff4-4064-4187-a9d1-2fb3c41d0bba)

_No response_

**Comment by The-Code-Monkey** [comment]
Getting this on the M2 mac book pro too.

**Comment by ericklarsen** [comment]
I think this issue related with this #5503

**Comment by Jarred-Sumner** [comment]
This was fixed in #5503. It will be part of Bun v1.0.3. 

To upgrade ahead of time:
```bash
bun upgrade --canary
```

**Comment by JasmailDuck** [comment]
Still getting errors on 1.0.3 `error: Invariant: Render expects to have staticGenerationAsyncStorage, none found` 
Ran this in wsl and native Linux.
