### ISSUE TITLE
Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by christoph88** [oven-sh/bun#5997]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run ```bun init```and add following code to index.ts.

```
const { input } = require("@inquirer/prompts");

const ask = async () => {
  const answer = await input({ message: "Enter your name" });
  console.log(answer);
  return answer;
};

ask();
```

Run ```bun install @inquirer/prompts``` then run ```bun run index.ts````

You will get this error. It works when setting up the project as a node app

```
❯ bun run index.ts 
? Enter your name
120 | 
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 | 
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
      at run (/Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/hook-engine.js:96:13)
      at workLoop (/Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/create-prompt.js:114:24)

      at /Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/create-prompt.js:123:20
      at processTicksAndRejections (:55:76)

```

### What is the expected behavior?

Open a cli prompt and enable input

### What do you see instead?

```
❯ bun run index.ts 
? Enter your name
120 | 
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 | 
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
      at run (/Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/hook-engine.js:96:13)
      at workLoop (/Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/create-prompt.js:114:24)

      at /Users/christoph/Code/testing/inquirer/node_modules/@inquirer/core/dist/cjs/lib/create-prompt.js:123:20
      at processTicksAndRejections (:55:76)

```

**Comment by jimmywarting** [comment]
eh... had a look at what `@inquirer/core` is doing with `withUpdates`
what they are doing looks wrong...?

`AsyncResource` is a class and they should treat it as such...? not by binding it to a new function. 
i think they should actually do something like:

```js
class Wrapped extends AsyncResource {
  constructor(...args) { ... }
}

// and then call it as such:
new Wrapped(...)
```

Feels like a `@inquirer/core` bug to me...

**EDIT:** i saw that AsyncResource.bind was a [thing](https://nodejs.org/api/async_context.html#static-method-asyncresourcebindfn-type-thisarg) apparently... however it's [deprecated](https://github.com/nodejs/node/pull/46432) and should not be used anymore.

**Comment by christoph88** [comment]
@jimmywarting  thanks I'll pass it on

**Comment by bompi88** [comment]
Any workaround for this atm?

**Comment by Jarred-Sumner** [comment]
Fixed by @paperdave in https://github.com/oven-sh/bun/pull/6095

**Comment by iway1** [comment]
still having this issue

EDIT: nvm hadn't upgraded bun since before #6095

**Comment by dante4rt** [comment]
Still having this issue too..

```
120 | 
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 | 
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
```
