### ISSUE TITLE
Support npm lifecycle hook scripts

### ISSUE THREAD

**Issue by sno2** [oven-sh/bun#606]
### What is the problem this feature will solve?

Many libraries currently depend on life cycle hooks for automated actions such as downloading a binary for a specific platform.

### What is the feature you are proposing to solve the problem?

Implement NPM's life-cycle hook scripts https://docs.npmjs.com/cli/v6/using-npm/scripts

### What alternatives have you considered?

n/a

**Comment by birkskyum** [comment]
@Jarred-Sumner you asked for blockers for bun adoption - any progress on this issue?

It's a show-stopper for me (macos arm64) that this popular (10M+ downloads / month) node image manipulation library [sharp](https://www.npmjs.com/package/sharp) doesn't install the platform specific binaries, because these npm install flags appear to be ignored, such as `npm install --platform=linux --arch=x64 sharp`

**Comment by denizguzel** [comment]
> @Jarred-Sumner you asked for blockers for bun adoption - any progress on this issue?
> 
> It's a show-stopper for me (macos arm64) that this popular node image manipulation library [sharp](https://www.npmjs.com/package/sharp) doesn't install the platform specific binaries, because these npm install flags appear to be ignored, such as `npm install --platform=linux --arch=x64 sharp`

Yeah same issue here as well with the following output.

```
 bun install
bun install v0.6.13 (3a93ddfa)
 + @babel/core@7.22.8
 + @babel/plugin-transform-runtime@7.22.7
 + @babel/preset-env@7.22.7
 + @babel/preset-react@7.22.5
 + @babel/preset-typescript@7.22.5
 + @storybook/addon-actions@7.0.26
 + @storybook/addon-docs@7.0.26
 + @storybook/addon-essentials@7.0.26
 + @storybook/addon-interactions@7.0.26
 + @storybook/addon-links@7.0.26
 + @storybook/react@7.0.26
 + @storybook/react-vite@7.0.26
 + @testing-library/dom@9.3.1
 + @testing-library/jest-dom@5.16.5
 + @testing-library/react@14.0.0
 + @types/dedent@0.7.0
 + @types/fs-extra@11.0.1
 + @types/html-minifier-terser@7.0.0
 + @types/jest@29.5.2
 + @types/loadable__component@5.13.4
 + @types/node@20.4.0
 + @types/papaparse@5.3.7
 + @types/react@18.2.14
 + @types/react-dom@18.2.6
 + @types/sort-json@2.0.1
 + @types/uuid@9.0.2
 + @typescript-eslint/eslint-plugin@5.61.0
 + @typescript-eslint/parser@5.61.0
 + @vitejs/plugin-react@4.0.2
 + babel-jest@29.6.1
 + babel-loader@9.1.2
 + babel-plugin-transform-import-meta@2.2.0
 + babel-plugin-transform-vite-meta-env@1.0.3
 + browserslist@4.21.9
 + cheerio@1.0.0-rc.12
 + cross-env@7.0.3
 + eslint@8.44.0
 + eslint-config-prettier@8.8.0
 + eslint-plugin-prettier@4.2.1
 + eslint-plugin-react@7.32.2
 + eslint-plugin-react-hooks@4.6.0
 + eslint-plugin-storybook@0.6.12
 + eslint-plugin-unused-imports@2.0.0
 + favicons@7.1.3
 + html-minifier-terser@7.2.0
 + husky@8.0.3
 + jest@29.6.1
 + jest-environment-jsdom@29.6.1
 + jsdom@22.1.0
 + lint-staged@13.2.3
 + picocolors@1.0.0
 + prettier@3.0.0
 + rollup-plugin-visualizer@5.9.2
 + sass@1.63.6
 + sharp@0.32.1
 + sort-json@2.0.1
 + storybook@7.0.26
 + storybook-dark-mode@3.0.0
 + ts-jest@29.1.1
 + ts-node@10.9.1
 + typescript@5.1.6
 + vite@4.4.1
 + vite-plugin-checker@0.6.1
 + vite-plugin-compression@0.5.1
 + vite-tsconfig-paths@4.2.0
 + yargs@17.7.2
 + @dnd-kit/core@6.0.8
 + @dnd-kit/modifiers@6.0.1
 + @dnd-kit/sortable@7.0.2
 + @emoji-mart/data@1.1.2
 + @emoji-mart/react@1.1.1
 + @emotion/react@11.11.1
 + @fontsource/poppins@5.0.4
 + @fortawesome/fontawesome-svg-core@6.4.0
 + @fortawesome/pro-duotone-svg-icons@6.4.0
 + @fortawesome/pro-light-svg-icons@6.4.0
 + @fortawesome/pro-regular-svg-icons@6.4.0
 + @fortawesome/pro-solid-svg-icons@6.4.0
 + @fortawesome/pro-thin-svg-icons@6.4.0
 + @fortawesome/react-fontawesome@0.2.0
 + @fortawesome/sharp-solid-svg-icons@6.4.0
 + @loadable/component@5.15.3
 + @mantine/carousel@6.0.16
 + @mantine/core@6.0.16
 + @mantine/dates@6.0.16
 + @mantine/dropzone@6.0.16
 + @mantine/hooks@6.0.16
 + @mantine/modals@6.0.16
 + @mantine/notifications@6.0.16
 + @mantine/prism@6.0.16
 + @mantine/spotlight@6.0.16
 + @mantine/tiptap@6.0.16
 + @reduxjs/toolkit@1.9.5
 + @sentry/react@7.57.0
 + @sentry/tracing@7.57.0
 + @tabler/icons-react@2.24.0
 + @tanstack/react-table@8.9.3
 + @tiptap/extension-character-count@2.0.3
 + @tiptap/extension-color@2.0.3
 + @tiptap/extension-highlight@2.0.3
 + @tiptap/extension-link@2.0.3
 + @tiptap/extension-placeholder@2.0.3
 + @tiptap/extension-subscript@2.0.3
 + @tiptap/extension-superscript@2.0.3
 + @tiptap/extension-text-align@2.0.3
 + @tiptap/extension-text-style@2.0.3
 + @tiptap/extension-underline@2.0.3
 + @tiptap/pm@2.0.3
 + @tiptap/react@2.0.3
 + @tiptap/starter-kit@2.0.3
 + axios@1.4.0
 + clsx@1.2.1
 + dayjs@1.11.9
 + dedent@0.7.0
 + dequal@2.0.3
 + embla-carousel-autoplay@7.1.0
 + embla-carousel-react@7.1.0
 + emoji-mart@5.5.2
 + formik@2.4.2
 + fuse.js@6.6.2
 + i18next@23.2.8
 + i18next-browser-languagedetector@7.1.0
 + i18next-http-backend@2.2.1
 + jsencrypt@3.3.2
 + papaparse@5.4.1
 + qs@6.11.2
 + react@18.2.0
 + react-cropper@2.3.3
 + react-dom@18.2.0
 + react-i18next@13.0.1
 + react-intl@6.4.4
 + react-redux@8.1.1
 + react-router-dom@6.14.1
 + react-use@17.4.0
 + redux-persist@6.0.0
 + redux-persist-transform-filter@0.0.22
 + socket.io-client@4.7.1
 + uuid@9.0.0
 + vite-plugin-svgr@3.2.0
 + yup@1.2.0
husky - Git hooks installed

 1499 packages installed [8.38s]


 bun run dev
$ vite
failed to load config from /vite.config.ts
error when starting dev server:
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /node_modules/sharp/lib/sharp.js
- /node_modules/sharp/lib/constructor.js
- /node_modules/sharp/lib/index.js
- /node_modules/favicons/dist/index.cjs
- /vite.config.ts
- /node_modules/vite/dist/node/chunks/dep-439026c8.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at _require.extensions.<computed> [as .js] (file:///node_modules/vite/dist/node/chunks/dep-439026c8.js:66104:17)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
error: script "dev" exited with code 1 (SIGHUP)
```

**Comment by Mouvedia** [comment]
[https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts](life cycle scripts)

depends on #1976:

- `prepare` AKA `prepublish`
- `prepublishOnly`

depends on #487:

- `prepack`
- `postpack`

**Comment by KjshServer** [comment]
Fix npm canvas: 

`bun add canvas && cd /node_modules/canvas && bun i && cd ../../ && bun dev`

**Comment by xinha-sh** [comment]
> Fix npm canvas:
> 
> `bun add canvas && cd /node_modules/canvas && bun i && cd ../../ && bun dev`

I'm getting error
```dyld[27269]: missing symbol called```

**Comment by KjshServer** [comment]
> > Fix npm canvas:
> > `bun add canvas && cd /node_modules/canvas && bun i && cd ../../ && bun dev`
> 
> I'm getting error `dyld[27269]: missing symbol called`

`bun add canvas`
`cd node_modules/canvas`
`bun i`

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.

**Comment by coolcorexix** [comment]
this problem still persist for me when I have to cd to node module canvas and run install command manually


Profile:
bun 1.1.38
macos 14.4.1
running installing canvas package from a monorepo

my .npmrc
```
unsafe-perm = true
auto-install-peers = true
```
