### ISSUE TITLE
zeromq module does not work

### ISSUE THREAD

**Issue by anttikissa** [oven-sh/bun#6313]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Even requiring the zeromq module doesn't work.

To reproduce, run in an empty directory:
```
bun init
bun add zeromq@6.0.0-beta.17
echo "require('zeromq')" > index.ts
bun index.ts
```

### What is the expected behavior?

That the require would work

### What do you see instead?

```
% bun index.ts
1 | (function (id) {"use strict";
                        ^
TypeError: dlopen(/Users/antti/sync/zeromq-test/node_modules/zeromq/prebuilds/darwin-arm64/node.napi.glibc.node, 0x0001): Library not loaded: /Users/runner/arm-target/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: <1DC056E1-92FA-379B-8526-E6E3738194E7> /Users/antti/sync/zeromq-test/node_modules/zeromq/prebuilds/darwin-arm64/node.napi.glibc.node
  Reason: tried: '/Users/runner/arm-target/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/arm-target/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/Users/runner/arm-target/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file, not in dyld cache)
      at internalRequire (:1:20)
      at load (/Users/antti/sync/zeromq-test/node_modules/@aminya/node-gyp-build/index.js:22:9)
      at /Users/antti/sync/zeromq-test/node_modules/zeromq/lib/native.js:6:7
      at globalThis (/Users/antti/sync/zeromq-test/node_modules/zeromq/lib/native.js:6:77)
      at overridableRequire (:1:20)
      at /Users/antti/sync/zeromq-test/node_modules/zeromq/lib/index.js:5:4
      at globalThis (/Users/antti/sync/zeromq-test/node_modules/zeromq/lib/index.js:595:75)
```

### Additional information

First I noticed that Bun tries to load libsodium from non-existing path `/Users/runner/arm-target/opt/libsodium/lib`.

I can get a step further by creating that and linking a homebrew-installed libsodium.23.dylib there:

```
sudo mkdir -p /Users/runner/arm-target/opt/libsodium/lib/
sudo ln -sf /opt/homebrew/lib/libsodium.23.dylib /Users/runner/arm-target/opt/libsodium/lib/
```

However, now I get this:

```
atk:~/sync/zeromq-test% bun index.ts
dyld[28103]: missing symbol called
zsh: killed     bun index.ts
```

and macOS problem report with the following contents:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               bun [28103]
Path:                  /Users/USER/*/bun
Identifier:            bun
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [27434]
Responsible:           iTerm2 [1421]
User ID:               501

Date/Time:             2023-10-05 10:18:57.2883 +0300
OS Version:            macOS 13.5.1 (22G90)
Report Version:        12
Anonymous UUID:        12E34994-328C-3E24-C543-F47D1568993A

Sleep/Wake UUID:       5D0646C5-F9BA-41EC-846D-DBBCD2F8A52C

Time Awake Since Boot: 6200 seconds
Time Since Wake:       2399 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
missing symbol called
(terminated at launch; ignore backtrace)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   dyld                          	       0x18d07d93c __terminate_with_payload + 8
1   dyld                          	       0x18d088d9c abort_with_payload_wrapper_internal + 136
2   dyld                          	       0x18d088db0 abort_with_payload + 16
3   dyld                          	       0x18d0148a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x18d04a770 dyld4::APIs::_dyld_missing_symbol_abort() + 44
5   node.napi.glibc.node          	       0x136a716dc 0x136a64000 + 55004
6   node.napi.glibc.node          	       0x136a6f0c4 0x136a64000 + 45252
7   node.napi.glibc.node          	       0x136a70608 napi_register_module_v1 + 48
8   bun                           	       0x102f09598 napi_module_register + 276
9   dyld                          	       0x18d02c1d8 invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
10  dyld                          	       0x18d06dc60 invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 172
11  dyld                          	       0x18d0611a4 invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 528
12  dyld                          	       0x18d00c2d8 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 296
13  dyld                          	       0x18d0601cc dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
14  dyld                          	       0x18d062cfc dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const + 160
15  dyld                          	       0x18d06d904 dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 432
16  dyld                          	       0x18d02885c dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 448
17  dyld                          	       0x18d028c10 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 220
18  dyld                          	       0x18d02c264 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 112
19  dyld                          	       0x18d028d90 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 304
20  dyld                          	       0x18d046d58 dyld4::APIs::dlopen_from(char const*, int, void*) + 1440
21  bun                           	       0x102e3e7a0 Bun::Process_functionDlopen(JSC::JSGlobalObject*, JSC::CallFrame*) + 356
22  ???                           	       0x10e9901fc ???
23  bun                           	       0x101a9bc64 llint_entry + 150952
24  ???                           	       0x10e98c164 ???
25  bun                           	       0x101a9bc64 llint_entry + 150952
26  bun                           	       0x101a9bc64 llint_entry + 150952
27  bun                           	       0x101a9bc64 llint_entry + 150952
28  bun                           	       0x101a76c08 vmEntryToJavaScript + 260
29  bun                           	       0x10240f50c JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*) + 13896
30  bun                           	       0x1026d16b8 JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 304
31  bun                           	       0x102ddba44 Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 716
32  bun                           	       0x102ddd86c Bun::jsFunctionRequireCommonJS(JSC::JSGlobalObject*, JSC::CallFrame*) + 2652
33  ???                           	       0x10e9901fc ???
34  bun                           	       0x101a9bbf0 llint_entry + 150836
35  ???                           	       0x10e98c164 ???
36  bun                           	       0x101a9bc64 llint_entry + 150952
37  bun                           	       0x101a9bc64 llint_entry + 150952
38  bun                           	       0x101a76c08 vmEntryToJavaScript + 260
39  bun                           	       0x10240f50c JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*) + 13896
40  bun                           	       0x1026d16b8 JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 304
41  bun                           	       0x102ddba44 Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 716
42  bun                           	       0x102ddd86c Bun::jsFunctionRequireCommonJS(JSC::JSGlobalObject*, JSC::CallFrame*) + 2652
43  ???                           	       0x10e9901fc ???
44  bun                           	       0x101a9bc64 llint_entry + 150952
45  bun                           	       0x101a76c08 vmEntryToJavaScript + 260
46  bun                           	       0x102410b30 JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 856
47  bun                           	       0x10276ddf4 JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*) + 1632
48  ???                           	       0x10e990038 ???
49  bun                           	       0x101a9cd34 llint_entry + 155256
50  bun                           	       0x101a9bc64 llint_entry + 150952
51  bun                           	       0x101a76c08 vmEntryToJavaScript + 260
52  bun                           	       0x10240f50c JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*) + 13896
53  bun                           	       0x1026d16b8 JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 304
54  bun                           	       0x102ddba44 Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 716
55  bun                           	       0x102de361c WTF::Detail::CallableWrapper<Bun::createCommonJSModule(Zig::GlobalObject*, ResolvedSource, bool)::$_0, void, JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&>::call(JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&) + 932
56  bun                           	       0x10280c554 JSC::moduleLoaderParseModule(JSC::JSGlobalObject*, JSC::CallFrame*) + 1600
57  ???                           	       0x10e9901fc ???
58  bun                           	       0x101a9bc64 llint_entry + 150952
59  bun                           	       0x101a9bbf0 llint_entry + 150836
60  bun                           	       0x101a9bc64 llint_entry + 150952
61  bun                           	       0x101a9cd34 llint_entry + 155256
62  bun                           	       0x101a76c08 vmEntryToJavaScript + 260
63  bun                           	       0x102410b30 JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 856
64  bun                           	       0x10280ace8 JSC::runJSMicrotask(JSC::JSGlobalObject*, WTF::ObjectIdentifierGeneric<JSC::MicrotaskIdentifierType, WTF::ObjectIdentifierThreadSafeAccessTraits>, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue) + 396
65  bun                           	       0x1029bb720 JSC::VM::drainMicrotasks() + 308
66  bun                           	       0x10141e470 src.bun.js.event_loop.EventLoop.tick + 604
67  bun                           	       0x101377c88 src.bun_js.Run.boot + 1172

Thread 1:: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102d60b7c scavenger_thread_main + 1008
3   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
4   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 2:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 3:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 4:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 5:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 6:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 7:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 8:: Heap Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8

Thread 9:: JIT Worklist Helper Thread
0   libsystem_kernel.dylib        	       0x18d32b750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x18d368574 _pthread_cond_wait + 1232
2   bun                           	       0x102cedf88 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2620
3   bun                           	       0x102cddb14 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 448
4   bun                           	       0x102d29c64 WTF::wtfThreadEntryPoint(void*) + 220
5   libsystem_pthread.dylib       	       0x18d367fa8 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x18d362da0 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000004   x3: 0x000000016ee3a960
    x4: 0x0000000000000014   x5: 0x000000016ee3a560   x6: 0x0000000000000200   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x00000001e83ea000  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x00000000000007fb  x15: 0x000000008023f7fb
   x16: 0x0000000000000208  x17: 0x000000018d00d35c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016ee3a560  x21: 0x0000000000000014  x22: 0x000000016ee3a960  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0xfffe000000000002  x26: 0x000000016ee3b6e0  x27: 0x0000000136a64420
   x28: 0xfffe000000000002   fp: 0x000000016ee3a530   lr: 0x000000018d088d9c
    sp: 0x000000016ee3a4f0   pc: 0x000000018d07d93c cpsr: 0x00001000
   far: 0x00000001014dc37c  esr: 0x56000080  Address size fault

Binary Images:
       0x100fa0000 -        0x103843fff bun (*) <f2a4ffb9-7fcd-339a-9b54-f704fc686f14> /Users/USER/*/bun
       0x136a64000 -        0x136af3fff node.napi.glibc.node (*) <1dc056e1-92fa-379b-8526-e6e3738194e7> /Users/USER/*/node.napi.glibc.node
       0x1369d4000 -        0x1369f7fff libsodium.23.dylib (*) <35811528-f5e0-3262-9418-27f089c03b04> /opt/homebrew/*/libsodium.23.dylib
       0x18d00a000 -        0x18d098587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18d327000 -        0x18d360ff7 libsystem_kernel.dylib (*) <08c5fe2a-b0bf-3ab6-bb42-460c18917d33> /usr/lib/system/libsystem_kernel.dylib
       0x18d361000 -        0x18d36dfff libsystem_pthread.dylib (*) <1f30fb9a-bdf9-32db-a709-8417666a7e45> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=858.6M resident=0K(0%) swapped_out_or_unallocated=858.6M(100%)
Writable regions: Total=69.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=69.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
IOAccelerator                     32.0M        1 
JS JIT generated code            512.0M        3 
JS VM Gigacage                    32.2G        3 
JS VM Gigacage (reserved)         63.8G        2         reserved VM address space (unallocated)
Kernel Alloc Once                   32K        1 
MALLOC                           146.2M       13 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                        160K       10 
Stack                             68.8M       11 
VM_ALLOCATE                      128.0M        1 
VM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)
WebKit Malloc                    288.1M        7 
__AUTH                              46K       11 
__AUTH_CONST                       144K       40 
__DATA                            9323K       42 
__DATA_CONST                      1189K       44 
__DATA_DIRTY                        84K       23 
__LINKEDIT                       809.3M        4 
__OBJC_RO                         66.4M        1 
__OBJC_RW                         2012K        1 
__TEXT                            49.3M       46 
dyld private memory                272K        2 
shared memory                       32K        2 
===========                     =======  ======= 
TOTAL                            102.4G      276 
TOTAL, minus reserved VM space    34.3G      276 



-----------
Full Report
-----------

{"app_name":"bun","timestamp":"2023-10-05 10:18:57.00 +0300","app_version":"","slice_uuid":"f2a4ffb9-7fcd-339a-9b54-f704fc686f14","build_version":"","platform":1,"share_with_app_devs":1,"is_first_party":1,"bug_type":"309","os_version":"macOS 13.5.1 (22G90)","roots_installed":0,"incident_id":"27D69580-54BB-46E6-8591-E1AE03B5B380","name":"bun"}
{
  "uptime" : 6200,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,4",
  "coalitionID" : 1017,
  "osVersion" : {
    "train" : "macOS 13.5.1",
    "build" : "22G90",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-05 10:18:57.2883 +0300",
  "incident" : "27D69580-54BB-46E6-8591-E1AE03B5B380",
  "pid" : 28103,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-05 10:18:57.2461 +0300",
  "procStartAbsTime" : 150384335156,
  "procExitAbsTime" : 150385309929,
  "procName" : "bun",
  "procPath" : "\/Users\/USER\/*\/bun",
  "parentProc" : "zsh",
  "parentPid" : 27434,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "12E34994-328C-3E24-C543-F47D1568993A",
  "responsiblePid" : 1421,
  "responsibleProc" : "iTerm2",
  "codeSigningID" : "bun",
  "codeSigningTeamID" : "7FRXF46ZSN",
  "codeSigningFlags" : 1644233217,
  "codeSigningValidationCategory" : 5,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 2399,
  "sleepWakeUUID" : "5D0646C5-F9BA-41EC-846D-DBBCD2F8A52C",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["missing symbol called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":138011,"threadState":{"x":[{"value":0},{"value":0},{"value":4},{"value":6155381088},{"value":20},{"value":6155380064},{"value":512},{"value":0},{"value":32},{"value":8191385600,"symbolLocation":0,"symbol":"_current_pid"},{"value":1},{"value":10},{"value":0},{"value":50},{"value":2043},{"value":2149840891},{"value":520},{"value":6660608860,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6155380064},{"value":20},{"value":6155381088},{"value":4},{"value":6},{"value":18446181123756130306},{"value":6155384544},{"value":5211833376},{"value":18446181123756130306}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6661115292},"cpsr":{"value":4096},"fp":{"value":6155380016},"sp":{"value":6155379952},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6661069116,"matchesCrashFrame":1},"far":{"value":4316840828}},"queue":"com.apple.main-thread","frames":[{"imageOffset":473404,"symbol":"__terminate_with_payload","symbolLocation":8,"imageIndex":3},{"imageOffset":519580,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":136,"imageIndex":3},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":3},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":3},{"imageOffset":264048,"symbol":"dyld4::APIs::_dyld_missing_symbol_abort()","symbolLocation":44,"imageIndex":3},{"imageOffset":55004,"imageIndex":1},{"imageOffset":45252,"imageIndex":1},{"imageOffset":50696,"symbol":"napi_register_module_v1","symbolLocation":48,"imageIndex":1},{"imageOffset":32937368,"symbol":"napi_module_register","symbolLocation":276,"imageIndex":0},{"imageOffset":139736,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":3},{"imageOffset":408672,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":172,"imageIndex":3},{"imageOffset":356772,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":528,"imageIndex":3},{"imageOffset":8920,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":296,"imageIndex":3},{"imageOffset":352716,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":3},{"imageOffset":363772,"symbol":"dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":160,"imageIndex":3},{"imageOffset":407812,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":432,"imageIndex":3},{"imageOffset":125020,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":448,"imageIndex":3},{"imageOffset":125968,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":220,"imageIndex":3},{"imageOffset":139876,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":112,"imageIndex":3},{"imageOffset":126352,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":304,"imageIndex":3},{"imageOffset":249176,"symbol":"dyld4::APIs::dlopen_from(char const*, int, void*)","symbolLocation":1440,"imageIndex":3},{"imageOffset":32106400,"symbol":"Bun::Process_functionDlopen(JSC::JSGlobalObject*, JSC::CallFrame*)","symbolLocation":356,"imageIndex":0},{"imageOffset":4539875836,"imageIndex":4},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":4539859300,"imageIndex":4},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11365384,"symbol":"vmEntryToJavaScript","symbolLocation":260,"imageIndex":0},{"imageOffset":21427468,"symbol":"JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*)","symbolLocation":13896,"imageIndex":0},{"imageOffset":24319672,"symbol":"JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":304,"imageIndex":0},{"imageOffset":31701572,"symbol":"Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":716,"imageIndex":0},{"imageOffset":31709292,"symbol":"Bun::jsFunctionRequireCommonJS(JSC::JSGlobalObject*, JSC::CallFrame*)","symbolLocation":2652,"imageIndex":0},{"imageOffset":4539875836,"imageIndex":4},{"imageOffset":11516912,"symbol":"llint_entry","symbolLocation":150836,"imageIndex":0},{"imageOffset":4539859300,"imageIndex":4},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11365384,"symbol":"vmEntryToJavaScript","symbolLocation":260,"imageIndex":0},{"imageOffset":21427468,"symbol":"JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*)","symbolLocation":13896,"imageIndex":0},{"imageOffset":24319672,"symbol":"JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":304,"imageIndex":0},{"imageOffset":31701572,"symbol":"Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":716,"imageIndex":0},{"imageOffset":31709292,"symbol":"Bun::jsFunctionRequireCommonJS(JSC::JSGlobalObject*, JSC::CallFrame*)","symbolLocation":2652,"imageIndex":0},{"imageOffset":4539875836,"imageIndex":4},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11365384,"symbol":"vmEntryToJavaScript","symbolLocation":260,"imageIndex":0},{"imageOffset":21433136,"symbol":"JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)","symbolLocation":856,"imageIndex":0},{"imageOffset":24960500,"symbol":"JSC::boundThisNoArgsFunctionCall(JSC::JSGlobalObject*, JSC::CallFrame*)","symbolLocation":1632,"imageIndex":0},{"imageOffset":4539875384,"imageIndex":4},{"imageOffset":11521332,"symbol":"llint_entry","symbolLocation":155256,"imageIndex":0},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11365384,"symbol":"vmEntryToJavaScript","symbolLocation":260,"imageIndex":0},{"imageOffset":21427468,"symbol":"JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*)","symbolLocation":13896,"imageIndex":0},{"imageOffset":24319672,"symbol":"JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":304,"imageIndex":0},{"imageOffset":31701572,"symbol":"Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&)","symbolLocation":716,"imageIndex":0},{"imageOffset":31733276,"symbol":"WTF::Detail::CallableWrapper<Bun::createCommonJSModule(Zig::GlobalObject*, ResolvedSource, bool)::$_0, void, JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&>::call(JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&)","symbolLocation":932,"imageIndex":0},{"imageOffset":25609556,"symbol":"JSC::moduleLoaderParseModule(JSC::JSGlobalObject*, JSC::CallFrame*)","symbolLocation":1600,"imageIndex":0},{"imageOffset":4539875836,"imageIndex":4},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11516912,"symbol":"llint_entry","symbolLocation":150836,"imageIndex":0},{"imageOffset":11517028,"symbol":"llint_entry","symbolLocation":150952,"imageIndex":0},{"imageOffset":11521332,"symbol":"llint_entry","symbolLocation":155256,"imageIndex":0},{"imageOffset":11365384,"symbol":"vmEntryToJavaScript","symbolLocation":260,"imageIndex":0},{"imageOffset":21433136,"symbol":"JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)","symbolLocation":856,"imageIndex":0},{"imageOffset":25603304,"symbol":"JSC::runJSMicrotask(JSC::JSGlobalObject*, WTF::ObjectIdentifierGeneric<JSC::MicrotaskIdentifierType, WTF::ObjectIdentifierThreadSafeAccessTraits>, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue)","symbolLocation":396,"imageIndex":0},{"imageOffset":27375392,"symbol":"JSC::VM::drainMicrotasks()","symbolLocation":308,"imageIndex":0},{"imageOffset":4711536,"symbol":"src.bun.js.event_loop.EventLoop.tick","symbolLocation":604,"imageIndex":0},{"imageOffset":4029576,"symbol":"src.bun_js.Run.boot","symbolLocation":1172,"imageIndex":0}]},{"id":138012,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":31198076,"symbol":"scavenger_thread_main","symbolLocation":1008,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138013,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138014,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138015,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138016,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138017,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138018,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138019,"name":"Heap Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":138020,"name":"JIT Worklist Helper Thread","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":6},{"imageOffset":30728072,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":2620,"imageIndex":0},{"imageOffset":30661396,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":448,"imageIndex":0},{"imageOffset":30973028,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":220,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4311351296,
    "size" : 42614784,
    "uuid" : "f2a4ffb9-7fcd-339a-9b54-f704fc686f14",
    "path" : "\/Users\/USER\/*\/bun",
    "name" : "bun"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 5211832320,
    "size" : 589824,
    "uuid" : "1dc056e1-92fa-379b-8526-e6e3738194e7",
    "path" : "\/Users\/USER\/*\/node.napi.glibc.node",
    "name" : "node.napi.glibc.node"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 5211242496,
    "size" : 147456,
    "uuid" : "35811528-f5e0-3262-9418-27f089c03b04",
    "path" : "\/opt\/homebrew\/*\/libsodium.23.dylib",
    "name" : "libsodium.23.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6660595712,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6663860224,
    "size" : 237560,
    "uuid" : "08c5fe2a-b0bf-3ab6-bb42-460c18917d33",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6664097792,
    "size" : 53248,
    "uuid" : "1f30fb9a-bdf9-32db-a709-8417666a7e45",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6659932160,
  "size" : 3553361920,
  "uuid" : "fef86b08-91da-3ab8-a9eb-8221d20f213c"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=858.6M resident=0K(0%) swapped_out_or_unallocated=858.6M(100%)\nWritable regions: Total=69.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=69.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nIOAccelerator                     32.0M        1 \nJS JIT generated code            512.0M        3 \nJS VM Gigacage                    32.2G        3 \nJS VM Gigacage (reserved)         63.8G        2         reserved VM address space (unallocated)\nKernel Alloc Once                   32K        1 \nMALLOC                           146.2M       13 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                        160K       10 \nStack                             68.8M       11 \nVM_ALLOCATE                      128.0M        1 \nVM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)\nWebKit Malloc                    288.1M        7 \n__AUTH                              46K       11 \n__AUTH_CONST                       144K       40 \n__DATA                            9323K       42 \n__DATA_CONST                      1189K       44 \n__DATA_DIRTY                        84K       23 \n__LINKEDIT                       809.3M        4 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                            49.3M       46 \ndyld private memory                272K        2 \nshared memory                       32K        2 \n===========                     =======  ======= \nTOTAL                            102.4G      276 \nTOTAL, minus reserved VM space    34.3G      276 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "472acc3847ad51220c22d980104c376494f29ea8",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "64d14f3e1008ca2fac17a163"
      },
      "deploymentId" : 240000064
    },
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

Model: MacBookPro18,4, BootROM 8422.141.2, proc 10:8:2 processors, 64 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: DELL U2720Q, 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: May 27 2023 01:34:59 version 20.96.31.0.8.7.148 FWID 01-126f2c4c
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: hub_device
USB Device: SteelSeries Rival 110 Gaming Mouse
USB Device: composite_device
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

```

**Comment by anttikissa** [comment]
The node equivalent works, though installation is much slower (is it compiling something that bun isn't?)
```
npm init
npm add zeromq@6.0.0-beta.17
node -e "require('zeromq')"
```

**Comment by Electroid** [comment]
Duplicate of #4959

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.

In the meantime, you can run `bun upgrade --canary`

**Comment by scottstanfield** [comment]
Appears this issue with `zeromq` is back (with 1.0.25 and 1.0.26 canary)
![image](https://github.com/oven-sh/bun/assets/280700/526430c4-6a18-441f-9090-48ef93c1e21f)

I opened a new issue #8498

**Comment by nk1tz** [comment]
I confirm this is **not resolved**. 
Here my comment in the new issue with a link to bug reproduction repo:
https://github.com/oven-sh/bun/issues/8498#issuecomment-1919151642
