### ISSUE TITLE
TypeError: performance.getEntriesByName

### ISSUE THREAD

**Issue by orpos** [oven-sh/bun#6537]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I just used the bun create next-app command and when i tried to use bun run dev it gave me that error

### What is the expected behavior?

to not throw an error

### What do you see instead?

$ next dev
78 |     if (cache) {
79 |         cache.set(obj, newObj);
80 |     }
81 |     return newObj;
82 | }
83 | if (performance.getEntriesByName("next-start").length === 0) {
       ^
TypeError: performance.getEntriesByName is not a function. (In 'performance.getEntriesByName("next-start")', 'performance.getEntriesByName' is undefined)
      at /home/dev1/projects/teste/node_modules/next/dist/server/lib/start-server.js:83:4
      at globalThis (/home/dev1/projects/teste/node_modules/next/dist/server/lib/start-server.js:285:5)

### Additional information
<=13.5.4 works correctly

**Comment by Electroid** [comment]
Next.js likely started calling this API in a recent update, and we'll need to implement it.

**Comment by HuakunShen** [comment]
Same issue

**Comment by Electroid** [comment]
Fixed by #6542, but will need a more permanent fix soon.

**Comment by sinawic** [comment]
I still get the same error using the `oven/bun` docker image
:(

**Comment by Electroid** [comment]
> I still get the same error using the `oven/bun` docker image :(

Try `oven/bun:canary`, or until our next release which will be soon.

**Comment by HuakunShen** [comment]
Error is gone, probably fixed in bun v1.0.7

**Comment by kothavade** [comment]
> Error is gone, probably fixed in bun v1.0.7

Still see it in `1.0.7`:
![Screenshot 2023-10-26 at 3 04 19 PM](https://github.com/oven-sh/bun/assets/60118973/8826c39d-faee-411c-a578-6397aed9e409)

**Comment by Electroid** [comment]
> > Error is gone, probably fixed in bun v1.0.7
> 
> Still see it in `1.0.7`: ![Screenshot 2023-10-26 at 3 04 19 PM](https://user-images.githubusercontent.com/60118973/278449359-8826c39d-faee-411c-a578-6397aed9e409.png)

@kothavade What does your `bun --revision` say?

**Comment by HuakunShen** [comment]
Mine: `1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157`
It works with next 13.5.5

Just upgrade both bun and next to latest, it should work.

**Comment by kothavade** [comment]
![Screenshot 2023-10-26 at 11 04 54 PM](https://github.com/oven-sh/bun/assets/60118973/fd01f01f-74a5-4442-8d41-a7558a9cdf09)

Both seem to be updated.

@Electroid @HuakunShen

**Comment by HuakunShen** [comment]
@kothavade I am using MacOS. Which OS are you using? 

I just tried Ubuntu 22, it also works. FYI: I created the template starter code with `bun create next-app`

<img width="547" alt="image" src="https://github.com/oven-sh/bun/assets/33727687/421535c1-2885-465e-afbd-a442f6f393c3">
<img width="343" alt="image" src="https://github.com/oven-sh/bun/assets/33727687/7a94e63f-3b2d-4c26-a437-82612ebda0cc">

The latest next is now 14.0.0, but 13.5.5 works for me too.

**Comment by kothavade** [comment]
On macOS as well. Will test again in a bit to check, maybe something might have changed.

FWIW, installed with nix, which just [downloads the 1.07 release from GitHub](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/web/bun/default.nix#L52-L54)

**Comment by kothavade** [comment]
Actually, for whatever reason, it works now. `bun --revision` hasn't changed though.

**Comment by JoltCode** [comment]
Still encountering this issue ^
<img width="718" alt="Screenshot 2024-01-29 at 10 34 28" src="https://github.com/oven-sh/bun/assets/46378904/3f62fc79-d90f-451a-8fde-617bd2917b7e">

**Comment by JoltCode** [comment]
Never mind - `bun upgrade --canary` fixed it! 😄

**Comment by anand4real** [comment]
works with oven/bun:1.0.7

**Comment by wj127** [comment]
`bun upgrade --canary` worked for me as well!
