### ISSUE TITLE
"Cannot find module" DuckDb

### ISSUE THREAD

**Issue by nshiab** [oven-sh/bun#6541]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

In a new repo, run `bun init` and then `bun add duckdb` (version 0.9.1 is the latest right now).

In `index.ts`, add this:
```ts
import { Database } from "duckdb";
const db = new Database(":memory:");
```

Run `bun index.ts`.

### What is the expected behavior?

When used with NodeJS, there is no error, and we can use DuckDB.

### What do you see instead?

 It will give you this error:
`Cannot find module "/node_modules/duckdb/lib/binding/duckdb.node" from "node_modules/duckdb/lib/duckdb-binding.js"`

### Additional information

Thank you for your amazing work! :)

**Comment by Electroid** [comment]
Duplicate of #4959

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.

In the meantime, you can run `bun upgrade --canary`

**Comment by pcc-huangm** [comment]
This is still an issue for me.

docker run -it oven/bun --entrypoint bash
root@68423ffc1cc0:/home/bun/app# bun -v
1.0.31

root@68423ffc1cc0:/home/bun/app# bun index.ts 
error: Cannot find module "/root/.bun/install/cache/duckdb@0.10.0/lib/binding/duckdb.node" from "/root/.bun/install/cache/duckdb@0.10.0/lib/duckdb-binding.js"

-- sample code index.ts


var duckdb = require('duckdb');
var db = new duckdb.Database(':memory:'); // or a file name for a persistent DB
db.all('SELECT 42 AS fortytwo', function(err, res) {
  if (err) {
    console.warn(err);
    return;
  }
  console.log(res[0].fortytwo)
});

**Comment by warrenbhw** [comment]
I'm hitting this issue again @dylan-conway @paperdave 

My bun version is 1.1.27

Unfortunately I have to switch off of bun (which I love in every other respect) because duckDB is a core part of what I'm building.

btw, I believe this issue is in bun's package manager, not in the bun runtime, because if I blow away my `node_modules` and reinstall then with `npm`, then run my program with bun, I do not hit this issue.

**Comment by warrenbhw** [comment]
cc @Jarred-Sumner in case you know what's going on :)

**Comment by Jarred-Sumner** [comment]
@warrenbhw this happens if the postinstall script for `duckdb` wasn't run

@pcc-huangm that happened because we don't currently support postinstall scripts when using automatic package installs. You'll have to run `bun install` manually in the folder and have a package.json in there.

**Comment by rvalek** [comment]
Hi! Any plans to support this?

**Comment by airtonix** [comment]
@Jarred-Sumner 

- ran `bun install`
- `bun build --compile` still gives error
