### ISSUE TITLE
`bun build` doesn't hoist `"use strict"`, `"use client"`, `"use server"`, etc. directives

### ISSUE THREAD

**Issue by ctjlewis** [oven-sh/bun#6854]
### What version of Bun is running?

`1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157`

### What platform is your computer?

`Darwin 23.1.0 arm64 arm`

### What steps can reproduce the bug?

Another edge case: https://github.com/oven-sh/bun/issues/6854#issuecomment-1824461079

---

![Screenshot 2023-11-02 at 4 16 20 AM](https://github.com/oven-sh/bun/assets/1657236/cca8dc91-dded-410c-bd5d-f8f498a430f9)

Leading string removed by `bun build` and `Bun.build(...)`:

```shell
$ bun build test.ts
  // test.ts
  console.log(123);
```

### What is the expected behavior?

Without `--minify`, this string shouldn't be removed.

### What do you see instead?

The string is removed.

**Comment by ctjlewis** [comment]
Manually forcing `"use client"` directives in build output:

```ts
/// <reference types="bun-types" />
import { glob } from "glob"

const entrypoints = await glob("lib/**/*.{js,jsx,ts,tsx}")
const { outputs } = await Bun.build({
  entrypoints,
  format: 'esm',
  outdir: './dist',
  external: ['react', 'react-dom'],
  minify: false,
})

for (const output of outputs) {
  const bytes = await output.arrayBuffer()
  const prefix = '"use client"\n\n'
  await Bun.write(output.path, [prefix, bytes])
}
```

**Comment by Bessonov** [comment]
Please check the latest bun release: https://bun.sh/blog/bun-v1.0.12#fixed-transpiler-preserves-custom-directives

**Comment by ctjlewis** [comment]
fixed by #7027

**Comment by ctjlewis** [comment]
Shit, there's an edge case we didn't think of, I closed without verifying.

It's not enough to just *not remove* these directives - we have to *hoist* them, and make sure they're the first expressions in the emitted AST.

For instance, we have to make sure JSX runtime imports and inlined dependencies are added *after* the directive. 

#### Repro (1.0.14): JSX runtime imports
```shell
$ bun build --no-bundle lib/components/form.tsx 
```
```js
import {
jsxDEV
} from "react/jsx-dev-runtime";
"use client"; // <---
// ...
```

#### Repro (1.0.14): Inlined imports
```shell
$ bun build lib/components/form.tsx
```
```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getProtoOf = Object.getPrototypeOf;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
// ...
"use client"; // <---
// ...
```

cc @Jarred-Sumner

**Comment by ctjlewis** [comment]
Lmfao, I tagged Jared instead of Jarred. My bad Palmer!

**Comment by Ant59** [comment]
Still an issue in 1.1.17. Bundling a directory of React components with `"use client";` directives results in an output file with many directives throughout instead of one hoisted to the top.

**Comment by Ant59** [comment]
Next.js outright refuses to load any component from the output due to the directive placement.

> × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.

**Comment by dgpt** [comment]
+1 I'm currently experiencing this issue with the `react-error-boundary` library. When I build with bun it sticks the `'use client'` in the middle of the code and I get ```Error:
  × The "use client" directive must be placed before other expressions. Move it to the top of the file to resolve this issue.```

**Comment by RiskyMH** [comment]
The original issue is fixed, but its still weird that the [edge case](https://github.com/oven-sh/bun/issues/6854#issuecomment-1824461079) with jsx puts react import above.

Also we have `--banner` now so you can manually force client too: https://bun.sh/blog/bun-v1.1.30#banner-and-footer-options-in-bun-build (I agree its not as good as fix but its there)

**Comment by XavierGeerinck** [comment]
Agreed, still an issue, needed the `--banner` option as well

**Comment by ctjlewis** [comment]
cc @Jarred-Sumner on an old one, good notes in here.

**Comment by nhuanhoangduc** [comment]
Thank your solution @XavierGeerinck . This way is how I fixed 'use client' issue:
```javascript
  // move "use client" to top of file
  for (const output of results.outputs) {
    // convert buffer to text string
    const buffer = await output.arrayBuffer();
    let text = new TextDecoder().decode(buffer);

    // check if file contains "use client", remove all and add 'use client' to start of file
    const hasUseClient = text.includes(`"use client";`);
    if (hasUseClient) {
      text = text.replaceAll(`"use client";`, "");
      text = `"use client";` + "\n" + text;
    }

    // Write the new file
    await Bun.write(
      (outdir ?? "./dist") + "/" + output.path,
      new TextEncoder().encode(text)
    );
  }
```

**Comment by arshad-yaseen** [comment]
@Jarred-Sumner Please 😭

**Comment by FlorianLebecque** [comment]
I confirm that I'am still having the issue


```
./ormi-core/dist/src/jsonforms.js:66827:1
Ecmascript file had an error
  66825 | var React224 = __toESM(require_react(), 1);
  66826 | var import_jsx_runtime131 = __toESM(require_jsx_runtime(), 1);
> 66827 | "use client";
        | ^^^^^^^^^^^^^
  66828 | var CHECKBOX_NAME = "Checkbox";
  66829 | var [createCheckboxContext, createCheckboxScope] = createContextScope(CHECKBOX_NAME);
  66830 | var [CheckboxProviderImpl, useCheckboxContext] = createCheckboxContext(CHECKBOX_NAME);
```

**Comment by ctjlewis** [comment]
> I'm having the same issue, and the --banner directive couldn't solve this poblem.

Can you manually bundle your client, server, or strict bundles and just add the banner manually? Or it will actually drag imports above the banner?
