### ISSUE TITLE
`stream` on sliced `Bunfile` doesn't work

### ISSUE THREAD

**Issue by bogeychan** [oven-sh/bun#7057]
### What version of Bun is running?

1.0.11

#### Create the following files

`./file.txt`

```txt
12345
```

`./index.ts`

```ts
const file = Bun.file('./file.txt').slice(0, 2);

const content = await(new Response(file.stream())).text();

console.log(content);
console.log(file.size);
```

#### Run

```bash
bun run index.ts
```

### What is the expected behavior?

Console output:

```bash
12
2
```

### What do you see instead?

Console output:

```bash
12345
2
```

**Comment by veera-sivarajan** [comment]
Hi, I'd like to work on this.

**Comment by botxboom** [comment]
Hi @bogeychan , I was going through the `read-file` docs(https://bun.sh/guides/read-file/string) and found `Bun.File()` returns a file instance as :
`FileRef ("./file.txt") {
  type: "text/plain;charset=utf-8"
}`

and you are performing `slice` on this `instance`. which won't slice the text inside the file.

To achieve that you can do:

`const content = await(new Response(file.stream())).text();`
`console.log(content.slice(0,2))`

You can also do:
`const file = Bun.file(path);`
`const content = await file.text();`

**Comment by veera-sivarajan** [comment]
From the docs (https://bun.sh/guides/read-file/string):
> The Bun.file() function accepts a path and returns a BunFile instance. The BunFile class extends Blob and allows you to lazily read the file in a variety of formats.

And `slice()` is a method on Blob (https://developer.mozilla.org/en-US/docs/Web/API/Blob). So I think `Bun.file('./file.txt').slice(0, 2);` should work as expected?

I'm not sure though.

**Comment by anderspitman** [comment]
Given this bug, and the lack of node `fs.createReadStream`, is there currently a way to seek and stream chunks from a large file in Bun? It's not time critical for me, but my code supports Node and Deno, and would like it to support Bun eventually.

**Comment by cirospaciari** [comment]
This was fixed in `v1.1.43`

**Comment by anderspitman** [comment]
Confirmed working for me, thank you!

**Comment by koakuma-chan** [comment]
Hi @cirospaciari,

It's still broken.

The stream hangs if the file is bigger than 640K.

Please re-open.

---

Works.
```
dd if=/dev/zero of=zeroes bs=512K count=1 \
  && bun -e 'await Bun.readableStreamToText(Bun.file("zeroes").slice(0, 1).stream())'
```

Works.
```
dd if=/dev/zero of=zeroes bs=768K count=1 \
  && bun -e 'await Bun.readableStreamToText(Bun.file("zeroes").stream())'
```

Does not work.
```
dd if=/dev/zero of=zeroes bs=768K count=1 \
  && bun -e 'await Bun.readableStreamToText(Bun.file("zeroes").slice(0, 1).stream())'
```

**Comment by koakuma-chan** [comment]
For anyone else running into this:

It seems `fs.createReadStream` is already implemented (a comment above says it isn't), so the workaround is to just use the Node API.

Here is a function to convert `ReadStream` to `ReadableStream`:

```typescript
// Helper function to convert Node.js ReadStream to Web ReadableStream
function nodeStreamToWebStream(nodeStream: ReadStream): ReadableStream {
  return new ReadableStream({
    start(controller) {
      nodeStream.on("data", (chunk) => {
        controller.enqueue(chunk);
      });
      nodeStream.on("end", () => {
        controller.close();
      });
      nodeStream.on("error", (err) => {
        controller.error(err);
      });
    },
    cancel() {
      nodeStream.destroy();
    },
  });
}
```
