### ISSUE TITLE
Bunx create-{react-app, vite, etc} freezes shell

### ISSUE THREAD

**Issue by squeaky-joe** [oven-sh/bun#7078]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Fedora 39 Linux 6.5.11-300 x86_64

### What steps can reproduce the bug?

Do `bunx --bun create-vite testing`, select a framework, and then shell will freeze

### What is the expected behavior?

Create an app using a framework script

### What do you see instead?

Entire shell freezes, have to kill it with alt+f4

### Additional information

This also happened with the docker image and the official Ubuntu image after I installed bun onto it. I did try both `bun x` and `bun create` and I ran into the same issue

**Comment by Hanaasagi** [comment]
maybe related to https://github.com/oven-sh/bun/issues/5040

**Comment by squeaky-joe** [comment]
Issue fixed with new Bun version 1.0.13 update

**Comment by squeaky-joe** [comment]
It fixed create-svelte, but create-vite still freezes the shell

**Comment by rempas** [comment]
> It fixed create-svelte, but create-vite still freezes the shell

Funny enough, `create-svelte` still freezes the shell for me in `1.0.14`

**Comment by KameiKojirou** [comment]
Same issue with ```bun create svelte@latest```

**Comment by squeaky-joe** [comment]
Started freezing for me once again...

**Comment by KameiKojirou** [comment]
So I forgot to mention I'm using Pop!_OS 22.04. In Bun 1.0.13 it used to take some time to freeze, in 1.0.14 it seems to happen almost immediately.

**Comment by rempas** [comment]
> So I forgot to mention I'm using Pop!_OS 22.04. In Bun 1.0.13 it used to take some time to freeze, in 1.0.14 it seems to happen almost immediately.

Yeah, mentioning our OS may be helpful! I use Arch (btw).

**Comment by Sur-en** [comment]
While it will be fixed, you can use just `bun`.
Here's an example:

```sh
bun create vite my-app
cd my-app
bun instal
bunx --bun vite
```
