### ISSUE TITLE
puppeteer pdf save bug

### ISSUE THREAD

**Issue by solenopsys** [oven-sh/bun#7728]
### What version of Bun is running?

1.0.18

### What platform is your computer?

wsl

### What steps can reproduce the bug?

Error  TypeError: fileHandle.close is not a function. (In 'fileHandle.close()', 'fileHandle.close' is undefined)

```
const puppeteer = require('puppeteer');

async function  gen(){
    const browser = await puppeteer.launch();

    const page = await browser.newPage();

    await page.setContent('<h1>Hello, Puppeteer!</h1>');

    await page.pdf({ path: 'example.pdf', format: 'A4' });

    await browser.close();

    console.log('Heres your PDF!.');
}

gen()
```

### What is the expected behavior?

no errors 

### What do you see instead?

```
  Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

389 |                 buffers.push(chunk);
390 |                 await fileHandle.writeFile(chunk);
391 |             }
392 |         }
393 |         finally {
394 |             await fileHandle.close();
                        ^
TypeError: fileHandle.close is not a function. (In 'fileHandle.close()', 'fileHandle.close' is undefined)
      at /mnt/c/dev/sources/MAIN/whiteparer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:394:19
      at processTicksAndRejections (:61:77)
```

**Comment by solenopsys** [comment]
Temporary solution to the problem.

```
import * as buffer from "buffer";

const puppeteer = require('puppeteer');

async function gen() {
    const browser = await puppeteer.launch();

    const page = await browser.newPage();

    await page.setContent('<h1>Hello, Puppeteer!</h1>');

    // Use pdf() instead of createPDFStream()
    const readableStream = await page.createPDFStream({format: 'A4'});

    const filePath = "test.pdf"

    readableStream.on('data', async (chunk: any) => {
        Bun.file(filePath, chunk)
        await Bun.write(filePath, chunk);
    });

    await browser.close();

    console.log('Here\'s your PDF!');
}

gen();
```

**Comment by Electroid** [comment]
We are likely missing the close method on file handle.

**Comment by kaioduarte** [comment]
Bun is returning the file descriptor (an integer) instead of a `FileHandle` as expected.

![image](https://github.com/oven-sh/bun/assets/11046907/ecddd203-e6c2-4526-bf49-e6591d5a984d)

I started looking into this but I hit the wall :)

**Comment by kaioduarte** [comment]
Maybe fixed by https://github.com/oven-sh/bun/pull/8141

**Comment by lacikawiz** [comment]
This issue is not fully fixed yet. The PDF creation does not crash with an error message but it creates a corrupt PDF file. See my bug report on this: #8482 (Which got closed as a duplicate of this, but it's not really the same as the manifestation is different). I just want to make sure that this doesn't get overlooked because others for sure will run into it and scratch their heads trying to figure out why they end up with corrupt PDF files.

**Comment by Xentox-Phil** [comment]
@lacikawiz 
a question are you running it inside a docker container?

I tried yesterday to generate pdf's and its giving me aswell a corrupted file. Did anybody look into this?

I use next.js for this project if you wonder

```typescript
    let browser: Browser | null = null;

    try {
        browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });
        const page: Page = await browser.newPage();
        await page.goto("http://localhost:3000/invoice/1", {
            waitUntil: ["networkidle0"],
            timeout: 30000,
        });
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
        });
     res.status(200).send(pdfBuffer);
```

**Comment by lacikawiz** [comment]
No. Not running it in a container.

**Comment by Xentox-Phil** [comment]
For Nextjs you need to convert the Uint8Array that the page.pdf method returns to a Buffer

```typescript 
res.status(200).send(Buffer.from(pdfBuffer));
```

**Comment by hayyangovinda** [comment]
> res.status(200).send(Buffer.from(pdfBuffer));

this worked for me

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v.1.2 by @paperclover

**Comment by Oladapodaniel** [comment]
> For Nextjs you need to convert the Uint8Array that the page.pdf method returns to a Buffer
> 
> res.status(200).send(Buffer.from(pdfBuffer));

I worked in a Node.js environment
This worked work for me,
 i battled with this for a while.
 Thanks for this.
