### ISSUE TITLE
`Error: request size did not match content length` when using `express.text()` middleware

### ISSUE THREAD

**Issue by noway** [oven-sh/bun#7939]
### What version of Bun is running?

1.0.20

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Minimal reproduction: https://github.com/noway/content-length-mismatch - follow Install & Run

### What is the expected behavior?

Expecting for Bun to output:
```
HTTP/1.1 404 Not Found
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /x</pre>
</body>
</html>
```

### What do you see instead?

Instead, Bun outputs:
```
HTTP/1.1 400 Bad Request
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: request size did not match content length<br> &nbsp; &nbsp;at createError (/Users/ilia/compiling/content-length-mismatch/node_modules/http-errors/index.js:94:34)<br> &nbsp; &nbsp;at onEnd (/Users/ilia/compiling/content-length-mismatch/node_modules/raw-body/index.js:271:8)<br> &nbsp; &nbsp;at endReadableNT (native)<br> &nbsp; &nbsp;at processTicksAndRejections (native)</pre>
</body>
</html>
```
```
Error: request size did not match content length
    at createError (/Users/ilia/compiling/content-length-mismatch/node_modules/http-errors/index.js:94:34)
    at onEnd (/Users/ilia/compiling/content-length-mismatch/node_modules/raw-body/index.js:271:8)
    at endReadableNT (native)
    at processTicksAndRejections (native)
```

### Additional information

- The bug was found via fuzzing by substituting `POST` with `GET`
- Seems to be happening when a `GET` request has a non-empty request body?

**Comment by Jarred-Sumner** [comment]
This may have been fixed but in canary by @cirospaciari 

can you run `bun upgrade --canary` and try again?

**Comment by noway** [comment]
@Jarred-Sumner Just tried canary, the bug is still happening unfortunately:

```
$ bun --version
1.0.21
```

```
$ ./repro.sh
...
Error: request size did not match content length
...
```

I've just searched GitHub issues and the stack trace is almost identical to #3842 . Looks like this is a duplicate issue, oops 😅

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/3842

**Comment by JulianMiguelAngle** [comment]
Guys it's 2025

**Comment by yesahem** [comment]
Guy's its official end of Q1 of 2025
