### ISSUE TITLE
Running `bun --bun vite build` inside Docker does not write files to system

### ISSUE THREAD

**Issue by JohannesKlauss** [oven-sh/bun#7967]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

oven/bun:1

### What steps can reproduce the bug?

Check out https://github.com/JohannesKlauss/bun-sveltekit-docker and run the dockerfile. It will throw an error:

```
 => ERROR [release 2/2] COPY --from=prerelease /usr/src/app/build .                                                                                                                                        0.0s
------
 > [release 2/2] COPY --from=prerelease /usr/src/app/build .:
------
Dockerfile:40
--------------------
  38 |     FROM base AS release
  39 |     COPY --from=install /temp/prod/node_modules node_modules
  40 | >>> COPY --from=prerelease /usr/src/app/build .
  41 |     
  42 |     ARG PUBLIC_SUPABASE_KEY
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 59ffe7c5-8f84-47e9-abfa-e874ebd11c23::bnbowl4qypjt62cc1vhx1fkkh: "/usr/src/app/build": not found
```

### What is the expected behavior?

The command should write the build output of vite to the docker file system

### What do you see instead?

The command runs successfully, but no files are present

### Additional information

Sadly, I don't know enough about the bun or docker internals to pinpoin the issue.

Running `bun --bun run vite build` locally works just fine and writes the build output to the file system, but inside the dockerfile, it does not work. Doesn't fail either.

**Comment by mikesprague** [comment]
This _might_ be related to this issue https://github.com/oven-sh/bun/issues/7676

**Comment by JohannesKlauss** [comment]
After digging around a bit you seem to be right. At least the behavior is the same.

Pinning bun to 1.0.16 in the Dockerfile works, the file runs without an issue.

Using 1.0.17 throws an weird error:

```
Step 6/34 : RUN cd /temp/dev && bun install --frozen-lockfile
 ---> Running in f87404aa0ba5
bun install v1.0.17 (5e60861c)
/bin/bash: line 1: node: command not found

error: postinstall script from "esbuild" exited with code 127
Error response from daemon: The command '/bin/sh -c cd /temp/dev && bun install --frozen-lockfile' returned a non-zero code: 127
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream
```

Using 1.0.18 throws an error that it can't find a python installation:

```
Step 6/34 : RUN cd /temp/dev && bun install --frozen-lockfile
 ---> Running in 726f3d1ab43c
bun install v1.0.18 (36c316a2)
 Resolving dependencies
 Resolved, downloaded and extracted [302]
 Saved lockfile
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.8.0 | linux | arm64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack at fail (/tmp/node-gyp@latest--bunx/node_modules/node-gyp/lib/find-python.js:305:67)
gyp ERR! stack at processTicksAndRejections (:61:39)
gyp ERR! System Linux 6.4.16-linuxkit
gyp ERR! command "/usr/local/bin/bun" "/tmp/node-gyp@latest--bunx/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /temp/dev/node_modules/utf-8-validate
gyp ERR! node -v v20.8.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 

error: install script from "utf-8-validate" exited with code 1 (SIGHUP)
Error response from daemon: The command '/bin/sh -c cd /temp/dev && bun install --frozen-lockfile' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream
```

And from 1.0.19 and onwards the original described error message appears.

So something broke between 1.0.16 and 1.0.19

**Comment by mikesprague** [comment]
YMMV but the seemingly related issue I was facing (https://github.com/oven-sh/bun/issues/7967#issuecomment-1875856263) appears to be resolved as of bun `v1.0.22`

**Comment by JohannesKlauss** [comment]
Yes, you are right, it has been fixed with 1.0.22

**Comment by JohannesKlauss** [comment]
This is still a problem with the new version 1.0.26 and it seems like 1.0.22 doesn't work anymore either. Docker fails with the mentioned error.

**Comment by beeequeue** [comment]
Can confirm this is still happening, doing pretty much the same thing with `1.0.35-alpine`.

Does not work with `--bun` or without it.

**Comment by tomholford** [comment]
> Using 1.0.18 throws an error that it can't find a python installation:

Seeing this now using oven/bun:1.1 container when trying to install deps for and build a `vite` project.

**Comment by DanielBaulig** [comment]
I think I've been running into the same or similar issue when trying to install a GitHub package dependency inside a Docker container. `bun install --verbose` seems to install the dependency, but it's simply not present in node_modules after the installation completes (there's no error, there's just no subdirectory for the dependency in node_modules). 

I've tried the same in `oven/bun:1.0.16` as this was mentioned as the last working version somewhere earlier in this issue and using that version the dependency installs correctly.

**Comment by DajosPatryk** [comment]
Have the same issue with bun v1.1.13 when building Nuxt3 app.

**Comment by azabroflovski** [comment]
same too
