### ISSUE TITLE
SegmentationFault at 26 when parsing json

### ISSUE THREAD

**Issue by romanetsdev** [oven-sh/bun#826]
### Version

0.1.4

### Platform

21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

super simple code to reproduce here:
https://github.com/romanetsdev/bun-json-bug

run with: `bun run index.js`

### How often does it reproduce? Is there a required condition?

reproduces with unexpected frequency

### What is the expected behavior?

log with parsed json object **on every run**

### What do you see instead?

SegmentationFault at 26

–––– bun meta ––––
Bun v0.1.4 macOS Silicon 21.5.0
RunCommand: 
Elapsed: 8ms | User: 9ms | Sys: 6ms
RSS: 19.15MB | Peak: 19.15MB | Commit: 69.22MB | Faults: 0
–––– bun meta ––––

### Additional information

https://user-images.githubusercontent.com/25416572/180428175-592ba21b-420e-4512-ac12-4c04f37f3cfc.mov

**Comment by Jarred-Sumner** [comment]
Most likely this is a bug in `.json()` memory management

**Comment by sewe75** [comment]
Works fine when `await`ing:
```javascript
const data = await Bun.file('data.json').json();
console.log(data);
```
Maybe when chaining it does not wait for the promise to be resolved?

**Comment by SelfMadeSystem** [comment]
~~I think it's fixed in the latest bun version.~~

~~I just tested it now with bun v0.1.11 and it didn't segfault.~~ I'm on `Arch Linux 5.19.7-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:33:28 +0000 x86_64 GNU/Linux`

Edit: Just tested it again. It segfaulted after 20 successful attempts and again after 45 successful attempts.

**Comment by kt3k** [comment]
I still see the segfault with `Bun.file("data.json").json().then(console.log);` in bun 0.1.11. The possibility is very small (like ~10%) though

(my env is `Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64`)

**Comment by Electroid** [comment]
This is still an issue as of `0.2.2`, we will get this fixed.

```json
{"data":1}
```

```js
Bun.file("data.json").json().then(console.log);
```

Then run `bun run` twice.

**Comment by Jarred-Sumner** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/709451/207997847-fbc5e3ad-5b1c-4d9a-b3ba-f33e7795eb45.png">
fixed as of bun v0.3.0
