### ISSUE TITLE
Error "SIGSEGV (Address boundary error)" in docker with prisma

### ISSUE THREAD

**Issue by Alexandrsv** [oven-sh/bun#8519]
### What version of Bun is running?

version 1.0.26+7492b3a20 and lower

### What platform is your computer?

Linux 6.7.0-0-MANJARO x86_64 unknown. alpine in docker

### What steps can reproduce the bug?

I tried to package hono and prisma in docker. 
Nothing succeeded

https://github.com/Alexandrsv/hono-vk-template/tree/brocken-bun

Without Docker on a local system, it works

### What is the expected behavior?

The application must run the hono server

### What do you see instead?

An error occurs when running docker-compose
SIGSEGV (Address boundary error)

### Additional information

![image](https://github.com/oven-sh/bun/assets/15097064/0c780458-810c-4116-8fea-71a468e89e4a)

**Comment by jontybrook** [comment]
Ditto seeing this issue; although i'm not running in docker.. i'm seeing it in dev on Ubuntu LTS. Are you sure this is related to Prisma?

**Comment by jontybrook** [comment]
This is likely related to this issue https://github.com/oven-sh/bun/issues/7864

Temporary solution for me is to use Bun v1.0.18

**Comment by camero2734** [comment]
I think this should have also been fixed by #8995

**Comment by muuvmuuv** [comment]
Also seeing this with `oven/bun:1.0` in GitLab CI with Cypress:

```
Using docker image sha256:a43cab60e1a2a13920cbf19cab25be76c4057288f1076b033f2d6383a123bb87 for oven/bun:1.0 with digest oven/bun@sha256:bdb96ef3fc072430bf06a2bfeb30314a1555adcfdc704c0cb8a22b6ced8945fc ...
$ bun install --frozen-lockfile
bun install v1.0.28 (70563847)
error: postinstall script from "nx" terminated by SIGSEGV (Address boundary error)
/bin/bash: line 135:    13 Segmentation fault      (core dumped) bun install --frozen-lockfile
```

There is no official documentation for Bun in GitLab; I use this `.gitlab-ci.yml`:

```yaml
modules:
  stage: .pre
  image: oven/bun:1.0
  script: bun install --frozen-lockfile
  cache:
    - key:
        files:
          - bun.lockb
      policy: pull-push
      paths:
        - node_modules/
```

**Comment by muuvmuuv** [comment]
> This is likely related to this issue #7864
> 
> Temporary solution for me is to use Bun v1.0.18

Tested this as well, but still the same, even if its now a different package (mayybe 'cause Bun does this in parallel):

```
Using docker image sha256:9dc0d8ab3409a166c2bd6bfb39102af3c2d07cf752b155a78698179f75da278c for oven/bun:1.0.18 with digest oven/bun@sha256:91a2f2d0f21bc1a4d44d42555698e58ffff33164f12b245d6e9dc5415a155dde ...
$ bun install --frozen-lockfile
bun install v1.0.18 (36c316a2)
error: postinstall script from "esbuild" exited with code 11 (SIGSEGV)
```

**Comment by muuvmuuv** [comment]
Tested with latest image again and concurrent=1 as well as with alpine... still shows SIGSEGV or SIGKILL.
