### ISSUE TITLE
Connection timeout when running pm2 + bun + TS + expressjs + postgres.js to connect to Postgresql database

### ISSUE THREAD

**Issue by minh5micron** [oven-sh/bun#8946]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Linux 5.15.0-67-generic x86_64 x86_64

### What steps can reproduce the bug?

We have Postgresql database size around 200Mb.
Our web server code is written in TS + Expressjs, Postgresjs to connect to the local database and the app is run by Bun.
We also use pm2 to start/restart and monitor the app itself.
However it's strange that after around somewhere from 10 to 20 hours there is connection time out issue with the database. 

```
2024-02-16T16:29:14: 22 |       errno: x,
2024-02-16T16:29:14: 23 |       address: options.path || host
2024-02-16T16:29:14: 24 |     }, options.path ? {} : { port: port }
2024-02-16T16:29:14: 25 |   )
2024-02-16T16:29:14: 26 |   Error.captureStackTrace(error, connection)
2024-02-16T16:29:14:              ^
2024-02-16T16:29:14: error: write CONNECT_TIMEOUT localhost:5432
2024-02-16T16:29:14:  code: "CONNECT_TIMEOUT"
2024-02-16T16:29:14: 
2024-02-16T16:29:14:       at connection (/home/****/node_modules/postgres/src/errors.js:26:9)
```

The database is still active without errors. We restart the app by "pm2 restart" and the connection timeout issue is disappeared.
Therefore we suspect that somehow Bun + Postgresjs is not stable enough though we have no ways to debug it. It would be nice if anyone can explain for us or show us some ways to debug :)

It is worth mentioning that we use the combo pm2 + Node + express + postgresjs before and never encountered into this issue before.
The reason why we are trying to switch to Bun is mostly because of its support of Typescript out-of-the-box.

**Comment by alhamda** [comment]
i experienced the same thing, did you fix it ?

**Comment by minh5micron** [comment]
Unfortunately, we had to switch back to Node + Typescript. We can only suspect that Postgresjs might be the main reason of this instability.

**Comment by bnussman** [comment]
I am unable to connect to my PostgreSQL database when using a `ca` cert

```typescript
import postgres from "postgres";
import { DB_CA, DB_URL } from "./constants";
import type { ConnectionOptions } from 'node:tls';

const options: ConnectionOptions = {
  ca: DB_CA,
};

const queryClient = postgres(DB_URL, options);
```

I think this is related

**Comment by Jarred-Sumner** [comment]
@bnussman are you getting a connection timeout? what's the error you're seeing? is there a chance you could let us know what type of certificate is in use? or if it's using a managed postgres instance, what provider? it would help us if you could provide some way for us to reproduce the authentication mechanism

**Comment by bnussman** [comment]
@Jarred-Sumner Yeah, a timeout using a managed Postgres (v13.2) database on Linode. 

```
Error: write CONNECT_TIMEOUT lin-1010-21-pgsql-primary.servers.linodedb.net:5432
    at connectTimedOut (/home/banks/Development/beep/apinext/node_modules/postgres/src/connection.js:257:20)
    at done (/home/banks/Development/beep/apinext/node_modules/postgres/src/connection.js:1033:8)
```

Working on gathering more detail. Will update shortly

**Comment by nektro** [comment]
this may have been fixed by https://github.com/oven-sh/bun/pull/11322

if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.

**Comment by TimMensch** [comment]
I'm still seeing this on Windows 10 and Windows 11.

The code that hits it is this:

```ts
        return await db.transaction(async (tx) => {
            console.log("User3b")
            let user = await tx.query.User.findFirst({
                where: eq(User.id, body.id),
            });
            console.log("User4")
//...
```

This is using Drizzle to talk to PostgresJS.

It gets to User3b and hangs.

I tried 1.1.38 and 1.1.39 Canary as of today (Dec 2). Hangs at the exact same place on both.

Earlier in the app I have it doing a simple "Count" query on two different PostgreSQL servers, and both return every time. This is obviously a transaction and the query that always works is not a transaction. 

And when I run the exact same code on Node it all works (I tweaked the setup code to wedge in "@hono/node-server" if it detects it's not Bun). 

On Windows 10 the code ... sometimes seems to work? I tried it right after you posted that we should use Canary and it seemed to work for a while. Now it's intermittent and fails reliably on Windows 11.

**Comment by cirospaciari** [comment]
> I'm still seeing this on Windows 10 and Windows 11.
> 
> The code that hits it is this:
> 
>         return await db.transaction(async (tx) => {
>             console.log("User3b")
>             let user = await tx.query.User.findFirst({
>                 where: eq(User.id, body.id),
>             });
>             console.log("User4")
> //...
> This is using Drizzle to talk to PostgresJS.
> 
> It gets to User3b and hangs.
> 
> I tried 1.1.38 and 1.1.39 Canary as of today (Dec 2). Hangs at the exact same place on both.
> 
> Earlier in the app I have it doing a simple "Count" query on two different PostgreSQL servers, and both return every time. This is obviously a transaction and the query that always works is not a transaction.
> 
> And when I run the exact same code on Node it all works (I tweaked the setup code to wedge in "@hono/node-server" if it detects it's not Bun).
> 
> On Windows 10 the code ... sometimes seems to work? I tried it right after you posted that we should use Canary and it seemed to work for a while. Now it's intermittent and fails reliably on Windows 11.

probably the same as https://github.com/oven-sh/bun/issues/15438 and will be fixed by https://github.com/oven-sh/bun/pull/15543

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15543
