### ISSUE TITLE
Bun setup first run - ld.lld: error: undefined symbol: u_hasBinaryProperty_70

### ISSUE THREAD

**Issue by coffee-mug** [oven-sh/bun#9095]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 6.5.0-17-generic x86_64 x86_64

### What steps can reproduce the bug?

- Followed the "Contributing" article from the doc
    - Installed dependencies
    - Installed LLVM
    - Cloned bun repository
    - From bun repo, ran "bun setup"

The error seems to indicate it cannot link libicuuc, so I have checked that I had it on my system and reinstalled it with sudo apt-get libicuuc-dev. Same result

### What is the expected behavior?

Setup successfully completes and I can then run bun build

### What do you see instead?

Pasting the trace:

$ ./scripts/setup.sh
All system dependencies OK
C Compiler for dependencies: /usr/bin/clang-16
C++ Compiler for dependencies: /usr/bin/clang++-16
+ git submodule update --init --recursive --progress --depth=1 --checkout src/deps/picohttpparser src/deps/mimalloc src/deps/zlib src/deps/libarchive src/deps/boringssl src/deps/lol-html src/deps/tinycc src/deps/c-ares src/deps/zstd src/deps/base64 src/deps/ls-hpack
base64 - already built
boringssl - already built
cares - already built
libarchive - already built
lolhtml - already built
mimalloc-debug - already built
mimalloc - already built
tinycc - already built
zlib - already built
zstd - already built
lshpack - already built
(run with -f to rebuild)
bun install v1.0.29 (a146856d)

Checked 183 installs across 197 packages (no changes) [6.00ms]
bun install v1.0.29 (a146856d)

Checked 766 installs across 779 packages (no changes) [8.00ms]
bun install v1.0.29 (a146856d)

Checked 12 installs across 34 packages (no changes) [4.00ms]

  dist/index.js       160.5kb
  dist/bun-error.css   12.8kb

⚡ Done in 27ms
bun install v1.0.29 (a146856d)

Checked 99 installs across 113 packages (no changes) [4.00ms]

  out/crypto.js          679.4kb
  out/zlib.js            219.7kb
  out/stream.js          109.1kb
  out/https.js           100.2kb
  out/http.js            100.0kb
  out/assert.js           58.9kb
  out/querystring.js      33.8kb
  out/string_decoder.js   32.1kb
  out/util.js             28.1kb
  out/sys.js              28.0kb
  out/buffer.js           27.8kb
  out/url.js               8.1kb
  out/domain.js            7.2kb
  out/events.js            6.0kb
  out/path.js              4.8kb
  out/timers.js            3.4kb
  out/process.js           2.3kb
  out/punycode.js          2.3kb
  ...and 5 more output files...

⚡ Done in 125ms
-- Configuring Bun 1.0.29 in /home/lucas/iwill/bun/build
-- The CMake build type is: Debug
-- The C compiler identification is Clang 16.0.6
-- The CXX compiler identification is Clang 16.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-16 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-16 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++ Compiler: Clang 16.0.6 at /usr/bin/clang++-16
-- Building for CPU Target: haswell
-- Installed Zig Compiler: /home/lucas/iwill/bun/.cache/zig/zig
-- Found Bun: /home/lucas/.bun/bin/bun
-- Using ccache: /usr/bin/ccache
-- Using Pre-built WebKit: bun-webkit-linux-amd64-debug
-- Using debug mimalloc
-- Using static sqlite3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lucas/iwill/bun/build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
[1/1] Linking CXX executable bun-debug
FAILED: bun-debug 
: && /usr/bin/clang++-16 -std=c++2a -g -fuse-ld=lld -static-libstdc++ -static-libgcc -Wl,-z,now -Wl,--as-needed -Wl,--gc-sections -Wl,-z,stack-size=12800000 -Wl,--wrap=fcntl -Wl,--wrap=fcntl64 -Wl,--wrap=stat64 -Wl,--wrap=pow -Wl,--wrap=exp -Wl,--wrap=log -Wl,--wrap=log2 -Wl,--wrap=lstat -Wl,--wrap=stat -Wl,--wrap=fstat -Wl,--wrap=fstatat -Wl,--wrap=lstat64 -Wl,--wrap=fstat64 -Wl,--wrap=fstatat64 -Wl,--wrap=mknod -Wl,--wrap=mknodat -Wl,--wrap=statx -Wl,--compress-debug-sections=zlib -Bsymbolics-functions -rdynamic -Wl,--dynamic-list=/home/lucas/iwill/bun/src/symbols.dyn -Wl,--version-script=/home/lucas/iwill/bun/src/linker.lds CMakeFiles/bun-zig.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ActiveDOMCallback.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/AsyncContextFrame.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunClientData.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunCommonStrings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunDebugger.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunGCOutputConstraint.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunInjectedScriptHost.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunInspector.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunPlugin.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunProcess.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunString.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/BunWorkerGlobalScope.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/CallSite.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/CallSitePrototype.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/CodeCoverage.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/CommonJSModuleRecord.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ConsoleObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/DOMException.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/DOMFormData.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/DOMURL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/DOMWrapperWorld.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ErrorStackTrace.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ExposeNodeModuleGlobals.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ImportMetaObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/InternalModuleRegistry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSBuffer.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSBufferEncodingType.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSBufferList.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSBundlerPlugin.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSCTaskScheduler.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSCUSocketsLoopIntegration.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSDOMExceptionHandling.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSDOMFile.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSDOMGlobalObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSDOMWrapper.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSDOMWrapperCache.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSEnvironmentVariableMap.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSFFIFunction.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSMockFunction.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSNextTickQueue.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSReadableHelper.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSReadableState.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSSocketAddress.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSStringDecoder.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/JSWrappingFunction.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/KeyObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/MarkingConstraint.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ModuleLoader.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/NodeHTTP.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/NodeVMScript.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/Path.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ProcessBindingConstants.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ProcessBindingNatives.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ProcessBindingTTYWrap.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ProcessBindingUV.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ProcessIdentifier.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/RegularExpression.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ScriptExecutionContext.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/Serialization.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/Strong.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/URLDecomposition.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/URLSearchParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ZigGeneratedCode.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ZigGlobalObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/ZigSourceProvider.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/bindings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/blob.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/bun-simdutf.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/bun-spawn.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/c-bindings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/coroutine.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/helpers.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/inlines.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/isBuiltinModule.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/napi.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/napi_external.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/objects.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/simdutf.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/spawn.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/sqlite/JSSQLStatement.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/v8.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/AbortController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/AbortSignal.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ActiveDOMObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/BroadcastChannel.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/BunBroadcastChannelRegistry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/CloseEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/CommonAtomStrings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ContextDestructionObserver.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/CustomEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/CustomEventCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/DOMJITHelpers.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ErrorCallback.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ErrorEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/Event.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventContext.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventDispatcher.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventEmitter.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventFactory.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventListenerMap.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventNames.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventPath.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventTarget.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventTargetConcrete.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/EventTargetFactory.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/FetchHeaders.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/HTTPHeaderField.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/HTTPHeaderMap.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/HTTPHeaderNames.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/HTTPHeaderValues.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/HTTPParsers.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/IdentifierEventListenerMap.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/InternalWritableStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSAbortAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSAbortController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSAbortSignal.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSAbortSignalCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSAddEventListenerOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSBroadcastChannel.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSByteLengthQueuingStrategy.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSCallbackData.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSCloseEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSCountQueuingStrategy.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSCustomEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMBindingInternalsBuiltins.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMBuiltinConstructorBase.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMConstructorBase.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMConvertDate.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMConvertNumbers.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMConvertStrings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMConvertWebGL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMException.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMFormData.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMGuardedObject.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMIterator.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMPromise.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMPromiseDeferred.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSDOMURL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSErrorCallback.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSErrorEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSErrorEventCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSErrorHandler.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventDOMJIT.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventEmitter.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventEmitterCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventInit.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventListener.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventListenerOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventModifierInit.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventTarget.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSEventTargetCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSFetchHeaders.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessageChannel.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessageChannelCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessageEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessageEventCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessagePort.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSMessagePortCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformance.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceEntry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceEntryCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceMark.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceMarkOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceMeasure.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceMeasureOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceObserver.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceObserverCallback.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceObserverCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceObserverEntryList.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSPerformanceTiming.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableByteStreamController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamBYOBReader.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamBYOBRequest.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamDefaultController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamDefaultReader.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamSink.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamSource.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSReadableStreamSourceCustom.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSStructuredSerializeOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSTextEncoder.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSTransformStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSTransformStreamDefaultController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSURLSearchParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWebSocket.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWorker.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWorkerOptions.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWritableStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWritableStreamDefaultController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWritableStreamDefaultWriter.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/JSWritableStreamSink.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessageChannel.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessageEvent.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessagePort.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessagePortChannel.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessagePortChannelProvider.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessagePortChannelProviderImpl.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/MessagePortChannelRegistry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/Performance.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceEntry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceMark.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceMeasure.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceObserver.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceObserverEntryList.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceTiming.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/PerformanceUserTiming.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ReadableStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ReadableStreamDefaultController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ReadableStreamSink.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ReadableStreamSource.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/ScriptWrappable.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/SerializedScriptValue.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/SharedBuffer.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/StructuredClone.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/TextEncoder.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/WebCoreTypedArrayController.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/WebSocket.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/Worker.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/WritableStream.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcore/weak_handle.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CommonCryptoDERUtilities.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CBC.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CBCOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CFB.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CFBOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CTR.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_CTROpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_GCM.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_GCMOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_KW.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmAES_KWOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDH.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDHOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDSA.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmECDSAOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmEd25519.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHKDF.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHKDFOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHMAC.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmHMACOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmPBKDF2.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmPBKDF2OpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSAES_PKCS1_v1_5.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSAES_PKCS1_v1_5OpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSASSA_PKCS1_v1_5.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSASSA_PKCS1_v1_5OpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_OAEP.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_OAEPOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_PSS.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRSA_PSSOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRegistry.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmRegistryOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA1.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA224.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA256.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA384.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoAlgorithmSHA512.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoDigest.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKey.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyAES.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyEC.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyECOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyHMAC.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyOKP.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyOKPOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSA.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSAComponents.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyRSAOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/CryptoKeyRaw.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSAesCbcCfbParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSAesCtrParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSAesGcmParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSAesKeyParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoAesKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoAlgorithmParameters.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoEcKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoHmacKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoKey.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyPair.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoKeyUsage.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoRsaHashedKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSCryptoRsaKeyAlgorithm.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSEcKeyParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSEcdhKeyDeriveParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSEcdsaParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSHkdfParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSHmacKeyParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSJsonWebKey.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSPbkdf2Params.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaHashedImportParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaHashedKeyGenParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaKeyGenParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaOaepParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaOtherPrimesInfo.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSRsaPssParams.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/JSSubtleCrypto.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/OpenSSLUtilities.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/SerializedCryptoKeyWrapOpenSSL.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/webcrypto/SubtleCrypto.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/workaround-missing-symbols.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/bindings/wtf-bindings.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/modules/BunObjectModule.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/modules/NodeTTYModule.cpp.o CMakeFiles/bun-debug.dir/src/bun.js/modules/ObjectModule.cpp.o CMakeFiles/bun-debug.dir/src/deps/libuwsockets.cpp.o CMakeFiles/bun-debug.dir/src/deps/picohttpparser/picohttpparser.c.o CMakeFiles/bun-debug.dir/src/io/io_darwin.cpp.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/constants.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/context.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/dictionary.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/platform.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/shared_dictionary.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/common/transform.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/dec/bit_reader.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/dec/decode.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/dec/huffman.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/dec/state.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/backward_references.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/backward_references_hq.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/bit_cost.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/block_splitter.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/brotli_bit_stream.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/cluster.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/command.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/compound_dictionary.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/compress_fragment.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/compress_fragment_two_pass.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/dictionary_hash.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/encode.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/encoder_dict.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/entropy_encode.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/fast_log.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/histogram.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/literal_cost.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/memory.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/metablock.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/static_dict.c.o CMakeFiles/bun-debug.dir/src/deps/brotli/enc/utf8_util.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/bsd.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/context.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/crypto/openssl.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/crypto/root_certs.cpp.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/crypto/sni_tree.cpp.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/eventing/epoll_kqueue.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/eventing/libuv.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/loop.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/quic.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/socket.c.o CMakeFiles/bun-debug.dir/packages/bun-usockets/src/udp.c.o CMakeFiles/bun-debug.dir/codegen/ZigGeneratedClasses.cpp.o CMakeFiles/bun-debug.dir/codegen/JSSink.cpp.o CMakeFiles/bun-debug.dir/codegen/WebCoreJSBuiltins.cpp.o -o bun-debug  -lc  -lpthread  -ldl  -Wl,-Bstatic  -latomic  -Wl,-Bdynamic  bun-webkit/lib/libicudata.a  bun-webkit/lib/libicui18n.a  bun-webkit/lib/libicuuc.a  ../src/deps/libz.a  ../src/deps/libcrypto.a  ../src/deps/libssl.a  ../src/deps/libdecrepit.a  ../src/deps/libarchive.a  ../src/deps/libmimalloc-debug.a  ../src/deps/libzstd.a  ../src/deps/libcares.a  ../src/deps/libbase64.a  ../src/deps/libtcc.a  ../src/deps/liblolhtml.a  libsqlite3.a  ../src/deps/liblshpack.a  bun-webkit/lib/libWTF.a  bun-webkit/lib/libJavaScriptCore.a  bun-webkit/lib/libbmalloc.a && :
ld.lld: warning: version script assignment of 'BUN_1.0' to symbol '__cxa_atexit' failed: symbol not defined
ld.lld: warning: version script assignment of 'BUN_1.0' to symbol '__cxa_thread_atexit_impl' failed: symbol not defined
ld.lld: error: undefined symbol: u_hasBinaryProperty_70
>>> referenced by workaround-missing-symbols.cpp:376 (/home/lucas/iwill/bun/src/bun.js/bindings/workaround-missing-symbols.cpp:376)
>>>               CMakeFiles/bun-debug.dir/src/bun.js/bindings/workaround-missing-symbols.cpp.o:(icu_hasBinaryProperty)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
error: script "setup" exited with code 1

### Additional information

Not at this stage

**Comment by Jarred-Sumner** [comment]
Fixed

**Comment by coffee-mug** [comment]
Thanks a lot @Jarred-Sumner for your reactivity, you're fast as light ! 

Still it did not fix it for me: I have tried the following without success

- Git pull && bun setup fails with same error
- re-clone the repo to start fresh without possible cache

For additional context:
`pkg-config --modversion icu-i18n` yields 70.1
find /usr/lib -name "libicuuc.so" yields: /usr/lib/x86_64-linux-gnu/libicuuc.so

Do I need to add a specific env variable so the linker finds the lib?

Thanks again

**Comment by almmiko** [comment]
Hey @coffee-mug could you try to clone the repo again and run `bun setup`.

I had the same problem when just `git pull`, but on the completely fresh setup (git clone) the build went without issues.

UPD: or `rm -rf build zig-cache && bun setup`

**Comment by coffee-mug** [comment]
Thanks a lot @almmiko when cloning again in a different location did the trick !
