### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by R0N1n-dev** [oven-sh/bun#961]
### Version

0.1.4

### Platform

Linux ronin-HP-Laptop 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Installed bun .
Added to bashrc.

Ran 'bun -v'

### What is the expected behavior?

bun --version to appear

### What do you see instead?

illegal instruction

**Comment by ghost** [comment]
Can you try it with v0.1.6? That probably fixes it.

**Comment by Jarred-Sumner** [comment]
Fixed in v0.1.6

**Comment by R0N1n-dev** [comment]
That installation process needs to be clearer.still not working. any bun command brings 'illegal instruction'. The installation needs to be redone to be really clear about the bash stuff and what to do after installation.

**Comment by R0N1n-dev** [comment]
what reproduction do you want me to give you, i have literally told you this happened after installing and trying to add bun to bash.
Not all of us are super linux pros but if asking for some clarity is a problem,   then .................
