### ISSUE TITLE
`bun wiptest` throws a Segfault

### ISSUE THREAD

**Issue by DarthBenro008** [oven-sh/bun#969]
### Version

0.1.3

### Platform

Darwin MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Create a testfile as follows

```typescript
import { describe, expect, toBe } from "bun:test";

describe("checking if wiptest works", () => {
  expect(2 + 2).toBe(4);
});
```

run the following command: `bun wiptest`

It throws a segfault error

### How often does it reproduce? Is there a required condition?

Always!

### What is the expected behavior?

For bun wiptest to run tests without segfaulting, or give meaningful error messages if something is wrong with the test file.

### What do you see instead?

I see a segfault as follows 

```bash
SegmentationFault at 4


–––– bun meta ––––
Bun v0.1.3 macOS Silicon 21.5.0
TestCommand:
Elapsed: 8ms | User: 9ms | Sys: 5ms
RSS: 17.40MB | Peak: 17.40MB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

### Additional information

<img width="743" alt="image" src="https://user-images.githubusercontent.com/31009634/182454004-eb401ded-56b9-4384-b103-ecce1fa99bdb.png">

**Comment by Jarred-Sumner** [comment]
This shouldn’t segfault, but you mean `it` instead of `describe`

**Comment by zhuzilin** [comment]
Could you give another try with version 0.1.6? It seems that the segfault is fixed.

**Comment by DarthBenro008** [comment]
@zhuzilin , the segfault still occurs in `0.1.6`

```bash
random.test.ts:

SegmentationFault at 0x0400000000000000


–––– bun meta ––––
Bun v0.1.6 macOS Silicon 21.5.0
TestCommand:
Elapsed: 8ms | User: 9ms | Sys: 5ms
RSS: 18.07MB | Peak: 18.07MB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––
```

<img width="606" alt="image" src="https://user-images.githubusercontent.com/31009634/182894616-5ab2d4d3-38a0-43c2-90ac-0b52b7ddd0fd.png">

**Comment by wearypossum4770** [comment]
I am getting a similar error. I upgraded moments ago. Also would there be any plans to allow `test.each` or `it.each` maybe in a thread-safe concurrent way?  How would someone build bun from source on a Android Linux (Termux) environment? The script installs but it says can't find the file from bash.
![image](https://user-images.githubusercontent.com/50812322/182908011-78ea5fa0-7041-403a-ae9a-c790a13d70f2.png)

**Comment by zhuzilin** [comment]
>  the segfault still occurs in 0.1.6

Ahh... Then it seems like a fault on mac specifically, as I was testing on ubuntu...

**Comment by DarthBenro008** [comment]
@zhuzilin , i am afraid the segfault also occurs in arch linux, as you can see below in the screenshot.

![WhatsApp Image 2022-08-06 at 3 07 50 AM](https://user-images.githubusercontent.com/31009634/183212335-09058f13-0043-48bd-8439-c2546e33b8e8.jpeg)

**Comment by zhuzilin** [comment]
I found out that I was testing the wrong way, sorry about that. The pr should fix this segfault.
